pdm/cli/actions.py, pdm/cli/commands.py, pdm/context.py, pdm/exceptions.py, pdm/models/environment.py, pdm/project/core.py, pdm/ui.py, pdm/utils.py, tests/cli/test_actions.py, tests/cli/test_cli.py, tests/conftest.py
=> Refactor error handling

pdm/cli/actions.py, pdm/cli/commands.py, pdm/cli/dependencies.py, pdm/models/candidates.py, pdm/models/repositories.py, pdm/project/core.py, tests/cli/test_actions.py
=> new option: list --graph

pdm/cli/actions.py, pdm/cli/commands.py, pdm/installers.py, pdm/models/repositories.py, tests/cli/test_actions.py
Close #13
```
pdm update -u <package>
```
=> Update ignore version constraints

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/.ci.yml, news/41.bugfix, news/42.dep, news/42.feature, pdm.lock, pdm/builders/wheel.py, pdm/cli/commands.py, pdm/project/core.py, pyproject.toml
- Close #41 
- Add a fancy banner when user types `pdm --help`
=> Fix the bug of wheel/RECORD

.github/workflows/.ci.yml, news/43.bugfix, pdm.lock, pdm/installers.py, pdm/models/environment.py, pdm/utils.py, setup_dev.py
=> patch sys.executable when activating env

news/48.bugfix, pdm/installers.py, pdm/models/candidates.py, pdm/models/environment.py
=> install compatible wheels

news/49.feature, news/50.feature, pdm/cli/actions.py, pdm/cli/commands.py, tests/cli/test_cli.py
=> improve init command to add more options

news/47.bugfix, pdm/models/candidates.py, pdm/models/repositories.py, pdm/project/core.py, tests/resolver/test_resolve.py
=> Merge markers correctly from different parents

news/54.feature, pdm/cli/actions.py, pdm/cli/commands.py, tests/cli/test_cli.py
=> better python selector

news/56.bugfix, pdm/installers.py
=> fix wheel installer

.github/workflows/ci.yml, .github/workflows/release.yml
=> add release pipeline

.github/workflows/doc.yml, .gitignore, README.md, README_zh.md, docs/docs/changelog.md, docs/docs/contributing.md, docs/docs/dependency.md, docs/docs/index.md, docs/docs/project.md, docs/docs/pyproject.md, docs/mkdocs.yml, news/14.doc, pdm.lock, pdm/project/core.py, pyproject.toml
=> documentation

.pre-commit-config.yaml, docs/docs/dependency.md, docs/docs/index.md, docs/docs/project.md, news/26.feature, pdm/cli/commands.py, pdm/cli/config.py, pdm/cli/options.py, pdm/exceptions.py, pdm/installers.py, pdm/project/config.py, pdm/project/core.py, pdm/ui.py, pdm/utils.py, pyproject.toml, setup.cfg, tests/cli/test_cli.py, tests/conftest.py, tests/test_project.py
=> New feature: pdm config

news/62.bugfix, pdm/cli/commands.py, pdm/cli/config.py, pdm/cli/dependencies.py, pdm/project/meta.py, tests/cli/test_actions.py, tests/conftest.py
=> fix circular dependency display

news/63.feature, pdm/cli/cache.py, pdm/cli/commands.py, tests/cli/test_cli.py
=> new command cache clear

news/66.bugfix, news/67.feature, pdm/cli/actions.py, pdm/cli/commands.py, pdm/models/specifiers.py, tests/resolver/test_resolve.py
=> Fix python version subset check

news/68.bugfix, pdm/models/requirements.py, pdm/utils.py, tests/models/test_requirements.py
=> Fix SSH URL parsing

CHANGELOG.md, docs/docs/project.md, news/30.doc, news/30.feature, pdm.lock, pdm/_editable_install.py, pdm/cli/actions.py, pdm/cli/commands.py, pdm/cli/config.py, pdm/cli/options.py, pdm/installers.py, pdm/models/environment.py, pdm/project/config.py, pdm/project/core.py, pdm/utils.py, tests/cli/test_cli.py, tests/conftest.py, tests/test_project.py
Close #30 
Install into global python:
```bash
$ pdm install -g
```
Show packages in global python:
```bash
$ pdm list -g --graph
```
Choose another directory as global project(temporarily):
```bash
$ pdm install -g -p .
```
=> New option: -g/--global

docs/docs/project.md, news/30.feature, news/71.feature, pdm/cli/actions.py, pdm/cli/config.py, pdm/models/environment.py, pdm/project/config.py, pdm/project/core.py, tests/conftest.py, tests/test_project.py
Refactor the config system, separate the handling of global and project-level config.
=> Refactor configuration system

.github/workflows/ci.yml, .github/workflows/release.yml, news/72.feature, pdm/project/core.py
=> Add a mininum dep set for global project

docs/docs/project.md, docs/mkdocs.yml, news/74.feature, pdm/cli/commands/config.py, pdm/cli/utils.py, pdm/project/config.py, pdm/project/core.py, pdm/utils.py, tests/cli/test_cli.py, tests/conftest.py, tests/test_project.py
=> support using venv

docs/docs/plugin.md, docs/docs/project.md, pdm/core.py, pdm/installers.py, pdm/project/config.py, tests/cli/test_actions.py, tests/conftest.py, tests/test_plugin.py
=> parallel install mode

docs/docs/pyproject.md, news/23.feature, pdm/builders/base.py, pdm/builders/wheel.py
=> support build script

news/89.bugfix, news/89.dep, pdm.lock, pdm/cli/actions.py, pdm/installers.py, pdm/models/caches.py, pdm/models/environment.py, pdm/project/core.py, pdm/project/meta.py, pdm/utils.py, pyproject.toml, setup.cfg, setup_dev.py, tests/cli/test_actions.py, tests/cli/test_cli.py, tests/test_project.py
=> validate python_requires

news/92.bugfix, pdm/installers.py, tests/cli/test_actions.py
=> only remove if it isn't required by any

news/90.bugfix, pdm/installers.py, pdm/iostream.py, pdm/models/environment.py
=> ensure wheel package is installed

news/97.feature, pdm/models/environment.py, pdm/project/core.py, pdm/utils.py
=> Auto detect venvs

news/96.feature, pdm/cli/actions.py, pdm/models/environment.py
=> update shebang lines

docs/docs/project.md, news/99.bugfix, pdm/builders/base.py, pdm/builders/wheel.py, pdm/project/meta.py, pdm/utils.py
=> fix extension building

news/101.bugfix, pdm/formats/flit.py, pdm/formats/poetry.py, tests/cli/test_cli.py
=> Fix toml parsing error

pdm/cli/actions.py, pdm/installers/__init__.py, pdm/installers/installers.py, pdm/installers/synchronizers.py, tests/conftest.py
Refactor the installers module
=> Restructure the installers module into a package

README.md, README_zh.md, news/100.feature, pdm/_editable_install.py, pdm/cli/actions.py, pdm/installers/installers.py, pdm/installers/site.py, pdm/installers/synchronizers.py, pdm/models/environment.py, tests/cli/test_cli.py, tests/conftest.py, tests/test_project.py
=> Disable loading of site-packages for PEP 582

pdm/installers/synchronizers.py, pdm/models/environment.py, tests/cli/test_actions.py, tests/conftest.py
=> ensure setuptools is installed

news/107.bugfix, pdm/models/markers.py, pdm/models/requirements.py, tests/conftest.py, tests/resolver/test_resolve.py
=> fix marker evaluation

.github/ISSUE_TEMPLATE/bug_report.md, docs/docs/project.md, news/111.feature, news/112.bugfix, pdm/_types.py, pdm/cli/actions.py, pdm/cli/commands/search.py, pdm/exceptions.py, pdm/iostream.py, pdm/models/repositories.py, pdm/models/xmlrpc.py, pdm/project/config.py, pdm/project/core.py, pdm/utils.py, tests/cli/test_cli.py
Consult XMLRPC API for package searching
Close #111
=> search command

news/114.feature, pdm/cli/commands/search.py, pdm/cli/commands/show.py, pdm/models/metadata.py, tests/cli/test_cli.py
`pdm show` show package metadata in tabulated output
=> New command: show

news/120.bugfix, pdm/models/candidates.py, tests/fixtures/artifacts/celery-4.4.2-py2.py3-none-any.whl, tests/models/test_candidates.py
=> Fix specifier parsing of distlib

.github/workflows/ci.yml
=> See what is breaking

news/138.bugfix, pdm/project/core.py
=> bugfix: Spaces in path causes requirement parse error

news/141.bugfix, pdm/models/repositories.py, pdm/models/requirements.py, pdm/resolver/providers.py, tests/conftest.py, tests/resolver/test_resolve.py
=> Respect python requires of single dependency

news/137.feature, pdm/cli/actions.py, pdm/cli/commands/list.py, pdm/cli/utils.py, pdm/models/builders.py, pdm/models/environment.py, tests/cli/test_actions.py
=> New feature: reverse dependency graph

.github/workflows/doc.yml
Support multi version docs by git tag
close #147
=> Support multi version docs

news/153.feature, pdm/models/environment.py, pdm/utils.py
=> cache built wheels

.github/workflows/ci.yml, news/156.bugfix, pdm/cli/actions.py, pdm/models/builders.py
=> fix parallel installation

docs/docs/project.md, news/157.feature, pdm/cli/commands/config.py, tests/cli/test_cli.py, tests/test_plugin.py
Make `pdm config` work like git command
=> Git style config command

news/158.bugfix, pdm/installers/_editable_install.py, pdm/installers/installers.py, pdm/models/builders.py
=> Determine whether to inject custom site by env type

docs/docs/index.md, news/159.feature, pdm.lock, pdm/cli/commands/completion.py, pyproject.toml, tests/cli/test_cli.py
=> Feature: Support generating completion scripts

docs/docs/project.md, news/162.bugfix, pdm.lock, pdm/cli/actions.py, pdm/iostream.py, pdm/models/builders.py, pdm/models/environment.py, pdm/utils.py, pyproject.toml, setup.cfg, tests/fixtures/projects/demo-combined-extras/pyproject.toml, tests/fixtures/projects/demo-module/pyproject.toml, tests/fixtures/projects/demo-package/pyproject.toml, tests/fixtures/projects/demo-src-package/pyproject.toml, tests/fixtures/projects/test-plugin-pdm/pyproject.toml
=> Refactor: Use a home grown PEP 517 build frontend

news/165.bugfix, pdm/models/builders.py, pdm/models/specifiers.py, tests/models/test_specifiers.py
=> bugfix: change the is_subset check logic

docs/docs/project.md, news/168.feature, pdm/cli/commands/run.py, pdm/models/environment.py, pdm/project/core.py, tests/cli/test_cli.py, tests/cli/test_run.py, tests/conftest.py
=> pdm run support predefined scripts

news/170.bugfix, pdm.lock, pdm/models/markers.py, pdm/resolver/core.py, pdm/resolver/metaset.py, tests/resolver/test_resolve.py
=> Simply the marker extracting logic

news/176.feature, pdm/cli/commands/run.py, pyproject.toml, tests/cli/test_cli.py, tests/cli/test_run.py
=> Supporting running scripts directly

docs/docs/project.md, news/178.feature, pdm.lock, pdm/cli/commands/run.py, pyproject.toml, tests/cli/test_run.py
=> Support dotenv file loading

pdm/cli/commands/build.py
Fix description
<s>我也来混个 PR</s>
=> Fix description of `build` command

news/187.bugfix, pdm/cli/commands/cache.py, pdm/cli/commands/remove.py
Some help messages.
BTW, would you mind me adding an hand-written zsh completion script for this project?
=> Fix help message of some command

setup_dev.py
I don't know whether this pr need a news entry. I will add one if needed.
`pdm config` doesn't need a `set` action. I removed it from setup_dev.py
=> Fix setup_dev.py

.github/workflows/ci.yml, docs/docs/index.md, pdm.lock, pdm/cli/actions.py, pdm/models/requirements.py, pdm/project/core.py, tests/cli/test_actions.py
=> add tests for editable install

.github/workflows/ci.yml, news/212.feature, pdm/cli/actions.py, pdm/cli/commands/init.py, pdm/models/builders.py, pdm/models/environment.py, pdm/models/in_process.py, pdm/pep582/sitecustomize.py, pdm/project/core.py, pdm/utils.py, tests/cli/test_cli.py, tests/test_project.py
=> Use a different packages directory for Windows 32bit installation

.github/workflows/ci.yml, docs/docs/project.md, news/219.feature, pdm/models/caches.py, pdm/models/environment.py, pdm/project/config.py, pdm/project/core.py, pdm/utils.py, tests/conftest.py, tests/test_project.py
=> Auto disable PEP 582 when a venv-like python is given

news/221.feature, pdm/cli/actions.py, pdm/cli/utils.py, tests/test_utils.py
=> Support specifying Python interpreter by `pdm use <path-to-python-root>`.

.github/workflows/ci.yml, docs/docs/dependency.md, news/226.feature.rst, pdm/models/auth.py, pdm/models/candidates.py, pdm/models/environment.py, pdm/models/requirements.py, pdm/project/core.py, pdm/utils.py, tests/models/test_candidates.py, tests/test_utils.py
=> Feature #226 Introducing ${PROJECT_ROOT} environment variable

news/235.dep, pdm.lock, pyproject.toml
=> Test pip 21.0

news/236.feature, pdm/cli/utils.py, pdm/resolver/core.py, pdm/resolver/providers.py
=> change dependencies to a list of PEP 508 strings

docs/docs/project.md, news/238.feature, pdm/cli/actions.py, pdm/project/config.py, pdm/resolver/core.py
=> Make resolve max rounds configurable

docs/docs/dependency.md
Mention editable mode when adding packages.
IMHO it's too small to actually mention it in the news.
=> docs: mention editable mode installation

CHANGELOG.md, CONTRIBUTING.md, README.md, docs/docs/dependency.md, docs/docs/index.md, docs/docs/plugin.md, docs/docs/project.md, docs/docs/pyproject.md
Fixed some typos. I'm not a native speaker, so feel free to keep/revert what you like.
=> docs: fix some typos

news/240.feature, pdm/installers/synchronizers.py, pdm/models/builders.py
=> rewrite the egg info when dependencies change

news/234.bugfix, news/245.feature, pdm.lock, pdm/formats/requirements.py, pdm/models/requirements.py, pdm/project/core.py, tests/test_formats.py
=> Feature: Build the wheel to find the name when importing from requirements.txt

news/262.bugfix.md, news/263.bugfix.md, pdm/cli/actions.py, pdm/formats/legacy.py, pdm/formats/pipfile.py, pdm/formats/poetry.py, pdm/project/core.py
=> Bugfix: Use the absolute path for destination path

docs/docs/index.md
Small comment about how to use tools from local environment (e.g. pytest) in PyCharm. Feel free to rephrase.
=> docs: add comment about PATH in PyCharm

news/270.bugfix.md, pdm/resolver/core.py, tests/resolver/test_resolve.py
=> Bugfix: sections resolving failure when circular dependencies exist

news/275.bugfix.rst, pdm/models/requirements.py, tests/models/test_requirements.py
=> Make requirement complying with PEP 508

news/278.bugfix.rst, pdm/installers/installers.py, pdm/installers/synchronizers.py, pdm/models/candidates.py, tests/cli/test_actions.py, tests/conftest.py
=> Editable package should override the non-editable version

.github/workflows/ci.yml
=> Fix ubuntu env error

news/283.feature.md, pdm/cli/actions.py, pdm/cli/commands/init.py, pdm/cli/commands/run.py, pdm/cli/options.py, pdm/core.py, pdm/models/environment.py, pdm/project/core.py, pdm/utils.py, tests/cli/test_cli.py, tests/cli/test_run.py, tests/test_project.py
=> Support transient Python interpreter path setting

news/286.feature.md, pdm/cli/commands/base.py, pdm/cli/commands/build.py, pdm/cli/commands/export.py, pdm/cli/commands/import_cmd.py, pdm/cli/commands/info.py, pdm/cli/commands/init.py, pdm/cli/commands/run.py, pdm/cli/options.py, pdm/core.py, pdm/models/requirements.py, pdm/pep582/sitecustomize.py, pdm/project/core.py, pdm/resolver/providers.py, tests/cli/test_cli.py, tests/cli/test_run.py, tests/conftest.py, tests/models/test_requirements.py
=> Add `-p/--project` option and deprecate the usage of `-g/--global` with values

news/291.feature.md, pdm/cli/actions.py, pdm/cli/commands/import_cmd.py, pdm/formats/flit.py, pdm/formats/legacy.py, pdm/formats/pipfile.py, pdm/formats/poetry.py, pdm/formats/requirements.py, pdm/formats/setup_py.py, tests/cli/test_cli.py, tests/test_formats.py
=> Import dependencies from files to dev-dependencies or sections

news/298.misc.md, pdm/cli/commands/base.py, pdm/core.py, pdm/models/builders.py, pdm/models/caches.py, pdm/models/candidates.py, pdm/models/pip_shims.py, pdm/models/readers.py, pdm/models/requirements.py, pdm/models/specifiers.py, pdm/project/config.py, pdm/project/core.py, pdm/resolver/core.py, pdm/resolver/providers.py, pdm/resolver/reporters.py, tests/conftest.py
- replaced a few type comments with type annotations
wanted to check this was of interest before i got too deep into this
=> update type annotations

news/303.feature.md, pdm/_types.py, pdm/models/specifiers.py, pdm/models/versions.py, setup.cfg, tests/models/test_versions.py
=> Refactor: Extract version logic to a separated module

news/305.bugfix.md, pdm/models/requirements.py, tests/models/test_candidates.py, tests/models/test_requirements.py
=> Pin the VCS revision for non-editable VCS candidates in the lock file

news/314.bugfix.md, pdm/models/candidates.py, pdm/models/requirements.py, tests/models/test_candidates.py
=> Preserve the revision and don't make in into the requirement

docs/docs/plugin.md, news/318.feature.md, pdm/__init__.py, pdm/__main__.py, pdm/cli/commands/init.py, pdm/core.py, pdm/project/__init__.py, tests/conftest.py
1. Re-exports some useful objects/models in the top package for plugin development.
2. Remove the `main` singleton throughout
=> Export some objects in the top package

news/323.misc.md, pdm/cli/actions.py, pdm/models/requirements.py
=> fix a few little typos

news/308.bugfix.md, pdm/models/builders.py
=> Fix UnicodeDecodeError

news/329.feature.md, pdm/cli/commands/cache.py, pdm/cli/utils.py, pdm/core.py, pdm/models/environment.py, pdm/models/pip_shims.py, pdm/project/core.py, pdm/termui.py, tests/cli/test_cache.py, tests/cli/test_cli.py
=> Feature: cache command: (list/remove)

news/333.feature.md, pdm/formats/flit.py, tests/fixtures/projects/flit-demo/flit.py, tests/test_formats.py
Related issue https://github.com/pdm-project/pdm-pep517/issues/10
=> Retrieve flit's version and description by parsing the ast

pdm.lock
=> Update pdm-pep517 to latest version

CHANGELOG.md, news/338.bugfix.md, news/cmd-scripts-array.md, pdm/installers/installers.py, pdm/models/builders.py, pdm/models/candidates.py, pdm/models/environment.py, pdm/models/readers.py
=> Quit early when wheel fails to build

news/343.feature.md, pdm/cli/commands/cache.py
=> feat: better UI for cache clear command

news/344.feature.md, pdm/installers/synchronizers.py, pdm/models/environment.py, pdm/project/core.py, tests/cli/test_actions.py
=> Always update editable installations when syncing

news/352.feature.rst, pdm/cli/actions.py, pdm/cli/commands/init.py, tests/cli/test_cli.py
- Achieve this proposal https://github.com/pdm-project/pdm/discussions/350
- skip the first prompt of `pdm init`
=> Skip the first prompt of `pdm init`

news/349.bugfix.md, pdm/models/candidates.py, pdm/models/environment.py, pdm/utils.py
=> Get revision from VCS url if source code isn't downloaded

news/360.misc.md, pdm/formats/base.py, pdm/formats/flit.py, pdm/formats/legacy.py, pdm/formats/poetry.py
=> Refactor the format converter to be more explicit

news/361.removal.md, pdm/cli/commands/import_cmd.py, pdm/cli/commands/init.py, pdm/cli/options.py, pdm/core.py, pdm/models/builders.py, tests/cli/test_cli.py
This usage was deprecated in 1.4.0 via #286
=> Remove the support of project path following -g

news/346.bugfix.md, pdm/models/environment.py
=> Try fixing the platform lib issue

news/368.feature.md, pdm.lock, pdm/cli/commands/init.py, pdm/core.py, tests/cli/test_cli.py
=> Non-interactive init command

news/369.bugfix.md, pdm/models/in_process.py
Python commands  in `pdm.models.in_process` which invoked via `subprocess` need to run in isolated mode [-I](https://docs.python.org/3/using/cmdline.html#id2), to avoid importing user packages. (like the `json.py` file in the current directory, etc)
=> Python runs in isolated mode to avoid importing user packages

news/370.bugfix.md, pdm/cli/actions.py, pdm/cli/options.py, pdm/cli/utils.py, pdm/formats/requirements.py, tests/cli/test_cli.py, tests/test_formats.py, tests/test_utils.py
=> Don't overwrite existing dependencies

news/372.feature.md, pdm/cli/actions.py, pdm/cli/commands/info.py, pdm/cli/commands/search.py
=> show packages root in pdm info

.github/workflows/ci.yml, news/377.misc.md, pdm/installers/_editable_install.py, pdm/models/builders.py, pdm/models/in_process.py, pdm/pep508.py, pyproject.toml, setup.cfg, tests/test_integration.py
=> add integration test

news/381.dep.md, pdm.lock, pdm/resolver/core.py, pdm/resolver/providers.py, pyproject.toml
=> Upgrade resolvelib to 0.6.0

news/383.misc.md, pdm/cli/actions.py, pdm/cli/commands/info.py, pdm/models/environment.py, pdm/models/pip_shims.py, pdm/models/python.py, pdm/project/core.py, pdm/utils.py
=> Extract python info to its own module

news/384.feature.md, pdm/builders/__init__.py, pdm/builders/base.py, pdm/builders/egg_info.py, pdm/builders/sdist.py, pdm/builders/wheel.py, pdm/cli/actions.py, pdm/installers/installers.py, pdm/models/environment.py
- Restructure the `builders` module to be a standalone package
- Use a similar approach to pip to enable isolated build, a downgrade of performance may be expected as requirements are re-installed for every build env.
=> Improve the builders to be run in isolated env

CHANGELOG.md, pdm/core.py, pdm/project/core.py, tests/cli/test_actions.py, tests/cli/test_cli.py, tests/conftest.py, tests/models/test_candidates.py, tests/test_project.py
=> Give warning message when the project automatically fallbacks

news/387.bugfix.md, pdm/installers/installers.py
=> Enquote executable path to ensure generating valid scripts

pdm/_types.py, pdm/builders/base.py, pdm/cli/commands/base.py, pdm/cli/commands/completion.py, pdm/cli/commands/run.py, pdm/cli/commands/search.py, pdm/core.py, pdm/formats/__init__.py, pdm/formats/base.py, pdm/formats/flit.py, pdm/formats/legacy.py, pdm/formats/pipfile.py, pdm/formats/poetry.py, pdm/formats/requirements.py, pdm/installers/synchronizers.py, pdm/models/caches.py, pdm/models/candidates.py, pdm/models/in_process/__init__.py, pdm/project/config.py, pdm/project/core.py, pdm/project/metadata.py, pdm/termui.py, pdm/utils.py, setup.cfg
=> Progressive typing

news/390.dep.md, pdm.lock, pdm/resolver/providers.py, pyproject.toml
- Update `pdm-pep517` to `0.7.0`
- Update `resolvelib` to `0.7.0`
=> Update pdm-pep517 and resolvelib

news/399.bugfix.md, pdm/builders/base.py
=> Recognize sources when building

news/401.bugfix.md, pdm/cli/utils.py
Make func translate_sections pure to avoid exporting requirements in random order. resolve #401
=> Make func translate_sections pure.

news/410.bugfix.md, pdm/cli/actions.py
=> Check before setting the PYTHONPATH environment variable for PEP582

news/412.dep.md, pdm.lock, pdm/models/environment.py, pdm/models/pip_shims.py, tests/conftest.py, tests/test_project.py
=> Update pip to 21.1 and fix compatibility issues

news/404.bugfix.md, setup_dev.py
=> Inform user to enable PEP 582 for development script to work

news/415.bugfix.md, setup_dev.py
=> Fix development setup error.

news/407.bugfix.md, pdm/installers/_editable_install.py, pdm/installers/installers.py
=> Fix a bug that executing `setup.py` failed for NameError

docs/docs/index.md, pdm/builders/base.py
Ref: 89d6117
~~- [ ] A news fragment is added in `news/` describing what is new.~~
~~- [ ] Test cases added for changed code.~~
=> Remove last usage of obsolete $PDM_PYTHON_PEP582

.mypy.ini, news/427.misc.md, news/428.misc.md, pdm/cli/actions.py, pdm/cli/utils.py, pyproject.toml
address a handful of type errors in `pdm.cli.actions`
this is stacked on #427
=> Refactor pdm.cli.actions

.pre-commit-config.yaml, pdm/formats/base.py, pdm/models/repositories.py, pdm/utils.py
not sure if this is of interest. Bugbear adds a few slightly opinionated lints
=> add bugbear linting

.mypy.ini, .pre-commit-config.yaml, news/427.misc.md, pdm/cli/utils.py, pdm/models/setup.py, pdm/termui.py
add mypy precommit hook with incremental 'whitelisting'
=> add mypy pre-commit hook

news/442.dep.md, pdm.lock, pdm/models/auth.py, pyproject.toml
=> Remove keyring as a dependency

.github/workflows/ci.yml, news/457.misc.md, pdm.lock
=> Test on Python 3.10.0 beta

docs/docs/pyproject/tool-pdm.md
https://github.com/pdm-project/pdm/discussions/440
=> docs: Improve namespace packages detection instructions

docs/docs/usage/advanced.md
Added a Dockerfile example. Related to #443
=> docs: Add multi-stage Dockerfile example

docs/docs/usage/advanced.md
Add note in documentation, related to #435
=> docs: Add note about setting a HOME in CI

docs/docs/index.md
https://github.com/pdm-project/pdm/discussions/376
=> docs: Improve VSCode integration examples

news/463.feature.md, pdm/cli/actions.py, pdm/cli/commands/install.py, pdm/project/core.py
=> Check if lockfile is compatible with PDM

news/465.dep.md, pdm.lock, pdm/cli/actions.py, pdm/cli/commands/run.py, pdm/cli/utils.py, pdm/formats/base.py, pdm/formats/requirements.py, pdm/project/config.py, pdm/project/core.py, pdm/project/metadata.py, pdm/utils.py, pyproject.toml
=> Migrate from tomlkit to atoml

docs/docs/pyproject/pep621.md, docs/docs/pyproject/tool-pdm.md, docs/docs/usage/advanced.md, docs/docs/usage/dependency.md, docs/docs/usage/project.md, news/472.doc.md
I found more bad links thanks to #472.
=> Fix 404 links in documetation.

pdm/builders/base.py, pdm/formats/pipfile.py, pdm/formats/poetry.py, pdm/formats/requirements.py, pdm/installers/installers.py, pdm/models/caches.py, pdm/utils.py
=> Fix typing

setup_dev.py
Change to pdm's base dir, for when it is run from elsewhere.
(Alternatively it could add `-p` to ~3 commands.)
=> fix(setup_dev): chdir to BASE_DIR

.github/workflows/ci.yml, news/510.feature.md, pdm/cli/commands/plugin.py, pdm/core.py, tests/cli/test_plugin.py, tests/test_plugin.py
=> Feature: plugin subcommand

.github/workflows/ci.yml, .github/workflows/release.yml, README.md, README_zh.md, docs/docs/index.md, install-pdm.py, news/508.feature.md
=> Feature: Add an install script to bootstrap PDM quickly

news/441.feature.md, pdm.lock, pdm/models/environment.py, pdm/models/requirements.py, pdm/resolver/core.py
=> Extract name from egg-info when eligible

.pre-commit-config.yaml, news/261.misc.md, pdm/cli/commands/show.py, pdm/models/candidates.py, pdm/models/environment.py, pdm/models/repositories.py, pdm/resolver/core.py, pyproject.toml, setup.cfg
=> Clear the type errors from mypy

pdm/cli/commands/init.py
=> Fix minor cli spelling mistake

news/527.feature.md, pdm/cli/commands/show.py, pdm/cli/completions/pdm.bash, pdm/cli/completions/pdm.fish, pdm/cli/completions/pdm.ps1, pdm/cli/completions/pdm.zsh, pdm/models/project_info.py, tests/cli/test_cli.py
=> feat: support showing individual fields in pdm show

news/531.feature.md, pdm/cli/actions.py, pdm/cli/commands/list.py, pdm/cli/completions/pdm.bash, pdm/cli/completions/pdm.fish, pdm/cli/completions/pdm.ps1, pdm/cli/completions/pdm.zsh, pdm/models/pip_shims.py, tests/cli/test_actions.py, tests/conftest.py
- add the new option
- add test cases
- update completion scripts
=> feat: add freeze option to list command

news/541.dep.md, news/541.feature.md, pdm.lock, pdm/builders/base.py, pdm/builders/sdist.py, pdm/builders/wheel.py, pdm/cli/completions/pdm.ps1, pdm/cli/completions/pdm.zsh, pdm/cli/utils.py, pdm/formats/flit.py, pdm/formats/legacy.py, pdm/formats/pipfile.py, pdm/formats/poetry.py, pdm/formats/requirements.py, pyproject.toml
Seperate the build env into two different levels for better caching:
- `shared` that is unique for a given build requires
- `overlay` that is unique for a given build root
=> separate the build env into two levels

news/547.bugfix.md, pdm/models/requirements.py, pdm/project/core.py, tests/cli/test_add.py, tests/conftest.py
=> Fix the VCS url to be consistent between lock and install

news/551.bugfix.md, pdm/resolver/providers.py, tests/fixtures/pypi.json, tests/resolver/test_resolve.py
=> Bugfix: improve the logic of picking requirements

news/553.bugfix.md, pdm/cli/actions.py, pdm/models/in_process/__init__.py, pdm/models/python.py, pdm/project/core.py, tests/cli/test_actions.py, tests/test_project.py
=> Use the underlying real executable path for writing shebangs

pdm/models/candidates.py, tests/cli/test_cache.py, tests/conftest.py, tests/fixtures/artifacts/demo-0.0.1-cp36-cp36m-win_amd64.whl, tests/fixtures/index/demo.html, tests/fixtures/index/pep345-legacy.html, tests/models/test_candidates.py
=> Add more test cases

news/559.bugfix.md, pdm/models/markers.py, tests/models/test_marker.py
=> Fix extra extracting when combined with other markers

README.md
=> corrected parentheses in readme

CONTRIBUTING.md, news/573.doc.md
Added instructions for creating news fragments and improved overall readability and usage.
=> Add instructions for creating news fragments; usage and style improvements

news/570.bugfix.md, pdm/models/auth.py, pdm/models/environment.py, pdm/project/core.py, pdm/utils.py, tests/test_project.py, tests/test_utils.py
This is an attempt to fix #561 as well as the regression that the current solution to this bug caused. There are almost some issues with this pull request, but I wanted to take a shot at it anyway. Thanks for your work on PDM!
=> Expand env vars in source credentials early (#561)

news/586.refactor.md, pdm/exceptions.py, pdm/installers/installers.py, pdm/installers/synchronizers.py, pdm/installers/uninstallers.py, pdm/models/environment.py, pdm/models/pip_shims.py, pdm/utils.py, tests/test_installer.py
=> New uninstaller

docs/docs/pyproject/pep621.md, docs/docs/usage/advanced.md, docs/docs/usage/dependency.md, news/591.removal.md, pdm/cli/actions.py, pdm/cli/commands/add.py, pdm/cli/commands/export.py, pdm/cli/commands/import_cmd.py, pdm/cli/commands/install.py, pdm/cli/commands/remove.py, pdm/cli/commands/sync.py, pdm/cli/commands/update.py, pdm/cli/options.py, pdm/cli/utils.py, pdm/formats/requirements.py, pdm/installers/synchronizers.py, pdm/project/core.py, pdm/resolver/core.py, tests/cli/test_actions.py, tests/cli/test_add.py, tests/cli/test_sync.py, tests/resolver/test_resolve.py, tests/test_deprecation.py, tests/test_formats.py, tests/test_project.py, tests/test_utils.py
=> Deprecate -s/--section in favor of --group

news/592.refactor.md, pdm/_types.py, pdm/builders/base.py, pdm/cli/actions.py, pdm/cli/commands/plugin.py, pdm/cli/utils.py, pdm/installers/manager.py, pdm/installers/synchronizers.py, pdm/installers/uninstallers.py, pdm/models/environment.py, pdm/models/in_process/__init__.py, pdm/models/repositories.py, pdm/models/working_set.py, pdm/utils.py, tests/cli/test_actions.py, tests/cli/test_add.py, tests/conftest.py, tests/test_integration.py
=> Refactor: switch to importlib.metadata.Distribution

news/604.feature.md, pdm/cli/commands/cache.py, tests/cli/test_cache.py
=> Handle install cache clearing

pdm/cli/actions.py, pdm/cli/utils.py, pdm/installers/manager.py, pdm/installers/synchronizers.py, pdm/models/candidates.py, pdm/utils.py, tests/conftest.py
=> Fix the generation of direct_url.json

CHANGELOG.md, docs/docs/plugin.md, docs/docs/pyproject/tool-pdm.md, docs/docs/usage/project.md, pdm/builders/base.py, pdm/cli/commands/base.py, pdm/installers/manager.py, pdm/installers/synchronizers.py, pdm/installers/uninstallers.py, pdm/models/auth.py, pdm/models/environment.py, pdm/models/markers.py, pdm/models/pip_shims.py, pdm/project/config.py, pdm/resolver/providers.py, tests/conftest.py, tests/fixtures/projects/demo-parent-package/README.md
I ran [codespell](https://github.com/codespell-project/codespell/) to fix spelling typos!
Note that it touched to code itself! I can revert these changes if you prefer.
=> Fix spelling

docs/docs/index.md, docs/docs/pyproject/tool-pdm.md, news/635.feature.md, pdm/builders/base.py, pdm/cli/actions.py, pdm/cli/commands/build.py, pdm/cli/completions/pdm.bash, pdm/cli/completions/pdm.fish, pdm/cli/completions/pdm.ps1, pdm/cli/completions/pdm.zsh, tests/cli/test_build.py, tests/fixtures/projects/demo-failure/setup.py
=> Add --no-isolation option to build command

docs/docs/pyproject/pep621.md
- ~~[ ] A news fragment is added in `news/` describing what is new.~~
- ~~[ ] Test cases added for changed code.~~
Added documentation about multiline description (#646).
Feel free to reject the PR if you consider this paragraph not useful :slightly_smiling_face:
=> Add paragraph about multiline descriptions

news/657.bugfix.md, news/658.refactor.md, pdm/cli/actions.py, pdm/cli/commands/show.py, pdm/cli/utils.py, pdm/models/candidates.py, pdm/models/repositories.py, pdm/project/config.py, pdm/project/core.py, pdm/resolver/core.py, pdm/resolver/providers.py, pdm/resolver/python.py, tests/cli/test_add.py, tests/conftest.py, tests/resolver/test_resolve.py
=> requires-python now participates in the resolution

README.md, README_zh.md
Reading the readme required a variety of web searching to find out what each of the various PEPs related to, particularly PEP 582.  This PR links each of their mentions to the relevant URL to make it easier for a new reader.
Also features a minor typo fix (`relative` to `relatively`) on one line of the readme.
=> Update README to link to PEPs

news/669.bugfix.md, pdm/builders/base.py, tests/cli/test_build.py
=> Run pip with --isolated flag

news/721.bugfix.md, pdm/models/requirements.py, tests/models/test_requirements.py
=> Fix the URL of requirement when relative path is given

.github/workflows/ci.yml, docs/docs/usage/project.md, news/733.bugfix.md, news/733.feature.md, pdm/cli/commands/run.py, pdm/cli/completions/pdm.bash, pdm/cli/completions/pdm.fish, pdm/cli/completions/pdm.ps1, pdm/cli/completions/pdm.zsh, pdm/cli/utils.py, pdm/pep582/sitecustomize.py, pdm/utils.py, tests/cli/test_run.py
=> Add a new option `-s/--site-packages` to run command

news/feat-support-conda.md, pdm/models/candidates.py, pdm/project/core.py, pdm/utils.py, tests/conftest.py
This PR adds support for `CONDA_PREFIX` where virtual environments are implemented using Conda.
=> Feat: add support for Conda environments

news/533.bugfix.md, pdm/cli/actions.py, pdm/cli/utils.py, pdm/models/pip_shims.py, pdm/models/requirements.py, tests/cli/test_actions.py, tests/conftest.py
=> Switch to self-implemented `pdm list --freeze`

news/776.bugfix.md, pdm/cli/utils.py, pdm/resolver/providers.py
=> Resolve the top-level requirements first

pdm/cli/utils.py
=> Fix missing space in help message

news/781.bugfix.md, pdm/_types.py, pdm/core.py, pdm/resolver/providers.py
=> improve the resolution order

news/784.bugfix.md, pdm/pep582/sitecustomize.py, pdm/utils.py, tests/cli/test_run.py
=> Make sysconfig return PEP 582 scheme in pdm run

news/787.dep.md, pdm.lock, pdm/project/config.py, pyproject.toml
=> Remove version caps for most dependencies

news/796.bugfix.md, pdm/pep582/sitecustomize.py
=> Fix the patching of sysconfig in PEP 582 init

docs/docs/usage/dependency.md, news/790.feature.md, pdm/cli/utils.py, pdm/project/core.py, pdm/resolver/providers.py, pdm/utils.py, tests/resolver/test_resolve.py
=> Feature: Support resolution overriding

docs/docs/plugin/reference.md, docs/docs/plugin/write.md, docs/mkdocs.yml, news/798.feature.md, news/802.doc.md, pdm.lock, pdm/cli/actions.py, pdm/core.py, pdm/project/config.py, pdm/signals.py, pyproject.toml, tests/test_signals.py
=> Feature: Signals for init, install, lock

news/809.dep.md, pdm.lock, pdm/cli/actions.py, pdm/cli/commands/run.py, pdm/cli/utils.py, pdm/formats/base.py, pdm/project/config.py, pdm/project/core.py, pyproject.toml
=> Switch back to tomlkit

news/820.bugfix.md, news/820.feature.md, pdm/installers/installers.py, pdm/project/config.py
=> Improve the install cache with symlinks method

pdm/builders/base.py
=> Fix UnicodeDecodeError while c-extension compiling

pdm/cli/commands/config.py, pdm/cli/completions/pdm.fish, pdm/cli/completions/pdm.zsh
Just fixing a simple typo in doc/help.
=> fix(doc): typo: s/filie/file

news/842.feature.md, pdm/project/core.py, tests/test_project.py
=> Support setting Python path in global configuration

news/847.bugfix.md, news/850.bugfix.md, pdm/installers/uninstallers.py, tests/test_installer.py
=> Bugfix: Fix the unstable uninstallation error

news/846.feature.md, pdm/cli/actions.py, pdm/cli/commands/use.py, pdm/cli/completions/pdm.bash, pdm/cli/completions/pdm.fish, pdm/cli/completions/pdm.ps1, pdm/cli/completions/pdm.zsh, pdm/models/caches.py, setup.cfg, tests/cli/test_use.py, tests/conftest.py
=> Feature: Remember the last selection in "pdm use"

.github/workflows/ci.yml, pdm.lock, pyproject.toml
=> Add python 3.11 alpha in matrix

news/872.bugfix.md, pdm/cli/commands/config.py, pdm/project/config.py
=> Ignore uninstalled plugin configs

docs/docs/index.md
No new features so nothing added to new
Added a snippet for how to configure neovim lsp with pdm.
=> doc: Add neovim setup documenation

news/901.bugfix.md, pdm/cli/actions.py, pdm/models/candidates.py, pdm/models/repositories.py, pdm/models/requirements.py, pdm/resolver/providers.py, tests/resolver/test_resolve.py
=> Bugfix: Update the candidate identifier if the requirement has no name

docs/docs/usage/dependency.md, news/861.bugfix.md, pdm/resolver/providers.py
Related: https://github.com/pdm-project/pdm/issues/861#issuecomment-1035855350
=> Fix the URL support of resolution overrides

docs/docs/usage/dependency.md, news/909.feature.md, pdm/project/core.py, pdm/resolver/providers.py, tests/resolver/test_resolve.py
=> Support version ranges in overrides table

news/914.feature.md, pdm/cli/actions.py, pdm/cli/commands/config.py, pdm/installers/installers.py, pdm/installers/synchronizers.py, pdm/project/config.py, pdm/project/core.py, pyproject.toml, tests/cli/test_config.py, tests/cli/test_install.py, tests/cli/test_others.py, tests/conftest.py, tests/test_project.py
=> Rename config items to be more organized

news/883.feature.md, pdm/cli/completions/pdm.bash, pdm/cli/completions/pdm.fish, pdm/cli/completions/pdm.ps1, pdm/cli/completions/pdm.zsh, pdm/core.py, pdm/project/config.py, pdm/project/core.py, tests/cli/test_config.py, tests/conftest.py, tests/test_plugin.py
=> Support --config option

.github/workflows/ci.yml, news/924.bugfix.md, pdm/models/candidates.py, pdm/resolver/providers.py, tests/models/test_candidates.py
=> Fix a race condition in parallel installation

.github/workflows/ci.yml, pdm.lock
=> resolve the hang issue

docs/docs/pyproject/pep621.md, news/959.feature.md, pdm.lock, pdm/cli/actions.py, pdm/formats/flit.py, pdm/formats/legacy.py, pdm/formats/poetry.py, pdm/models/project_info.py, pyproject.toml, tests/fixtures/artifacts/pdm_pep517-0.10.1-py3-none-any.whl, tests/fixtures/artifacts/pdm_pep517-0.12.0-py3-none-any.whl, tests/fixtures/projects/demo-package/pyproject.toml, tests/fixtures/projects/poetry-demo/pyproject.toml, tests/models/test_candidates.py, tests/test_formats.py
=> Update license field name according to PEP 639

docs/docs/index.md
* Added a link to PyCharm official docs on how to mark a folder as Sources Root.
* [optional] Specified that after marking the source as root then one needs to set up the correct Python interpreter matching the same `<major.minor>` version.
=> [DOCS] Added a link to PDM-PyCharm setup

docs/docs/index.md
i added a note about using pylance/pyright.
the user may see a ton of errors or warnings after they configured `"python.analysis.diagnosticMode": "workspace"`.
pyright follows the "pyrightconfig.json", and it could solve this problem.
=> docs: Add notes about using Pylance/Pyright

README_zh.md
I change PDM logo's url  to the url provided by cdn in README_zh.
Most Chinese people can't access raw.githubusercontent.com, so I use cdn in the README_zh to make the image accessible properly.
Also, raw.githubusercontents.com is a free cdn for raw.githubusercontent.com, please feel free to use it.
=> PDM logo use cdn

docs/docs/index.md
Add notes about using jupyter in vscode according to #848
=> docs: Add notes about using jupyter in vsc

news/993.bugfix.md, pdm/cli/commands/config.py, pdm/cli/commands/search.py, pdm/models/environment.py, pdm/project/config.py, tests/cli/test_others.py
=> Don't create project files in `pdm search` command

news/991.bugfix.md, pdm/models/project_info.py
This PR is submitted to fix #991.
=> default optional `license` field to str(None) to fix #991

news/1002.dep.md, pdm.lock, pdm/installers/installers.py, pyproject.toml
=> Upgrade to support installer 0.5.0

news/1011.feature.md, pdm/cli/actions.py, pdm/installers/synchronizers.py, pdm/models/candidates.py, pdm/resolver/providers.py, tests/cli/test_add.py, tests/fixtures/projects/demo-combined-extras/pyproject.toml, tests/fixtures/projects/demo-module/pyproject.toml, tests/fixtures/projects/demo-package-has-dep-with-extras/pyproject.toml, tests/fixtures/projects/demo-package/pyproject.toml, tests/fixtures/projects/demo-src-package/pyproject.toml
=> Don't override editable installation

docs/docs/index.md, news/1004.doc.md
- [ x] A news fragment is added in `news/` describing what is new.
Document how to install PDM inside a project with Pyprojectx.
=> Install docs

docs/docs/index.md
Add notes about using Jupyter Notebook in VSCode, as discussed in #848
=> docs: Add notes about using jupyter in VSCode #848

news/1019.feature.md, pdm/cli/actions.py, pdm/cli/utils.py, pdm/models/repositories.py, pdm/models/specifiers.py, pyproject.toml, setup.cfg, tests/cli/test_others.py
=> Recalculate file hashes in `pdm lock --refresh`

news/1041.feature.md, pdm/cli/actions.py, pdm/cli/commands/init.py, tests/cli/test_others.py
=> Ask for description and create default README for libraries

news/1039.bugfix.md, pdm/cli/actions.py, pdm/models/python.py, pdm/project/core.py
=> Another approach for fixing errors that pdm use corrupted python

pdm/cli/actions.py, pdm/models/python.py, pdm/project/core.py
=> Filter out invalid pythons

news/1050.bugfix.md, pdm/cli/actions.py, pdm/project/core.py, tests/cli/test_add.py
=> Replace the editable entry in pyproject.toml

README_zh.md
I fix the typo `坠吼` in the `README_zh.md` description for `pip install pdm` and changed it to `最好`.
Otherwise, there may be problems with unclear language.
=> docs: 📝 Fix typo in `pip install pdm` description

news/1073.bugfix.md, news/1075.bugfix.md, pdm/cli/commands/base.py, pdm/models/requirements.py
=> Bugfix: Unquote path in req url

news/1079.bugfix.md, pdm/formats/requirements.py, tests/test_formats.py
=> Replace PROJECT_ROOT in export result

news/1082.removal.md, pdm/__version__.py, pdm/core.py, pdm/project/core.py, pdm/utils.py, tests/test_utils.py
=> Deprecate usage of Python 2.7 interpreter

news/1097.bugfix.md, pdm/cli/utils.py, pdm/models/requirements.py
=> Fix a bug of dependency graph missing deps

news/1106.bugfix.md, pdm/models/in_process/sysconfig_get_paths.py, pdm/utils.py
=> Prefer `venv` scheme if available

news/1084.misc.md, news/1097.bugfix.md, news/1099.bugfix.1.md, news/1099.bugfix.2.md, news/1101.bugfix.md, news/1103.bugfix.md, news/1104.bugfix.md, news/1106.bugfix.md, pdm/builders/base.py, pdm/models/repositories.py
=> Fix a version conflict issue in build env.

.github/workflows/doc.yml, .github/workflows/release.yml, README.md, README_zh.md, docs/docs/index.md, docs/mkdocs.yml, news/1126.doc.md, pdm.lock, pdm/cli/utils.py, pyproject.toml
=> Docs: multiple versions

news/1119.bugfix.md, pdm/resolver/providers.py
=> Fix a careless bug in the resolution preference

news/1153.dep.md, pdm.lock, pdm/builders/base.py, pdm/cli/actions.py, pdm/models/setup.py, pdm/project/core.py, pdm/project/metadata.py, pyproject.toml, tasks/release.py, tests/fixtures/projects/poetry-demo/pyproject.toml
=> feat: Update pdm-pep517 to 1.0

news/1166.bugfix.md, pdm/project/core.py, pdm/resolver/providers.py, tests/cli/test_update.py
=> fix: a bug that dep with extras can't be updated

docs/docs/usage/project.md
I spotted these while reviewing the code. 🍎
=> Fix a couple documentation typos

news/1184.bugfix.md, pdm/termui.py
=> fix: use normal streamhandler for logging

news/1180.bugfix.md, pdm/cli/actions.py, pdm/project/config.py, pdm/resolver/reporters.py, tests/cli/test_config.py
I fix reading the environment variable for `PDM_RESOLVE_MAX_ROUNDS`, and I fix a few other small typos found using a spell checker.
Fixes #1180
=> Fix reading `PDM_RESOLVE_MAX_ROUNDS`

.github/workflows/ci.yml, news/1178.bugfix.md, pdm.lock, pyproject.toml
=> chore: Update unearth version to 0.4.1

news/1173.bugfix.md, pdm/models/repositories.py, tests/resolver/test_resolve.py
Fix #1173
@Hnasar would you like to test this branch to see if the issue is gone?
=> fix: fix resolve requirements with extras

docs/docs/usage/dependency.md, docs/docs/usage/project.md, news/1191.feature.md, news/398.feature.md, pdm/cli/actions.py, pdm/cli/commands/sync.py, pdm/cli/completions/pdm.bash, pdm/cli/completions/pdm.fish, pdm/cli/completions/pdm.ps1, pdm/cli/completions/pdm.zsh, pdm/cli/options.py, pdm/installers/synchronizers.py, tests/cli/test_install.py
=> feat: add `--no-keep` option to sync command

news/1196.bugfix.md, pdm/models/environment.py, pdm/utils.py
=> fix: check if the host pip is compatible with the project python

docs/docs/usage/project.md, news/1200.feature.md, pdm/cli/commands/config.py, pdm/project/config.py
=> feat: site-wide configuration

.pre-commit-config.yaml, CHANGELOG.md, docs/docs/usage/hooks.md, docs/docs/usage/project.md, pdm/cli/commands/init.py, pdm/cli/commands/run.py, pdm/cli/commands/venv/purge.py, pdm/cli/hooks.py, pdm/cli/options.py, pdm/installers/synchronizers.py, pdm/signals.py, pdm/termui.py, setup.cfg
[`codespell --ignore-words-list=ba,overriden,te`](https://pypi.org/project/codespell)
=> Fix typos discovered by codespell

pdm/cli/actions.py, pdm/models/caches.py, setup.cfg, tests/cli/test_use.py
* https://portingguide.readthedocs.io/en/latest/dicts.html#removed-dict-has-key
* [https://docs.python.org/3/reference/datamodel.html#object.__contains__](https://docs.python.org/3/reference/datamodel.html#object.__contains__)
=> JSONFileCache: Replace .has_key() with __contains__()

pdm/cli/commands/cache.py, pdm/cli/utils.py, pdm/core.py, pdm/exceptions.py, pdm/formats/base.py, pdm/installers/uninstallers.py, pdm/models/in_process/get_abi_tag.py, pdm/models/markers.py, pdm/models/python.py, pdm/models/requirements.py, pdm/models/specifiers.py, pdm/pep582/sitecustomize.py, pdm/project/config.py, pdm/project/core.py, pdm/project/metadata.py, pdm/resolver/reporters.py, pdm/termui.py, pdm/utils.py, tests/cli/test_install.py, tests/conftest.py, tests/fixtures/projects/test-setuptools/setup.py, tests/models/test_requirements.py
[`pyupgrade --py37-plus **/*.py`](https://pypi.org/project/pyupgrade)
=> pyupgrade --py37-plus

news/1211.bugfix.md, pdm/cli/commands/run.py
=> fix: fix run env overriding pep582

pdm/cli/completions/pdm.fish, pdm/cli/completions/pdm.zsh, pdm/cli/options.py
=> doc: pdm.toml -> .pdm.toml

news/1216.pwsh-support.md, pdm/cli/commands/completion.py
Support generating shell completion for [`pwsh`](https://github.com/PowerShell/PowerShell) (#1216)
=> feat(completion): support pwsh (PowerShell Core)

.github/workflows/ci.yml, news/1221.bugfix.md, pdm/cli/actions.py, tests/cli/test_remove.py
=> fix: removing package shouldn't break TOML

docs/docs/usage/project.md
=> docs/usage/project.md: five different of caches

news/1230.bugfix.md, pdm/cli/commands/venv/activate.py, pdm/cli/commands/venv/backends.py, tests/cli/test_venv.py
=> fix: don't save python path for venv commands

docs/docs/usage/dependency.md, news/1235.feature, news/1235.feature.md, news/1241.feature.md, pdm/models/candidates.py, pdm/models/repositories.py, tests/cli/test_install.py
=> feat: reference other groups in optional dependencies

.github/workflows/ci.yml, pdm/project/core.py, tests/cli/test_venv.py, tests/conftest.py, tests/test_integration.py
=> chore: detect available python versions for integration

news/1253.bugfix.md, pdm/project/core.py
I apologise for not adding a test case yet. I have very little time at the moment, so I thought I'd just submit this PR in the hope that it might be useful. In future I'll look to adding tests etc.
Support Conda environment detection
Fixes #1253
=> Fix: support conda in environment detection

docs/docs/usage/advanced.md
=> Upgrade GitHub Action

.github/workflows/ci.yml, news/1261.dep.md, pdm.lock, pdm/models/repositories.py, pyproject.toml
=> fix: pin the pip version

news/1268.dep.md, pdm.lock, pdm/cli/commands/plugin.py, pyproject.toml, tests/cli/test_plugin.py
=> feat: Remove dependency of pip

news/1273.bugfix.md, pdm/cli/actions.py, pdm/models/environment.py, pdm/models/repositories.py, pdm/models/versions.py, pdm/project/core.py
=> fix: Try to read the lock file even if the version is incompatible

news/1282.removal.md, pdm/__init__.py, pdm/cli/commands/venv/__init__.py, pdm/cli/commands/venv/backends.py, pdm/cli/commands/venv/create.py, pdm/cli/commands/venv/purge.py, pdm/cli/commands/venv/remove.py
=> feat: Deprecate top-level imports

news/1302.bugfix.md, pdm/models/candidates.py
=> fix: prefer compatible packages

tests/cli/test_build.py, tests/conftest.py, tests/test_project.py
=> fix: remove dependance on network for several tests

README.md, README_zh.md
Fix https://github.com/pdm-project/pdm/issues/1304
=> Update asdf instructions and add to zh version

news/1307.bugfix.md, pdm/cli/actions.py, pdm/cli/utils.py, pdm/models/candidates.py, pdm/resolver/core.py, pdm/resolver/providers.py
=> fix: store dependencies by name and version

docs/docs/usage/dependency.md
--lockfilie should be --lockfile
=> Fixed minor typo

news/1320.bugfix.md, src/pdm/cli/actions.py, src/pdm/cli/hooks.py
=> feat: Delay the trigger of post_lock in add and update command

news/1325.bugfix.md, src/pdm/models/repositories.py
=> fix: bug of missing hashes

news/1337.bugfix.md, src/pdm/models/candidates.py
=> fix: warning about failure to parse project files

news/1334.bugfix.md, src/pdm/models/candidates.py, tests/fixtures/index/wheel.html, tests/models/test_candidates.py
=> fix: Ignore invalid values of `data-requires-python`

news/1329.md, src/pdm/cli/actions.py
- [x ] A news fragment is added in `news/` describing what is new.
Found all instances of `{group}` in  `do_add()` and `do_remove()` (located in `src/pdm/cli/actions.py`) and replaced them with `[bold cyan]{group}[/]`.
=> style(cli): enhance group formatting in messages (fixes #1329)

docs/docs/usage/dependency.md
- [N/A] A news fragment is added in `news/` describing what is new.
- [N/A] Test cases added for changed code.
=> doc: #1357 Add missing editable install dependency group criteria

docs/docs/usage/project.md, news/1364.doc.md
~- [x] Test cases added for changed code.~
Added a section under project in the documentation on how to correctly use a version control system like git with a PDM based project. This resolves issue #1364 
_Sorry first time committing to with open source so sorry if there are any mistakes._
=> doc: Add working with version control section

README_zh.md
fix typo in zh-CN README, i.e., `__papackage__` to `__pypackage__`
=> doc: fix zh-CN README typo

docs/docs/usage/project.md, news/1392.feature.md, src/pdm/cli/commands/publish/__init__.py, src/pdm/cli/commands/publish/repository.py, src/pdm/project/config.py, tests/cli/test_publish.py
=> feat: Introduce `ca_certs` / `--ca-certs` to `pdm publish` repos

news/1401.bugfix.md, src/pdm/models/repositories.py, src/pdm/models/requirements.py, tests/cli/test_add.py
=> fix: Fix a crash issue when depending on editable packages with extras

src/pdm/cli/actions.py, src/pdm/cli/commands/self_cmd.py, tests/cli/test_self_command.py
=> fix: update version checker to show self update command

news/1410.bugfix.md, pdm.lock, pyproject.toml, src/pdm/cli/actions.py, src/pdm/cli/commands/init.py, tests/cli/test_init.py, tests/test_integration.py
Fixing https://github.com/pdm-project/pdm/issues/1407#issuecomment-1262206732
=> fix: do not save python path under non-interactive mode

news/1412.feature.md, news/1418.bugfix.md, src/pdm/cli/actions.py, src/pdm/cli/commands/init.py, tests/cli/test_init.py
- Resolve #1412
- Resolve #1418
=> feat: allow pdm init to receive a python version

news/1426.feature.md, src/pdm/cli/actions.py
=> feat: add a default requires-python on import

src/pdm/cli/utils.py
=> Remove extra '/'

CONTRIBUTING.md
=> doc: fix a broken link in CONTRIBUTING.md

README.md, README_zh.md, docs/docs/index.md, install-pdm.py
=> feat: write useful informations for github action

docs/docs/usage/configuration.md, news/1463.feature.md, src/pdm/cli/commands/venv/backends.py, src/pdm/cli/commands/venv/create.py, src/pdm/project/config.py, tests/cli/test_venv.py, tests/test_project.py
=> feat: option to ship pip when creating a venv

news/1467.bugfix.md, pdm.lock, pyproject.toml, src/pdm/compat.py, src/pdm/core.py, tests/test_plugin.py
=> fix: use pypi importlib_metadata on python < 3.10

news/1484.bugfix.md, src/pdm/models/markers.py, tests/models/test_marker.py
=> fix: python_version comparison in environment markers

.github/workflows/ci.yml
=> chore: change the python version to download

docs/docs/usage/dependency.md, news/1503.feature.md, src/pdm/builders/base.py, src/pdm/project/core.py, src/pdm/project/project_file.py, tests/resolver/test_resolve.py
=> feat: rename the resolution.overrides table

docs/docs/usage/configuration.md
=> fix venv.with_pip syntax error

news/1546.bugfix.md, src/pdm/models/backends.py
=> fix: fallback to pdm.pep517 for unknown custom build backend

news/1010.bugfix.md, news/1550.dep.md, pdm.lock, pyproject.toml
=> feat: update installer to 0.6.0

news/1555.dep.md, pdm.lock, pyproject.toml, src/pdm/models/specifiers.py, tests/__init__.py, tests/models/test_specifiers.py, tests/resolver/test_resolve.py
=> chore: update deps unearth and packaging

news/1569.bugfix.md, src/pdm/models/repositories.py
=> fix: matching problem of packages in lockfile

pyproject.toml, setup.cfg
=> chore: ignore coverage warnings

src/pdm/project/core.py
- [n/a] A news fragment is added in `news/` describing what is new.
- [n/a] Test cases added for changed code.
Correct grammar "reuse it" -> "reusing it" because it looked like it was an instruction for the user.
Fix a small typo.
=> Fix small wording issues

news/1602.bugfix.md, src/pdm/cli/commands/self_cmd.py
=> fix: fix an uninstallation error on Windows

news/1619.bugfix.md, src/pdm/models/requirements.py, src/pdm/utils.py, tests/__init__.py, tests/models/test_requirements.py, tests/models/test_specifiers.py
=> fix: fix the wildcards in requirement specifiers

docs/docs/usage/venv.md
Fixed misplaced backtick (`pdm config python.use_venv` false -> `pdm config python.use_venv false`)
=> docs: fixed misplaced backtick

src/pdm/models/requirements.py, src/pdm/resolver/providers.py
=> fix: correct the hash key for requirements

.github/PULL_REQUEST_TEMPLATE.md, news/1651.bugfix.md, src/pdm/models/auth.py, src/pdm/project/config.py, src/pdm/project/core.py
Raised by https://github.com/pdm-project/pdm/pull/1597#issuecomment-1407403488
=> fix: load pypi sources from project config

news/1666.feature.md, src/pdm/cli/commands/venv/backends.py, src/pdm/cli/commands/venv/create.py, tests/cli/test_venv.py
=> fix: allow force re-creating venv in project

news/1672.feature.md, src/pdm/cli/commands/init.py, tests/cli/test_init.py
=> feat: accept --ignore-remembered in pdm init

news/1674.bugfix.md, src/pdm/formats/requirements.py, tests/test_formats.py
=> fix: import editable requirements into dev dependencies

docs/docs/usage/venv.md, news/1680.feature.md, src/pdm/cli/commands/venv/__init__.py, tests/cli/test_venv.py
=> feat(venv): add option to show the path to a venv

docs/docs/dev/changelog.md, docs/docs/dev/contributing.md, docs/mkdocs.yml, pdm.lock, pyproject.toml, src/pdm/cli/actions.py
=> doc: add redirects map for moved pages

docs/docs/usage/dependency.md, news/1614.feature.md, src/pdm/cli/actions.py, src/pdm/cli/commands/add.py, src/pdm/cli/commands/install.py, src/pdm/cli/commands/remove.py, src/pdm/cli/commands/sync.py, src/pdm/cli/commands/update.py, src/pdm/cli/options.py, src/pdm/installers/synchronizers.py, tests/cli/test_add.py, tests/cli/test_install.py, tests/cli/test_remove.py
=> feat(install): fail-fast

news/1692.feature.md, pdm.lock, src/pdm/project/core.py, src/pdm/project/lockfile.py
=> feat: write groups to the metadata section of lockfile

news/1535.bugfix.md, src/pdm/models/candidates.py, src/pdm/models/environment.py
=> fix: prefer built distributions

news/1702.bugfix.md, src/pdm/models/repositories.py, src/pdm/models/requirements.py, src/pdm/resolver/providers.py, tests/cli/test_install.py, tests/conftest.py, tests/fixtures/projects/test-monorepo/README.md, tests/fixtures/projects/test-monorepo/core/pyproject.toml, tests/fixtures/projects/test-monorepo/package_a/pyproject.toml, tests/fixtures/projects/test-monorepo/package_b/pyproject.toml, tests/fixtures/projects/test-monorepo/pyproject.toml
=> fix: resolution failure with nested relative path deps

CONTRIBUTING.md
Discussion in https://github.com/pdm-project/pdm/discussions/1711
=> docs: Improve contributing docs

docs/docs/usage/advanced.md
I accidentally added this in #1475 and only noticed it now :^)
=> fix wrong file name for pdm.lock

docs/docs/index.md, news/1725.misc.md
I made [asdf-vm](https://asdf-vm.com/) plugin -> https://github.com/1oglop1/asdf-pdm/ it would be nice to mention it in docs.
=> docs: install via asdf-vm

news/1740.bugfix.md, src/pdm/cli/commands/show.py, src/pdm/models/project_info.py
=> fix: fix a bug of show command not showing metadata of current project

news/1743.feature.md, src/pdm/cli/commands/fix/__init__.py, src/pdm/cli/commands/fix/fixers.py, src/pdm/cli/completions/pdm.bash, src/pdm/cli/completions/pdm.fish, src/pdm/cli/completions/pdm.ps1, src/pdm/cli/completions/pdm.zsh, src/pdm/cli/options.py, src/pdm/core.py, src/pdm/project/core.py, tests/cli/test_fix.py, tests/cli/test_run.py, tests/test_plugin.py
=> feat: add pdm fix and hint when invoking pdm commands

news/1653.feature.md, pdm.lock, pyproject.toml, src/pdm/models/auth.py
=> feat: upgrade unearth to 0.8 to enable calling keyring from CLI

CHANGELOG.md
=> Fix markup in CHANGELOG.md

docs/docs/usage/venv.md, news/1782.feature.md, src/pdm/project/core.py
=> feat: ignore active venv

docs/docs/usage/hooks.md, news/1792.feature.md, src/pdm/cli/commands/base.py, src/pdm/cli/commands/fix/__init__.py, src/pdm/core.py, src/pdm/signals.py
=> feat: signal to emit before any command is invoked

news/1509.feature.md, pdm.lock, pyproject.toml, src/pdm/cli/commands/publish/repository.py, src/pdm/environments/base.py, src/pdm/models/candidates.py, src/pdm/models/repositories.py, src/pdm/utils.py
=> feat: lazily evaluate sources when respect-source-order is true

news/1836.bugfix.md, news/1836.doc.md, pdm.lock, src/pdm/cli/actions.py, tests/cli/test_update.py
=> fix: wrong argument validation for update command

README.md, README_zh.md, docs/docs/index.md, docs/docs/reference/build.md, docs/docs/reference/cli.md, docs/docs/reference/configuration.md, docs/docs/usage/advanced.md, docs/docs/usage/config.md, docs/docs/usage/dependency.md, docs/docs/usage/hooks.md, docs/docs/usage/pep582.md, docs/docs/usage/project.md, docs/docs/usage/venv.md, news/1840.doc.md, pdm.lock
=> doc(#1840): Remove advertizing of PEP-582 from Feature highlights

docs/docs/usage/venv.md
Hi,
Thanks for the great project. I have a small pull request for the documentation
fixed link in documentation, that was causing a 404
=> Update docs venv.md

news/1851.bugfix.md, src/pdm/resolver/providers.py
=> fix: The resolver doesn't take into account of the requirements from both bare package and package[extra]

news/1856.bugfix.md, src/pdm/cli/commands/config.py, src/pdm/exceptions.py, src/pdm/project/config.py
=> fix: Default pypi source gets password <hidden>

docs/docs/usage/scripts.md
Fix typo in `docs/docs/usage/scripts.md`, as mentioned in issue [1870](https://github.com/pdm-project/pdm/issues/1870).
=> Fix typo in docs/docs/usage/scripts.md

news/1886.bugfix.md, pdm.lock, pyproject.toml
=> fix: pin urllib3 to avoid incompatibility with cachecontrol

news/1868.feature.md, src/pdm/cli/commands/publish/repository.py
=> feat: PyPI Trusted Publisher Support

news/1894.bugfix.md, news/1901.bugfix.md, src/pdm/cli/actions.py, src/pdm/cli/commands/install.py, src/pdm/installers/core.py, src/pdm/installers/synchronizers.py
=> fix: the self package isn't uninstallable

pdm.lock, pyproject.toml, src/pdm/_types.py, src/pdm/cli/commands/config.py, src/pdm/cli/commands/publish/__init__.py, src/pdm/cli/commands/run.py, src/pdm/cli/options.py, src/pdm/compat.py, src/pdm/environments/base.py, src/pdm/formats/__init__.py, src/pdm/models/auth.py, src/pdm/models/versions.py, src/pdm/project/config.py, src/pdm/project/core.py, src/pdm/pytest.py, src/pdm/termui.py, tests/cli/test_config.py, tests/models/test_candidates.py
=> refactor: reduce repeating code in config and clean the types

news/1919.feature.md, src/pdm/models/caches.py, src/pdm/models/candidates.py, src/pdm/utils.py
=> feat: Add support for reading metadata from PyPI directly

news/1944.feature.md, src/pdm/core.py
=> feat: add local plugin scripts to PATH env

news/1945.bugfix.md, src/pdm/project/config.py
=> fix: convert to boolean when setting verify_ssl for custom indexes

news/1948.bugfix.md, src/pdm/cli/actions.py, src/pdm/cli/utils.py, tests/test_utils.py
=> fix: `pdm import` clobbers `build-system.requires` value in `pyproject.toml`

docs/docs/usage/config.md, news/1923.feature.md, src/pdm/core.py, tests/test_project.py
=> feat: An option to specify constant command arguments via pyproject.toml

news/1961.bugfix.md, pdm.lock, src/pdm/project/config.py, src/pdm/project/core.py, tests/cli/test_add.py, tests/test_project.py
=> fix: PDM ignores PDM_PYPI_USERNAME and PDM_PYPI_PASSWORD when there are no defaults in config

news/1972.feature.md, src/pdm/cli/actions.py
=> fix: add python prefix to the self update command on Windows

src/pdm/formats/poetry.py, tests/fixtures/pyproject.toml
=> Fix path while import poetry deps (#1968)

docs/docs/usage/config.md
refs
- https://github.com/pdm-project/pdm/blob/77190c47d5a6ba56996de45518afdccc87ae7005/src/pdm/project/config.py#L227
- https://github.com/platformdirs/platformdirs/blob/1ac7baad22509157518efc7ef2d8119080a01932/src/platformdirs/macos.py#L8
=> docs: fix configuration details for macOS

news/1977.bugfix.md, src/pdm/project/config.py, src/pdm/project/core.py
=> fix: reading config from env vars correctly

news/1984.bugfix.md, src/pdm/cli/commands/init.py, src/pdm/cli/commands/venv/backends.py
=> fix: `pdm init` in non-interactive mode does not respect `--python` option

news/1981.bugfix.md, src/pdm/models/session.py
=> fix: no crash when reading the old cache

install-pdm.py
=> fix: install-pdm.py looking in wrong place for `yanked` flag

news/2006.bugfix.md, src/pdm/models/requirements.py
=> fix: ExtrasWarning: Extras not found for jax: [cuda12_pip]

news/2007.bugfix.md, src/pdm/cli/commands/base.py
=> fix: deprecation warning when passing parser to Command.__init__

news/2013.bugfix.md, src/pdm/cli/actions.py
=> fix: Breaking change: module 'pdm.cli.actions' has no attribute 'do_use'

news/2018.bugfix.md, src/pdm/cli/commands/self_cmd.py
=> Duplicate libraries in `pdm self list`

README.md, README_zh.md, docs/docs/index.md, docs/docs/install-pdm.py, docs/docs/install-pdm.py.sha256, news/2026.feature.md
=> fix: create `.sha256` file for verfication and serve on the docs

news/2012.feature.md, src/pdm/models/candidates.py, src/pdm/utils.py, tests/test_utils.py
=> Refactor deprecated `warn` method and use appropriate warnings class

src/pdm/cli/commands/config.py, src/pdm/cli/completions/pdm.bash, src/pdm/cli/completions/pdm.fish, src/pdm/cli/completions/pdm.ps1, src/pdm/cli/completions/pdm.zsh
=> feat: new --edit option to edit config file in editor

news/2038.bugfix.md, src/pdm/resolver/providers.py
=> fix: Yanked version might cause a conflict

news/2045.bugfix.md, src/pdm/environments/local.py
Fixes #2045
Supersedes #2046 
cc @pawamoy
=> fix: PDM corrupts binary executable (ruff)

docs/docs/usage/config.md, news/2049.feature.md, src/pdm/models/session.py
=> feat: Add support for truststore package

news/2056.bugfix.md, src/pdm/cli/commands/remove.py, src/pdm/project/core.py, tests/cli/test_add.py, tests/cli/test_build.py
=> fix: correctly update dependencies for out-of-order table

.github/workflows/ci.yml, news/2078.feature.md, src/pdm/environments/base.py, src/pdm/models/in_process/__init__.py, src/pdm/models/session.py
=> feat: Support environment for other architecture

pyproject.toml
=> chore(ruff): use isort and extend-select

news/2105.bugfix.md, src/pdm/installers/installers.py
=> fix: Shared cache cannot support overlapping directory structures

news/2113.dep.md, news/2113.feature.md, pdm.lock, pyproject.toml, src/pdm/models/repositories.py
=> feat: ignore wheels for pythons not in range

news/2130.bugfix.md, src/pdm/project/core.py
=> fix: ignore empty source when merging sources

news/2133.bugfix.md, src/pdm/models/requirements.py
=> fix: invalid requirement converted from poetry metadata

.pre-commit-config.yaml, src/pdm/environments/local.py
=> chore: Pre commit ci update config

docs/docs/reference/build.md, docs/docs/reference/pep621.md, docs/docs/usage/project.md, news/2167.removal.md, src/pdm/cli/completions/pdm.ps1, src/pdm/cli/completions/pdm.zsh, src/pdm/models/backends.py, tests/cli/test_build.py, tests/cli/test_publish.py, tests/cli/test_template.py, tests/fixtures/projects/demo-combined-extras/pyproject.toml, tests/fixtures/projects/demo-module/pyproject.toml, tests/fixtures/projects/demo-package-has-dep-with-extras/pyproject.toml, tests/fixtures/projects/demo-package/pyproject.toml, tests/fixtures/projects/demo-parent-package/package-b/pyproject.toml, tests/fixtures/projects/demo-src-package/pyproject.toml, tests/fixtures/projects/test-monorepo/core/pyproject.toml, tests/fixtures/projects/test-monorepo/package_a/pyproject.toml, tests/fixtures/projects/test-monorepo/package_b/pyproject.toml, tests/fixtures/projects/test-monorepo/pyproject.toml, tests/fixtures/projects/test-plugin-pdm/pyproject.toml, tests/models/test_backends.py, tests/models/test_candidates.py
=> feat: remove legacy pdm-pep517 backend

news/2203.bugfix.md, src/pdm/formats/__init__.py, src/pdm/formats/base.py, src/pdm/models/candidates.py, src/pdm/models/setup.py, tests/fixtures/poetry-error.toml, tests/test_formats.py, tests/test_project.py
=> fix: Handle parsing errors when converting from poetry-style metadata

news/2221.bugfix.md, src/pdm/cli/commands/run.py, tests/cli/test_run.py
=> fix: `pdm run` conflicts between local file and PATH

news/2240.bugfix.md, src/pdm/cli/utils.py
=> fix: lock relocatable dependency URLs in the lockfile

pyproject.toml, tox.ini
fixes https://github.com/pdm-project/pdm/issues/2247
=> add tox.ini in sdist

news/2071.doc.md, src/pdm/cli/options.py
- ~[ ] Test cases added for changed code.~
Fixes #2071.
=> doc: clarify --no-isolation option

docs/docs/usage/advanced.md
Bumped version of `setup-pdm` from `v2` to `v3`.
=> docs: update github actions version

docs/docs/usage/dependency.md
=> doc: add note about installing into global python

news/2301.py312.md, pdm.lock, pyproject.toml, tox.ini
Support Python 3.12
close #2300
=> porting to python3.12

docs/docs/usage/dependency.md
=> Typo in docs/dependency.md

news/2285.bugfix.md, src/pdm/cli/commands/update.py, src/pdm/formats/poetry.py, tests/fixtures/poetry-new.toml, tests/test_formats.py
=> fix: Dependency Groups from Poetry do not migrate properly to PDM

docs/docs/usage/project.md, docs/docs/usage/scripts.md, docs/docs/usage/template.md, docs/docs/usage/venv.md
just 2 spelling fixes and 2 english improvements .
=> improve spelling

news/2314.bugfix.md, src/pdm/builders/base.py
=> fix: Install build requirements into wrong location when running with --venv

src/pdm/cli/commands/venv/activate.py
Make it less confusing for new users.
Related issue: #2266
=> doc: clarify the effect of `pdm venv activate`

news/2355.bugfix.md, src/pdm/installers/installers.py
=> fix: Installation failed when install.cache = true

docs/docs/assets/extra.css, docs/mkdocs.yml, docs/overrides/main.html, news/2365.doc.md
=> feat: add a chatbot in the doc page

news/2164.feature.md, src/pdm/cli/actions.py, src/pdm/project/core.py, src/pdm/project/lockfile.py, tests/cli/test_install.py, tests/cli/test_lock.py
=> feat: improve the compatibility checking for lockfile

news/2362.feature.md, src/pdm/cli/commands/publish/__init__.py, src/pdm/cli/commands/publish/repository.py, src/pdm/cli/completions/pdm.bash, src/pdm/cli/completions/pdm.fish, src/pdm/cli/completions/pdm.ps1, src/pdm/cli/completions/pdm.zsh, tests/cli/conftest.py
=> feat: Publish: add argument `--skip-existing` to avoid overwrite

src/pdm/cli/actions.py, src/pdm/cli/commands/add.py, src/pdm/cli/commands/config.py, src/pdm/cli/commands/export.py, src/pdm/cli/commands/fix/__init__.py, src/pdm/cli/commands/init.py, src/pdm/cli/commands/list.py, src/pdm/cli/commands/publish/__init__.py, src/pdm/cli/commands/remove.py, src/pdm/cli/commands/run.py, src/pdm/cli/commands/show.py, src/pdm/cli/commands/use.py, src/pdm/cli/commands/venv/activate.py, src/pdm/cli/commands/venv/purge.py, src/pdm/cli/utils.py, src/pdm/core.py, src/pdm/formats/flit.py, src/pdm/models/auth.py, src/pdm/models/repositories.py, src/pdm/project/config.py, src/pdm/project/core.py, src/pdm/resolver/core.py, src/pdm/termui.py, tests/cli/test_config.py
=> feat: Change the style of logging status to console

news/2358.bugfix.md, src/pdm/models/repositories.py
=> fix: improve the error message to tell user how to fix it

docs/docs/usage/project.md
Fix python version list in doc.
=> fix: python version in doc

.pre-commit-hooks.yaml, docs/docs/usage/advanced.md, news/2474.feature.md
Add "pdm-sync" as a pre-commit hook. Fixes #2474
=> Add "pdm-sync" pre-commit hook

news/2483.bugfix.md, src/pdm/cli/utils.py
=> fix: `pdm update --dry-run --unconstrained` raises KeyError

news/2497.feature.1.md, news/2497.feature.2.md, src/pdm/cli/commands/export.py, src/pdm/cli/completions/pdm.bash, src/pdm/cli/completions/pdm.fish, src/pdm/cli/completions/pdm.ps1, src/pdm/cli/completions/pdm.zsh, tests/cli/test_install.py, tests/cli/test_others.py
=> feat: add --no-markers to `export` command

docs/docs/usage/venv.md
Added `pdm shell` function documentation for `fish shell` #2499
Fish is also one of the popular shells, so why leave it out?
=> feat: added documentation for enabling 'pdm shell' for fish shell

.github/ISSUE_TEMPLATE/feature_request.md
Change the issue template name from "feature request" to "feature / enhancement request", since some enhancements aren't new features.
=> feature_request.md: Change the template name to "Feature / Enhancement Request"

docs/docs/usage/advanced.md
Describe how `keyring` can be added to `pdm-sync` pre-commit hook.
=> DOCS: Describe keyring support for pdm-sync pre-commit hook

docs/docs/reference/build.md, news/2510.docs.md
Finally had the time to do this, in between all of the holidays 😃 
Addresses #2510
=> docs: add maturin section

news/2488.bugfix.md, news/2495.bugfix.md, news/2502.bugfix.md, news/2507.bugfix.md, news/2510.doc.md, news/2542.bugfix.md, src/pdm/cli/commands/run.py, src/pdm/utils.py, tests/cli/test_run.py
=> fix: Environment variable substitution in `cmd` scripts

news/2547.feature.md, news/2547.removal.md, src/pdm/cli/actions.py, src/pdm/exceptions.py, src/pdm/models/specifiers.py, src/pdm/project/core.py, src/pdm/project/project_file.py, src/pdm/utils.py, tests/test_utils.py
=> feat: remove some deprecated members

docs/docs/usage/template.md, news/2543.feature.md, src/pdm/cli/templates/__init__.py, src/pdm/cli/templates/minimal/pyproject.toml
=> feat: Allow generating pyproject.toml without the extra project boilerplate

docs/docs/index.md
- [?] A news fragment is added in `news/` describing what is new. - is this required for documentation only changes?
- [N/A] Test cases added for changed code.
pyprojectx version 2.0 was recently released which changes the `--init` argument to `--add`
=> update pyprojectx install command

news/2564.feature.md, src/pdm/cli/actions.py, src/pdm/cli/commands/add.py, src/pdm/cli/commands/build.py, src/pdm/cli/commands/fix/__init__.py, src/pdm/cli/commands/fix/fixers.py, src/pdm/cli/commands/init.py, src/pdm/cli/commands/show.py, src/pdm/cli/completions/pdm.bash, src/pdm/cli/completions/pdm.fish, src/pdm/cli/completions/pdm.ps1, src/pdm/cli/completions/pdm.zsh, src/pdm/cli/utils.py, src/pdm/formats/requirements.py, src/pdm/models/repositories.py, src/pdm/project/core.py, src/pdm/resolver/core.py, tests/cli/test_init.py
=> feat: rename the package-type config to distribution

news/2573.bugfix.md, src/pdm/environments/python.py
=> fix: Dependency with additional headers fails to install

docs/docs/usage/template.md, news/2588.doc.md
Fixes #2588, a typo in the template docs.
=> Fix typo in template docs

news/2608.bugfix.md, src/pdm/formats/requirements.py, src/pdm/formats/setup_py.py
=> fix: reset project.environment when importing from setup.py

news/2631.bugfix.md, src/pdm/cli/commands/venv/backends.py, src/pdm/project/core.py
=> fix: pdm venv create succeeds/fails alternately

news/2660.feature.md, news/2660.removal.md, src/pdm/cli/commands/cache.py, src/pdm/environments/base.py, src/pdm/installers/installers.py, src/pdm/installers/manager.py, src/pdm/installers/uninstallers.py, src/pdm/models/cached_package.py, src/pdm/models/caches.py, src/pdm/models/candidates.py, src/pdm/project/core.py, src/pdm/utils.py, tests/cli/test_cache.py, tests/cli/test_venv.py, tests/models/test_candidates.py, tests/test_installer.py
=> feat: cache the decompressed content of wheels

news/2680.feature.md, src/pdm/environments/base.py, src/pdm/project/config.py
=> feat: timeout config for network requests

news/2678.bugfix.md, src/pdm/termui.py
=> fix: disable colors in pdm help on legacy terminals of windows

docs/docs/usage/venv.md, news/2720.feature.md, src/pdm/cli/commands/init.py, src/pdm/cli/commands/use.py, src/pdm/project/core.py, tests/cli/test_init.py
=> feat: create venv when switching python versions

news/2723.feature.md, src/pdm/cli/commands/publish/__init__.py, src/pdm/cli/completions/pdm.bash, src/pdm/cli/completions/pdm.fish, src/pdm/cli/completions/pdm.ps1, src/pdm/cli/completions/pdm.zsh
=> fix: supports custom distribution files path for pdm publish

tests/fixtures/pypi.json
Sort the `pypi.json` under `tests/fixtures` using VSCode extension: https://marketplace.visualstudio.com/items?itemName=richie5um2.vscode-sort-json
=> refactor: sort the pypi.json fixture

docs/dev/changelog.md, docs/dev/contributing.md
Docs-only changes, just fixing file references for `CHANGELOG.md` and `CONTRIBUTING.md`.
=> doc: fix path refs for CHANGELOG.md and CONTRIBUTING.md

docs/usage/dependency.md, news/2740.doc.md
=> Doc usage dependency typo

news/2739.bugfix.md, pdm.lock, pyproject.toml, src/pdm/installers/installers.py, src/pdm/models/cached_package.py, src/pdm/models/caches.py
=> fix: race condition issue for cached package

news/2754.bugfix.md, src/pdm/_types.py, src/pdm/cli/commands/publish/repository.py, src/pdm/environments/base.py, src/pdm/models/session.py, src/pdm/project/core.py
=> feat: per-source config of ca_certs and client_cert

news/2793.bugfix.md, src/pdm/core.py, tests/test_project.py
=> fix: `[tool.pdm.options]` is ignored by `pdm --config <somefile> ...`

news/2792.bugfix.md, src/pdm/project/core.py
=> fix: Error while trying to init a new project

.readthedocs.yaml
=> fix: try to fix docs

news/2809.bugfix.md, news/2810.bugfix.md, src/pdm/cli/commands/python.py
=> fix: A venv is created during a standalone python installation

news/2820.bugfix.md, src/pdm/installers/synchronizers.py
=> fix: install plugin in editable mode & from local path doesn't work

news/2825.bugfix.md, src/pdm/core.py, src/pdm/termui.py
=> fix: don't create log_dir until needed

.github/workflows/ci.yml, .github/workflows/release.yml
=> fix(ci): fix the CI matrix for the latest macos image release

news/2853.bugfix.md, src/pdm/cli/commands/add.py, src/pdm/project/core.py, tests/cli/test_add.py
=> fix: Inconsistent behaviour of `pdm add` in mode direct_minimal_versions

news/2872.feature.md, src/pdm/cli/commands/run.py
=> fix: make it easier to subclass runner

.github/workflows/ci.yml
=> chore(ci): add python 3.13 to the matrix

tests/conftest.py, tests/test_utils.py
=> fix(ci): simplify tests

news/2885.bugfix.md, src/pdm/cli/commands/update.py, tests/cli/test_update.py
=> fix: Inconsistent behavior between `pdm remove` and `pdm update`

news/2877.bugfix.md, src/pdm/cli/commands/export.py, src/pdm/cli/completions/pdm.fish, src/pdm/cli/completions/pdm.zsh
=> fix: don't show unsupported formats in export command

news/2898.bugfix.md, src/pdm/models/repositories.py
=> fix: self-referencing extra dependencies doesn't work for local packages

news/2900.bugfix.md, src/pdm/formats/poetry.py, src/pdm/models/requirements.py, tests/fixtures/projects/poetry-with-circular-dep/packages/child/pyproject.toml, tests/fixtures/projects/poetry-with-circular-dep/pyproject.toml, tests/test_formats.py
=> fix: Maximum recursion depth exceeded

news/2908.bugfix.md, src/pdm/cli/commands/add.py, src/pdm/formats/requirements.py, tests/cli/test_others.py, tests/test_formats.py
=> fix: `pdm export --self` is incompatible with hashes

news/2843.bugfix.md, src/pdm/cli/commands/build.py, tests/cli/test_build.py
=> fix: Build wheel from sdist to ensure a proper sdist is created.

news/2912.bugfix.md, src/pdm/models/candidates.py
=> fix: build cache miss

news/2913.bugfix.md, src/pdm/core.py, src/pdm/environments/base.py, src/pdm/models/caches.py, src/pdm/models/candidates.py, src/pdm/models/session.py, src/pdm/project/core.py, tests/cli/test_use.py
=> fix: don't touch caches if no-cache is given

news/2914.bugfix.md, src/pdm/models/session.py
=> fix: add retries for bad connection

news/2519.feature.md, src/pdm/cli/commands/export.py, src/pdm/cli/completions/pdm.bash, src/pdm/cli/completions/pdm.fish, src/pdm/cli/completions/pdm.ps1, src/pdm/cli/completions/pdm.zsh, tests/cli/test_others.py
=> feat: Supporting adding `extra` annotations to the exported `requirements` file

docs/usage/publish.md
=> docs(publish): add note on PyPI API tokens in docs/usage/publish.md

docs/usage/config.md, docs/usage/project.md, news/2967.doc.md
=> doc: some clarifications on the project setup

news/2976.bugfix.md, src/pdm/cli/actions.py, src/pdm/cli/utils.py, src/pdm/models/candidates.py, src/pdm/models/repositories.py, src/pdm/models/requirements.py, src/pdm/pytest.py, src/pdm/resolver/graph.py, tests/cli/test_lock.py, tests/models/test_candidates.py, tests/models/test_requirements.py
=> fix: Record extra groups in self-referencing dependencies

news/3005.bugfix.md, src/pdm/installers/synchronizers.py
=> fix: Retry failed installation jobs if they are run sequentially

.gitignore, news/3011.feature.md, pdm.lock, pyproject.toml, src/pdm/__init__.py, src/pdm/__version__.py, tasks/release.py
=> feat: add pdm/__init__.py to make it a normal package

news/3009.bugfix.md, src/pdm/models/candidates.py, src/pdm/models/requirements.py, src/pdm/project/core.py
=> fix: RequirementError when adding multiple local editable dependencies.

src/pdm/models/finder.py, tests/models/test_candidates.py
=> fix: don't skip validation when allow all env is passed

news/3018.bugfix.md, src/pdm/builders/base.py, src/pdm/builders/editable.py, src/pdm/builders/sdist.py, src/pdm/builders/wheel.py, src/pdm/installers/synchronizers.py
=> fix: Can't install non-isolated builds without extra steps

news/3020.bugfix.md, src/pdm/models/candidates.py
=> fix: add context when parsing version failed

docs/assets/extra.css, docs/overrides/main.html
fix chatbot style, make chatbot always display at the right height and set as topmost
=> docs: make chatbot always display at the right height and set as topmost

news/dep-logic.bugfix.md, pdm.lock, pyproject.toml
- [-] Test cases added for changed code.
=> Raise dep-logic lower bound to 0.4.2

news/3038.bugfix.md, pdm.lock, pyproject.toml, src/pdm/models/candidates.py, src/pdm/models/finder.py, src/pdm/models/requirements.py, src/pdm/models/specifiers.py, tests/models/test_candidates.py
=> fix: marker evaluation if the python_version is connected by `or`

news/3045.bugfix.md, src/pdm/cli/filters.py, tests/test_utils.py
=> fix: correct the logic of unselecting groups

news/3051.feature.md, src/pdm/installers/synchronizers.py, src/pdm/models/reporter.py
=> feat: Display Installation Time

docs/usage/config.md, news/3052.feature.md, src/pdm/project/config.py, src/pdm/project/core.py
=> fix: Allow to disable default PyPI without overriding it

news/ensure_bool_PDM_IGNORE_SAVED_PYTHON.md, src/pdm/project/core.py
added ensure boolean before getting PDM_IGNORE_SAVED_PYTHON in project/core.py
issue #3063
=> Ensure bool pdm ignore saved python

news/3067.bugfix.md, src/pdm/cli/commands/install.py, src/pdm/environments/python.py, src/pdm/installers/core.py, src/pdm/models/repositories/base.py, src/pdm/models/repositories/pypi.py
=> fix: PDM plugins installed from project-root cannot be loaded, if they have dependencies

news/3085.bugfix.md, src/pdm/core.py
=> fix: skip on parsing errors when invoking pdm commands

news/3094.bugfix.md, src/pdm/formats/requirements.py, src/pdm/installers/synchronizers.py, src/pdm/project/core.py, tests/cli/test_install.py
=> fix: `pdm export` does not backfill source `url` for PyPI

news/3100.feature.md, src/pdm/cli/actions.py, src/pdm/installers/core.py, src/pdm/installers/synchronizers.py, src/pdm/models/candidates.py, src/pdm/models/reporter.py, src/pdm/models/repositories/base.py, src/pdm/project/core.py, src/pdm/resolver/reporters.py, tests/resolver/test_resolve.py
=> feat: polish the ui looking of locking packages

news/3099.bugfix.md, src/pdm/project/config.py
=> fix: PDM_IGNORE_STORED_INDEX environment variable is ignored

news/3108.bugfix.md, pdm.lock, pyproject.toml, src/pdm/models/auth.py, src/pdm/project/config.py, tests/cli/conftest.py, tests/cli/test_config.py, tests/conftest.py
=> fix: PDM unable to delete source password when saved in keyring

news/3113.bugfix.md, src/pdm/installers/core.py
=> fix: Respect the `excludes` and `overrides` settings when installing packages

docs/usage/pep582.md, docs/usage/venv.md
Added notes on configuring PDM to use venv or PEP 582 to relevant pages.
refs #3120
refs #2708
refs #2174
=> [Docs] Add note how to switch between venv and PEP 582

docs/usage/advanced.md, docs/usage/publish.md
=> Update Github actions versions in documentation

docs/usage/dependency.md
=> Tweak some grammar in dependency.md

news/3159.removal.md, src/pdm/builders/editable.py
=> fix: remove the fallback backend for editable build error

CONTRIBUTING.md, docs/index.md, news/3183.doc.md
I was not able to setup shell completion in my 'Bash' shell until I ran into https://github.com/python-poetry/poetry/issues/2295
My submission is a solution that worked without any issues for me
=> Update documentation on setting up shell completions

pdm.lock, pyproject.toml
=> Bump the version of hishel

docs/usage/project.md, news/3201.feature.md, src/pdm/cli/commands/python.py, src/pdm/utils.py
=> fix: support free-threaded python and latest pbs-installer

news/3204.bugfix.md, src/pdm/cli/commands/venv/backends.py, src/pdm/formats/uv.py
=> fix: pass python path to uv venv command

docs/index.md, news/2470.doc.md
Show users the way to uninstall pdm in a more obvious way
=> update docs: Show users the way to uninstall pdm in a more obvious way

news/3216.bugfix.md, src/pdm/cli/commands/self_cmd.py, tests/cli/test_self_command.py
=> fix: self update using locked extra

news/3252.bugfix.md, src/pdm/cli/commands/run.py
=> fix: `FileNotFoundError` with pdm run and process substitution

news/3280.feat.md, src/pdm/resolver/graph.py, tests/resolver/test_graph.py
Use a dict to store set elements. Also add `__slots__` for speed.
=> Make `OrderedSet.__contains__` run in O(1)

docs/usage/dependency.md
- Remove outdated mention about `tool.pdm.dev-dependencies`;
- Slightly update the wording.
=> doc: improve documentation of "Dependency Groups"

news/3276.feature.md, src/pdm/project/core.py
Add a conditional statement to get clearer Python interpreter message. fix #3276
=> improve readability of Python interpreter validation message

news/3320.bugfix.md, src/pdm/builders/base.py, src/pdm/models/backends.py, tests/cli/test_init.py
=> fix: no longer requires wheel to build

news/3319.feature.md, news/3320.bugfix.md, src/pdm/resolver/providers.py
=> fix: Speed up the resolution by only resolving wheel candidates if possible

src/pdm/cli/actions.py, src/pdm/installers/base.py, src/pdm/installers/uv.py
=> fix: inconsistent behavior when removing package with uv enabled

docs/usage/uv.md, news/3330.feature.md, src/pdm/formats/uv.py, src/pdm/resolver/providers.py, src/pdm/resolver/uv.py, src/pdm/utils.py, tests/resolver/test_resolve.py, tests/resolver/test_uv_resolver.py
Hello this is only a POC just to be sure what I'm doing is not wrong. It seems to work fine on my environment, but I'm not sure about it. @frostming if you think it works, I will be more than happy to add fragment in `news` and also `tests`, if not, don't hesitate to tell me so :)
=> feat: Add resolution.overrides support for use_uv

news/3333.bugfix.md, src/pdm/project/core.py, tests/cli/test_add.py, tests/cli/test_update.py
=> fix: `pdm update -u` fails when a depenendcy group contains a dependency group include

news/3334.bugfix.md, src/pdm/_types.py, src/pdm/cli/commands/publish/__init__.py, src/pdm/project/config.py, src/pdm/project/core.py
=> fix: also read username from keyring if available

docs/index.md
I've changed the order of the installation commands for asdf and added the version to install.
It needs to be installed first, and later set the local version.
=> Change asdf installation commands order

news/3354.bugfix.md, src/pdm/cli/commands/import_cmd.py
=> fix: write dependency-groups when importing

README.md, README_zh.md
Poetry supports PEP621 since v2.0.0.
=> doc: update poetry state in README

docs/usage/config.md
Correct the path errors related to Windows in the configuration file documentation.
fixes #3398
=> doc: fix path for config

tests/cli/test_others.py
=> fix(ci): CI failure on windows-3.11

news/3389.feature.md, src/pdm/cli/commands/python.py, src/pdm/cli/completions/pdm.bash, src/pdm/cli/completions/pdm.fish, src/pdm/cli/completions/pdm.ps1, src/pdm/cli/completions/pdm.zsh, tests/cli/test_python.py
=> feat: Add `pdm python find` command to search for a python interpreter

news/3427.feature.md, src/pdm/cli/commands/import_cmd.py, src/pdm/formats/poetry.py
=> feat: convert poetry's package-mode setting

news/3426.bugfix.md, src/pdm/resolver/providers.py
=> fix: using resolution overrides drops extra dependencies

news/3434.bugfix.md, src/pdm/cli/actions.py
=> fix: Warning about inherit_metadata and UV always displayed

news/3407.bugfix.md, src/pdm/cli/commands/run.py, src/pdm/models/requirements.py, tests/test_plugin.py
=> fix: set project name if specified with URL

.github/workflows/release.yml, news/3429.feature.md
- close https://github.com/pdm-project/pdm/issues/3429
cc @Zheaoli 
I have tested the CI in https://github.com/kemingy/pdm/actions/runs/14147198843 & https://github.com/kemingy/pdm/releases/tag/v0.1.0-alpha.1
=> feat: use pyapp to build dist in release 

news/3447.bugfix.md, src/pdm/project/core.py
=> fix: incorrect cyclic group inclusion detected

news/3444.bugfix.md, src/pdm/models/candidates.py
=> fix: Can't install editable packages with PDM installed on 3.13

news/3455.bugfix.md, pdm.lock, pyproject.toml, src/pdm/models/candidates.py, src/pdm/pytest.py
=> fix: cache the build dir by link

news/3452.bugfix.md, pdm.lock, pyproject.toml, src/pdm/models/candidates.py, src/pdm/models/requirements.py, src/pdm/pytest.py, tests/cli/test_remove.py
=> fix: `pdm remove` does not handle dependency groups properly

src/pdm/installers/manager.py, src/pdm/installers/uninstallers.py
=> chore: use warning for termui.logger to avoid the deprecation

news/3461.bugfix.md, src/pdm/resolver/providers.py
=> fix: pdm lock --update-reuse with URL dependencies generates an invalid lock file

README_zh.md, docs/usage/dependency.md
using autocorrect to autocorrect 
FYI: https://github.com/huacnlee/autocorrect
=> doc: autocorrect using autocorrect

src/pdm/cli/commands/init.py, src/pdm/cli/commands/new.py
=> fix: do not run generator_args when new

pdm.lock
=> fix: update pywin32 version in lock close #3473

.github/workflows/ci.yml
=> ci: drop useless ignore since the change

news/3484.bugfix.md, src/pdm/installers/base.py, src/pdm/installers/core.py
=> fix: install self for BaseSynchronizer

README.md, README_zh.md, docs/index.md
=> docs: add the standalone binary release to installation part

.github/workflows/ci.yml, news/3506.misc.md, src/pdm/formats/flit.py, src/pdm/models/setup.py, tests/cli/test_cache.py, tests/models/test_candidates.py, tests/test_installer.py, tests/test_integration.py
=> ci: add Python 3.14 to the test matrix

CONTRIBUTING.md, docs/usage/config.md, docs/usage/dependency.md, docs/usage/lockfile.md, docs/usage/project.md, docs/usage/scripts.md, docs/usage/venv.md
- Write admonition keywords in lowercase
- Fix some broken admonitions by correcting content indentation
=> docs: Fix admonitions

news/3503.bugfix.md, pdm.lock, src/pdm/installers/base.py, src/pdm/models/repositories/base.py
=> fix: Reinstalling local wheel should check it's signature

news/3515.bugfix.md, pdm.lock, src/pdm/models/serializers.py, src/pdm/models/session.py
=> fix: ignore deserialization error

news/3518.bugfix.md, src/pdm/cli/commands/export.py, src/pdm/formats/pylock.py, src/pdm/models/requirements.py
=> fix: `pdm export -f pylock --self` misses self.

news/3517.bugfix.md, src/pdm/formats/pylock.py, tests/fixtures/projects/demo/pdm.lock, tests/fixtures/projects/demo/pylock.toml
=> fix: Add missing urls when running `pdm export -f pylock.

src/pdm/cli/commands/publish/repository.py, src/pdm/installers/installers.py, src/pdm/termui.py
This patch delete some dead code using [vulture](https://github.com/jendrikseipp/vulture)
FYI: not delete all of them some of the code are not sure
command
```cli
pdm run vulture . --exclude "*settings.py,*/docs/*.py,*/test_*.py,*/.venv/*.py,*/migrations/*.py" --min-confidence 60
```
=> fix: delete some dead using vulture

.github/workflows/ci.yml, pyproject.toml, src/pdm/models/serializers.py, tests/conftest.py, tests/models/test_serializers.py
=> test alpha

news/3522.feature.md, src/pdm/cli/actions.py, src/pdm/formats/pylock.py, src/pdm/formats/uv.py, src/pdm/models/caches.py, src/pdm/models/repositories/lock.py, src/pdm/models/session.py, src/pdm/project/core.py, src/pdm/project/lockfile/pdmlock.py, src/pdm/resolver/providers.py
=> fix: Search package metadata in lock file first when reuse

news/3545.bugfixl.md, src/pdm/core.py, src/pdm/models/repositories/lock.py, src/pdm/resolver/providers.py
=> fix: package metadata missing when reading from lockfile after 2.25

src/pdm/models/markers.py, src/pdm/models/repositories/lock.py
=> fix: split group markers from others when parsing pylock.toml

news/3557.dep.md, pdm.lock
=> chore: update resolvelib to 1.2.0

news/3561.bugfix.md, src/pdm/installers/synchronizers.py
=> fix: skip non-existent library paths in synchronizer

.github/workflows/ci.yml, news/3562.feature.md, pdm.lock, pyproject.toml, src/pdm/cli/commands/python.py, src/pdm/models/python.py, tests/cli/test_python.py
=> feat: tell the difference between freethreaded python and normal ones

pyproject.toml
- [-] A news fragment is added in `news/` describing what is new.
- [-] Test cases added for changed code.
closes #3580
=> chore: Add license file metadata

news/3582.bugfix.md, src/pdm/formats/pylock.py
Fixes #3582
Signed-off-by: Claude <claude@anthropic.com>
=> fix: Error when locking git dependency in pylock.toml format

news/3579.bugfix.md, src/pdm/models/candidates.py, src/pdm/resolver/providers.py
=> fix: read metadata from installed file when reuse-installed strategy is used.

src/pdm/formats/base.py
=> fix: Ensure make_array always returns a tomlkit array type.

src/pdm/cli/utils.py
=> feat: Preserve multi-line formatting in help output.

tests/test_integration.py
- [-] A news fragment is added in `news/` describing what is new.
- [-] Test cases added for changed code.
closes #3588
=> fix: mark additional tests that require network access

src/pdm/cli/actions.py
=> fix: clear candidate hashes when refreshing or using env_spec in do_lock

.gitignore, news/3601.dep.md, pdm.lock, pyproject.toml, src/pdm/models/requirements.py, tests/models/test_requirements.py
=> chore: Require packaging>22.0 and remove PACKAGING_22 checks

news/3605.bugfix.md, src/pdm/models/candidates.py
=> fix: PDM adds +cpu to torch version and then fails to install it

docs/usage/uv.md, news/3603.bugfix.md
=> fix: `uv python dir` path resolution on Windows

news/3615.bugfix.md, src/pdm/cli/commands/run.py, src/pdm/project/config.py
=> fix: `pdm.toml` is not considered in `pdm build` if it is created on-the-fly in a pre_build hook

CONTRIBUTING.md
=> docs(CONTRIBUTING): Fix code block indent

tests/test_utils.py
Covers the expected `PdmException` being thrown.
=> test(utils): Improve test coverage

src/pdm/environments/local.py, tests/environments/test_environment.py, tests/environments/test_shebangs.py
increase environment test. coverage
=> chore: increase environment coverage

.github/dependabot.yml
A dependabot configuration was added, to keep all workflows with the latest version of each action. It will open a PR every month bundling everything that needs to be updated. 
Should be merged after #3631.
=> feat: add dependabot for actions
