pdm-project/pdm

- .gitignore
- pdm/cli/actions.py
- pdm/cli/commands.py
- pdm/models/environment.py
- pdm/project/config.py
- tests/cli/test_cli.py
> new command: pdm use

- setup_dev.py
+ It seems that pip and pip_shims did some break changes.  We need to update pip and pip_shims before setup development
+ sys.version_info is a `Tuple[int, ...]`.  We need `str` here.
> Fixed setup_dev.py

- news/33.feature
- pdm.lock
- pdm/cli/commands.py
- pdm/project/core.py
- tests/cli/test_cli.py
> Reuse pinned candidates during `pdm install`

- .github/workflows/.ci.yml
- news/36.feature
- pdm/builders/wheel.py
- pdm/cli/actions.py
- pdm/cli/commands.py
- pdm/cli/options.py
- pdm/context.py
- pdm/exceptions.py
- pdm/installers.py
- pdm/models/caches.py
- pdm/models/candidates.py
- pdm/models/environment.py
- pdm/project/config.py
- pdm/project/core.py
- pdm/project/meta.py
- pdm/resolver/reporters.py
- pdm/utils.py
- pyproject.toml
- tests/cli/test_actions.py
- tests/cli/test_cli.py
- tests/conftest.py
- tests/models/test_candidates.py
- tests/models/test_markers.py
- tests/models/test_requirements.py
- tests/models/test_specifiers.py
- tests/resolver/test_resolve.py
- tests/test_project.py
> Integrate with pyenv

- README.md
- README_zh.md
- docs/docs/index.md
- docs/docs/project.md
- news/176.feature
- news/181.feature
- pdm/cli/actions.py
- pdm/cli/commands/run.py
- pdm/installers/_editable_install.py
- pdm/installers/_pep582.py
- pdm/installers/installers.py
- pdm/installers/synchronizers.py
- pdm/models/builders.py
- pdm/models/environment.py
- setup.cfg
- tests/cli/test_run.py
> New method of enabling PEP 582

- news/182.bugfix
- pdm/project/core.py
`wheels` is among the minimum dependencies injected for global projects resulting in crashes.
This change corrects the typo to `wheel`.
Below is an example traceback of the error
```
======== Start resolving requirements ========
pip
setuptools
wheels
Adding requirement pip
Adding requirement setuptools
Adding requirement wheels
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pdm/resolver/core.py", line 23, in _merge_into_criterion
crit = self.state.criteria[name]
KeyError: 'wheels'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/resolvelib/resolvers.py", line 310, in resolve
name, crit = self._merge_into_criterion(r, parent=None)
File …
```
> Fix global project dependencies (wheels -> wheel)

- news/197.feature
- pdm/core.py
- pdm/installers/synchronizers.py
> retry failed jobs

- docs/docs/index.md
- news/280.doc.md
I added a link to a [VSCode Task Provider extension](https://marketplace.visualstudio.com/items?itemName=knowsuchagency.pdm-task-provider) to the documentation for VSCode integration. 
My apologies, but I couldn't figure out how to properly add an entry in `/news` for `towncrier`, but would be happy to do so if given instructions on how.
Thanks!
> VSCode Task Provider Documentation

- news/299.bugfix.md
- pdm/models/candidates.py
- pdm/models/requirements.py
- tests/fixtures/projects/demo-failure-no-dep/demo.py
- tests/fixtures/projects/demo-failure-no-dep/setup.py
- tests/models/test_candidates.py
> Bugfix: Get dependencies error when the setup.py has no install_requires key

- docs/docs/index.md
VSCode Pylance needs to be configured to correctly search for dependencies.
> Add configuration to make pylance work

- docs/docs/project.md
- news/cmd-scripts-array.md
- pdm/cli/commands/run.py
- tests/cli/test_run.py
Field `cmd` in `tools.pdm.scripts` configuration items now allows specifying an argument array instead of a string.
> Allow `cmd` fields in `tool.pdm.scripts` section to contain arrays in addition to strings

- news/326.feature.md
- pdm/cli/actions.py
- pdm/cli/utils.py
- pdm/project/core.py
- pdm/utils.py
- pyproject.toml
- tests/test_utils.py
> Extract the logic of finding interpreters to a method

- news/331.feature.md
- pdm/cli/actions.py
- pdm/project/core.py
- pdm/utils.py
- tests/test_project.py
> Refactor: Unify the code about selecting interpreter

- CONTRIBUTING.md
- news/348.bugfix.rst
- tests/test_utils.py
- Fixes https://github.com/pdm-project/pdm/issues/347.
- On MacOS, python's `sys.prefix` and `sys.executable` are different. So this tests must have failed.
- I changed this test into "find the sys.executable path up to version just like `/usr/local/Cellar/python@3.9`, and compare it to sys.prefix with `startwith`" only when MacOS.
I checked this test with ubuntu on docker as well, and it runs correctly.
> Fix test_find_python_in_path: Check only up to version only when MacOS

- news/358.bugfix.md
- pdm/cli/actions.py
- pdm/cli/commands/run.py
- pdm/cli/commands/update.py
- pdm/cli/options.py
- pdm/cli/utils.py
- pdm/installers/synchronizers.py
- pdm/project/core.py
- tests/cli/test_actions.py
> Support update --dry-run to list outdated packages

- setup_dev.py
~~- [ ] A news fragment is added in `news/` describing what is new.~~
~~- [ ] Test cases added for changed code.~~
Fixes notification:
> [CHANGE IN 1.5.0]: dev-dependencies are included by default and `-d/--dev` is redundant
> Remove redundant `-d` with `pdm install` in setup_dev.py

- news/421.misc.md
- pdm/models/candidates.py
- pdm/models/repositories.py
I'm currently struggling with installing packages from multiple repos and had the impression that the log output could be improved.
The PR adds some more log output (log level: DETAIL) about matching candidates and their origin. If no matching candidates could be found, the non-matching candidates are printed to give the user some idea what might have gone wrong.
> Feat add candidate output

- news/422.bugfix.md
- pdm/pep582/sitecustomize.py
- tests/cli/test_run.py
- tests/conftest.py
- tests/test_integration.py
Try to use nix to build an isolating environment for PDM development. But pdm can not co-exist with Python packages in nix due to the import mechanism that Python only imports module once by name.
The Python in nix using sitecustomize.py to import packages and PDM also using it to enable PEP582 globally. 
Hence, we need to **make sure that another sitecustomize.py gets imported if it exists**. So PDM can make PEP582 enabling globally, and  Python in nix also can import its packages.
> Seek for other sitecustomize.py to import

- .pre-commit-config.yaml
- news/451.misc.md
- setup.cfg
Fix the wrong Mypy configuration. It would be better that change to execute `mypy pdm` instead of executing `mypy` with `files=pdm/**/*.py` because `files=...` ignores `exclude=...`.
`follow_imports = silent` is for avoiding that it reports errors which came from `pdm/_vendor`.
> Fix wrong mypy configuration

- docs/docs/usage/dependency.md
The PEP621 link to the project metadata goes to https://pdm.fming.dev/pyproject/pep621.md (which 404). It should go to https://pdm.fming.dev/pyproject/pep621/ instead
> Fix 404 link on doc page

- news/477.bugfix.md
- pdm/builders/base.py
- pdm/cli/actions.py
- pdm/utils.py
- tests/test_utils.py
> Fix the isolation of build env

- pyproject.toml
I installed PDM in an environment that had a few other dependencies and got this error:
```
> pdm init -v
Creating a pyproject.toml for PDM...
Please enter the Python interpreter to use
0. /usr/bin/python (2.7)
1. /usr/local/bin/python3 (3.9)
2. /usr/local/bin/python3.9 (3.9)
3. /usr/bin/python3 (3.8)
4. /usr/bin/python2 (2.7)
5. /usr/bin/pythonw (2.7)
6. /usr/bin/python2.7 (2.7)
7. /usr/local/opt/python@3.9/bin/python3.9 (3.9)
Traceback (most recent call last):
File "/usr/local/bin/pdm", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 185, in main
return Core().main(args)
File "/usr/local/lib/python3.9/site-packages/pdm/core.py", line 146, in main
raise cast(Exception, err).with_traceback(traceback)
File …
```
> Define minimal version for click

- README.md
- README_zh.md
- docs/docs/index.md
- news/522.bugfix.md
- news/522.doc.md
> Add install instructions for scoop

- pdm.lock
- pdm/builders/base.py
- pdm/cli/completions/pdm.ps1
- pdm/cli/completions/pdm.zsh
- pdm/cli/utils.py
- pdm/formats/flit.py
- pdm/formats/legacy.py
- pdm/formats/pipfile.py
- pdm/formats/poetry.py
- pdm/formats/requirements.py
- pyproject.toml
Text file objects are deprecated in Tomli. This PR moves to using binary file objects to avoid deprecation warning
> Fix tomli deprecation warning

- docs/docs/usage/dependency.md
- docs/docs/usage/project.md
- tests/cli/test_cli.py
- tests/test_project.py
`testpypi.org` URL seems wrong; `test.pypi.org` should be used instead.
> Use test.pypi.org instead of testpypi.org

- docs/mkdocs.yml
https://www.mkdocs.org/user-guide/configuration/#edit_uri
Currently, the edit links on pages points to, for example, https://github.com/pdm-project/pdm/edit/master/docs/pyproject/pep621.md.
With the `edit_uri` option, we can fix it to point to the right location: https://github.com/pdm-project/pdm/edit/main/docs/docs/pyproject/pep621.md
> Adapt edit URI on docs pages

- docs/docs/pyproject/pep621.md
- docs/docs/usage/advanced.md
- pdm/cli/commands/add.py
- pdm/cli/commands/import_cmd.py
- pdm/cli/commands/remove.py
- pdm/cli/options.py
- ~[ ] A news fragment is added in `news/` describing what is new.~ Not applicable
- ~[ ] Test cases added for changed code.~ Not applicable
Looks like some occurrences of `-s` option were not replaced in https://github.com/pdm-project/pdm/pull/591
Also fixing a typo where `--groups` is used instead of `--group` in CLI deprecation descriptions.
> Replace remaining deprecated usages of `-s` in doc

- docs/docs/index.md
Small documentation improvement suggestion: I copied the code for `.vscode/settings.json`, the file didn't exist in my project. The copied code included the ellipsis for other settings.
I think it's better to not include the ellipsis in the code and rephrase, so it's clear it should be added to existing configuration.
Fixes #736
> Remove ellipsis from config sample for copy

- docs/docs/pyproject/pep621.md
- docs/docs/usage/advanced.md
- docs/docs/usage/dependency.md
- docs/docs/usage/project.md
docs: clarify the use of `-d` without `-G`
It's clearer that you can use `pdm add --dev pytest`, because when you
arrive this point in the documentation, you don't know that `-d` means
`--dev`.
docs: add the `minimum` save strategy
It's the default and it was not mentioned! :P
docs: mark the `reuse` update strategy as the default
docs: fix typos
docs: add the `pdm-publish` as an option to upload packages
docs: remove duplicated install cache version
It's already documented [here](project.md#cache-the-installation-of-wheels).
docs: Update the Python versions of the github action snippet
Just documentation, so no need to add anything under `news` or `tests`
> Small documentation improvements

- news/642.feature.md
- pdm/cli/actions.py
- pdm/cli/commands/lock.py
- pdm/cli/completions/pdm.bash
- pdm/cli/completions/pdm.fish
- pdm/cli/completions/pdm.ps1
- pdm/cli/completions/pdm.zsh
- tests/cli/test_cli.py
> Feature: pdm lock --refresh

- news/810.feature.md
- pdm/cli/actions.py
- pdm/cli/commands/install.py
- pdm/cli/commands/sync.py
- pdm/cli/completions/pdm.bash
- pdm/cli/completions/pdm.fish
- pdm/cli/completions/pdm.ps1
- pdm/cli/completions/pdm.zsh
- tests/cli/test_add.py
- tests/cli/test_build.py
- tests/cli/test_install.py
- tests/cli/test_list.py
- tests/cli/test_others.py
- tests/cli/test_remove.py
- tests/cli/test_update.py
- tests/cli/test_use.py
> Feature: pdm install --check

- news/875.bugfix.md
- pdm/models/candidates.py
- pdm/models/pip_shims.py
> Add missing verbosity flag

- tests/fixtures/index/demo.html
- tests/fixtures/index/future-fstrings.html
- tests/fixtures/index/pep345-legacy.html
Its a temporary solution, should migrate to `html.parser` as `html5lib` will be [deprecated](https://github.com/pypa/pip/pull/10291). New parser requires doctypes.
Or add html5lib/another parser as a dependency.
> Add doctype

- .github/workflows/ci.yml
- news/920.refactor.md
- pdm/cli/actions.py
- pdm/cli/commands/show.py
- pdm/cli/utils.py
- pdm/formats/requirements.py
- pdm/installers/manager.py
- pdm/installers/synchronizers.py
- pdm/models/candidates.py
- pdm/models/repositories.py
- pdm/project/core.py
- pdm/resolver/providers.py
- pdm/resolver/python.py
- pdm/resolver/reporters.py
- pdm/utils.py
- tests/cli/test_add.py
- tests/cli/test_install.py
- tests/conftest.py
- tests/models/test_candidates.py
- tests/test_installer.py
- tests/test_integration.py
> Refactor: Extract environment related code from Candidate

- .github/workflows/ci.yml
- news/930.dep.md
- pdm.lock
- pdm/_vendor/halo/_utils.py
- pdm/builders/base.py
- pdm/cli/actions.py
- pdm/cli/commands/info.py
- pdm/installers/installers.py
- pdm/models/environment.py
- pdm/models/in_process/__init__.py
- pdm/models/python.py
- pdm/models/repositories.py
- pdm/project/core.py
- pyproject.toml
- tasks/patches/halo-multiple.patch
- tasks/patches/log-symbols-support-utf8.patch
- tests/cli/test_others.py
- tests/cli/test_run.py
- tests/cli/test_use.py
- tests/test_integration.py
- tests/test_project.py
> Switch from pythonfinder to findpython

- .github/workflows/ci.yml
- news/932.bugfix.md
- pdm.lock
- pdm/models/specifiers.py
- pdm/project/core.py
> Support prereleases in python requires

- news/1036.bugfix.md
- pdm/formats/requirements.py
- pdm/models/requirements.py
- tests/fixtures/requirements.txt
- tests/test_formats.py
> Encode the requirments.txt from ireq

- docs/docs/pyproject/pep621.md
This is in line with
https://peps.python.org/pep-0440/#direct-references.
PEP 508 only has an example with a zip file
(https://peps.python.org/pep-0508/#examples).
The original example fails like this:
> % pdm add "pip @ https://github.com/pypa/pip.git@20.3.1"
Adding packages to default dependencies: pip @ https://github.com/pypa/pip.git@20.3.1
⠸ Resolving dependencies
See /tmp/pdm-lock-nnaadyua.log for detailed debug log.
[NetworkConnectionError]: 404 Client Error: Not Found for url: https://github.com/pypa/pip.git@20.3.1
Add '-v' to see the detailed traceback
> doc: fix URL requirement example with "Dependency specification"

- news/1098.feature.md
- pdm/resolver/providers.py
- setup.cfg
> Speedup resolution with lazy find_matches

- news/1101.bugfix.md
- pdm/models/setup.py
- tests/models/test_setup_parsing.py
> Give a default version if the version is dynamic in setup.cfg

- news/1103.bugfix.md
- pdm/models/repositories.py
> Prepare the candidate before calculating the hash

- news/1111.bugfix.md
- pdm/models/specifiers.py
- pdm/models/versions.py
- pdm/project/core.py
- tests/models/test_specifiers.py
- tests/models/test_versions.py
Recently, coverage 6.4.1 listed its requirements with an alpha version of
python and this broke PDM's version parsing:
extras_require={
'toml': ['tomli; python_full_version<="3.11.0a6"'],
},
Prerelease `requires-python` versions *are* valid, per these specifications:
* https://peps.python.org/pep-0440/
* https://peps.python.org/pep-0621/#requires-python
* https://packaging.python.org/en/latest/specifications/core-metadata/#requires-python
Therefore this commit adds missing parsing support for `{a|b|rc}[N]`
pre-release specifiers which are used by python language releases:
* https://docs.python.org/3/faq/general.html#how-does-the-python-version-numbering-scheme-work
This bug meant that projects that directly or indirectly depended on coverage
were unable to update pdm.lock using commands …
> Fix crash if dependencies have prerelease requires-python versions

- docs/docs/usage/scripts.md
- news/1117.feature.md
- pdm/cli/commands/run.py
- tests/cli/test_run.py
- tests/conftest.py
This PR adds a "composite script" feature allowing to run multiple scripts one by one.
A classical use case would be:
```toml
[tool.pdm.scripts]
lint = "flake8 mypackage"
test = "pytest -v tests/"
ci = {composite = ["lint", "test"]}
```
Then `pdm run ci` will run the `lint` command and then the `test` command. Execution stops and returns on first error.
Both `env` and `env_file` defined in `composite` action will override those defined in called tasks.
So with the following:
```toml
[tool.pdm.scripts]
echo = {shell = "echo $VAR", env = { VAR = "value"}}
composite = {composite = ["echo"], env = { VAR = "overriden"}}
```
you will have:
```console
$ pdm run echo
value
$ pdm run composite
overriden
```
> Feature: composite scripts

- docs/docs/usage/scripts.md
- news/1127.feature.md
- pdm/cli/actions.py
- pdm/cli/commands/add.py
- pdm/cli/commands/build.py
- pdm/cli/commands/init.py
- pdm/cli/commands/install.py
- pdm/cli/commands/lock.py
- pdm/cli/commands/publish/__init__.py
- pdm/cli/commands/remove.py
- pdm/cli/commands/run.py
- pdm/cli/commands/sync.py
- pdm/cli/commands/update.py
- pdm/cli/hooks.py
- pdm/cli/options.py
- pyproject.toml
- tests/cli/conftest.py
- tests/cli/test_hooks.py
- tests/cli/test_lock.py
- tests/cli/test_others.py
- tests/cli/test_publish.py
- tests/cli/test_run.py
- tests/conftest.py
- tests/test_signals.py
This PR is a proposal at implementing #948.
If provides 2 parameters:
- `--skip-hooks` that will skip any hook (or pre/post script) involved in the execution
- `--skip` which can take any arbitrary task or hook name(s) and skip it/them
Those 2 parameters have been added to the following commands
- `run`
- `install`
- `lock`
- `build`
- `init`
The `--skip` can be used many times. The following commands are all equivalents
- `--skip=pre_task1,task2`
- `--skip pre_task1,task2`
- `--skip=pre_task1 --skip=task2`
- `--skip pre_task1 --skip task2`
The both options can be used together:
```console
pdm run --skip-hooks --skip=taskn my-composite-task
```
> Feature: Option to skip hooks

- README.md
- install-pdm.py
- news/1145.misc.md
I created a [asdf-vm](https://asdf-vm.com/) plugin for PDM https://github.com/1oglop1/asdf-pdm. 
And created an issue to add it to the community plugins #asdf-community/.github/issues/33. 
Also a minor change to a variable name `bin` which was shadowing builtin function `bin`.
> Add option to skip _add_to_path in installer

- pdm/cli/commands/run.py
Just clean up a remaining artifact from #1127 (not used anymore in the final version)
> chore: remove remaining artifacts from #1127

- docs/docs/usage/hooks.md
- docs/docs/usage/scripts.md
- docs/mkdocs.yml
- news/1147.feature.md
- pdm/cli/commands/build.py
- pdm/cli/commands/init.py
- pdm/cli/commands/install.py
- pdm/cli/commands/lock.py
- pdm/cli/commands/publish/__init__.py
- pdm/cli/commands/run.py
- pdm/cli/hooks.py
- pdm/signals.py
- tests/cli/conftest.py
- tests/cli/test_hooks.py
- tests/cli/test_run.py
This PR follows #1127 and adds the following:
- signals:
- `pre_publish` executed before publishing
- `post_publish` executed before publishing
- `pre_script` executed before **each** script execution (runs multiple times in case of composite script)
- `post_script` executed after **each** script execution (runs multiple times in case of composite script)
- `pre_run` executed once before a run (run only once in case of composite script)
- `post_run` executed once after a run (run only once in case of composite script)
- commands:
- `new`: just because I documented if and it wasn't existing (I'm also rust/cargo user, I bootstrap project with it)
- documentation:
- a new dedicated `Lifecycle and hooks` section with detailled lifecycle documentation with flow charts
- update/re-lock doc …
> Feature: complete lifecycle signals and documentation

- news/1151.feature.md
- pdm/cli/commands/run.py
- pdm/termui.py
- tests/cli/test_run.py
While the current script listing is working fine when your command are short one-liners, it was broken for multilines scripts on `main` (where this PR was initially implemented).
Now that `dev` switched on a `rich` table display, I'm not sure whether it is improvement or not so I submit it anyway,
This PR improvement proposal was to merge the `Script` and `Description` column into a single `Description` column displaying the `help` if available and if not:
- display the sequence of calls for `composite`
- display the first line of script with a `⮨` ellipsis if it has been truncated
Also, the list is now sorted.
Here the same output for `main`, `dev` and this PR for this given `tool.pdm.scripts`:
```toml
[tool.pdm.scripts]
all = {composite = ["format", "lint", "cover"]}
test = "pytest …
```
> Proposal: Fix for multilines and composite scripts listing

- CONTRIBUTING.md
- docs/mkdocs.yml
- news/1160.misc.md
- pdm.lock
- pyproject.toml
- tox.ini
Just add a `tox.ini` file for easier local testing against all supported Python versions.
It requires `tox-pdm`, can be either run using `tox` diurectly or through PDM with `pdm run tox` (depends on the new `tox` development dependency group)
> Adds a tox.ini file for easier local testing against all Python versions

- docs/docs/usage/scripts.md
- docs/mkdocs.yml
- news/1159.feature.md
- pdm/core.py
- tests/cli/test_run.py
- tests/conftest.py
This PR allow to execute PDM scripts without the `run` command prefix as long as it doesn't conflict with any builtin command or any plugin-provided command.
In case of error, it produces the exact same output, especially in case of shell command not found (ie. instead of having the command not found error from your shell as `run` does, you still have the PDM usage and error).
In the process I made the "no parameters provided" behavior the same as any others parsing error: usage (help in in this case) is printed on `stderr` instead of `stdout` [here](https://github.com/pdm-project/pdm/pull/1159/files#diff-3a198f24ba7555b1c4cf4d06730a48e6d7494772cda928b78676a76f0f1a0cd9L158-R184).
**Note:** the `click.testing.CliRunner` have some known issues with `stderr` (`stderr` is unbuffered but …
> feat(CLI): Yarn-like root scripts fallback

- docs/docs/usage/hooks.md
- news/1163.feature.md
- pdm/cli/actions.py
- pdm/cli/commands/init.py
- pdm/cli/commands/use.py
- pdm/signals.py
- tests/cli/test_hooks.py
- tests/cli/test_others.py
- tests/conftest.py
This PR adds a `post_use` hook which was missing while being very useful.
In my use case, a `pdm-vscode`extensions (WIP) it allows the extension to automatically update `VSCode` settings when you switch Python version.
As there are already many hooks, I didn't add the `pre_use` but I can.
> feat(hooks): added a post_use hook

- README.md
- README_zh.md
- docs/docs/dev/benchmark.md
- docs/docs/index.md
- pyproject.toml
- Change the project description to not highlighting PEP 582
- Remove the Python Development Master from the tagline. We don't explicitly declare the full expanded name of PDM, while users can derive it from the description: `a modern Python package and dependency manager supporting the latest PEP standards`
- Supersedes #1064
> chore: change the project description

- news/correct-zsh-completion.md
- pdm/cli/completions/pdm.zsh
Fixed the `invalid option definition` in the pdm zsh completion for the --pep582 flag.
The exact error was `_arguments:comparguments:327: invalid option definition: --pep582=[Print the command line to be eval by the shell]:shell:(zsh bash fish tcsh csh)`.
Images:
The problem:
The fix:
> Fixed zsh completion for pep582 flag

- news/1224.bugfix.md
- pdm/cli/actions.py
Now lockfile is written before `post_lock` hook. Fixes #1224
> fix: write lockfile before post_lock hook

- news/1226.bugfix.md
- pdm/cli/actions.py
- pdm/project/core.py
> fix: suppress errors when cache dir isn't accessible

- news/1235.feature
- pdm/cli/commands/run.py
- tests/cli/test_run.py
This changes the logic when using an env_file such that any
environment variables defined within it do not override existing set
environment variables. This matches the default logic of dotenv and
should match user expectations.
> env_file variables do not override existing

- news/1256.bugfix.md
- pdm/cli/utils.py
- pdm/resolver/core.py
- tests/cli/test_lock.py
Make pdm.lock metadata.files sorting idempotent
In #1203 pdm.lock was changed to store a list of URLs rather than wheel
names. That change caused a regression because we were sorting the
output based on filename only, not the full URL.
This caused unnecessary lockfile changes in our CI environment.
Fixes #1256
> Fix locking sort bug

- news/1255.bugfix.md
- pdm/project/core.py
- tests/cli/test_venv.py
> fix: try `python` executable first

- news/1276.bugfix.md
- pdm/models/project_info.py
- tests/cli/test_others.py
> fix: Crashes when executing pdm show for an sdist

- .pre-commit-hooks.yaml
- docs/docs/usage/advanced.md
- docs/docs/usage/project.md
- news/1279.feature.md
Added `pdm export` to available pre-commit hooks. This can be used for CI pipelines. The file `pre-commit-hooks.yaml` can be expanded in the future with other hooks to expose.
Updated the doc accordingly.
> Add pdm export to available pre-commit hooks

- news/1293.bugfix.md
- pdm.lock
- pyproject.toml
Fixes #1293.
I've set the minimum version of `packaging` to 20.9 in `pyproject.toml`, which I think should resolve the issue.
> fix: set minimum version for `packaging` dependency

- docs/docs/usage/scripts.md
- news/1299.feature
- pdm/cli/commands/run.py
- tests/cli/test_run.py
This allows the user to specify that the env_file should override any
existing environment variables. This is not the default as the
environment the code runs it should take precedence.
> Add an override option to the env_file script option

- docs/docs/pyproject/build.md
- news/1327.doc.md
Since the behavior changes with run-setuptools, and since is-purelib
also changes, it was a little confusing how everything was intended to
work. After reading the code I updated the documentation to be more
clear.
See also a similar pull request in pdm-pep517: https://github.com/pdm-project/pdm-pep517/pull/116
#1327
> Clean up documentation related to new setup-script

- src/pdm/cli/options.py
"filename": "pdm/cli/options.py"
"warning_type": "Incompatible variable type [9]",
"warning_message": " name is declared to have type `str` but is used as type `None`.",
"warning_line": 62
"fix": remove none
> Pyre: name has type `str` but is used as type `None`

- src/pdm/cli/commands/config.py
- src/pdm/cli/options.py
- src/pdm/project/config.py
- tests/cli/test_config.py
> feat: remove deprecated config names

- news/1220.bugfix.md
- news/1381.bugfix.md
- src/pdm/cli/actions.py
- src/pdm/models/candidates.py
- src/pdm/models/repositories.py
- src/pdm/models/requirements.py
- src/pdm/project/core.py
- tests/models/test_requirements.py
- Resolve #1381
- Resolve #1220
- Related to #464
> fix: Fix the support for relative paths from outside the project

- .github/workflows/ci.yml
GitHub deprecated set-output command, recommend using GITHUB_OUTPUT environment file instead:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Current warnings in [CI](https://github.com/pdm-project/pdm/actions/runs/3241934222/jobs/5314532917):
> Replace deprecated `set-output` command with `GITHUB_OUTPUT` file

- docs/docs/usage/hooks.md
I was looking at the online documentation, and clicking on the link did not work, so I decided to fix it quickly.
> chore: fix typo in documentation link id

- news/1459.feature.md
- src/pdm/cli/commands/lock.py
- tests/cli/test_lock.py
Added a `--check` flag to `pdm lock` as discussed in #1459.  I followed the pattern from install, which I wasn't aware of. I do think `lock --check` is a more logical check and easier to discover.
> add `--check` flag to `pdm lock`

- .github/workflows/ci.yml
- src/pdm/cli/actions.py
- src/pdm/cli/commands/list.py
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- src/pdm/cli/utils.py
- src/pdm/installers/uninstallers.py
- tests/cli/test_list.py
- tests/cli/test_others.py
- tests/conftest.py
- Improve `--sort` to accept a comma-separated string
- Packages are included or excluded in the tree approach, when a package is excluded, all its dependencies are excluded, too.
- Modify test cases according to the expected behavior
cc @JohnHardy
> feat: enhance the pdm list command

- .pre-commit-hooks.yaml
- docs/docs/usage/advanced.md
- news/1471.feature.md
> pdm lock --check pre-commit hook

- news/1471.feature.md
- src/pdm/pep582/sitecustomize.py
Make `sitecustomize.py` respect the `PDM_PROJECT_MAX_DEPTH` environment variable
> Make `sitecustomize.py` respect the `PDM_PROJECT_MAX_DEPTH` environment variable. Resolves #1413.

- news/1491.feature.md
- src/pdm/builders/base.py
- src/pdm/project/core.py
- src/pdm/project/project_file.py
> feat: beautify the build error

- src/pdm/cli/actions.py
Signed-off-by: Leonard Crestez <cdleonard@gmail.com>
> fix: Handle "sh" and "dash" in print_pep582_command (#1502)

- news/1516.bugfix.md
- pdm.lock
- src/pdm/cli/actions.py
- src/pdm/models/python.py
- tests/cli/test_use.py
> fix: test against the latest findpython

- src/pdm/project/core.py
Before this fix, when running `pdm use python` if there was a file or folder named `python` then the code would not look for other installed interpreters.
fixes #1523
> Fix finding interpreters if file matches spec

- news/1528.dep.md
- pdm.lock
- pyproject.toml
- src/pdm/builders/base.py
- src/pdm/builders/editable.py
- tox.ini
> feat: replace pep517 with pyproject-hooks

- docs/docs/pyproject/build.md
The behavior of `includes` seems to imply that any files listed will be *added* to the package itself. However the latter has to be also explicitly included. This can cause confusion when adding `includes` for the first time in an already existing package, whereby the package itself will suddenly disappear from the build. Clarify this in the documentaion.
Fixes https://github.com/pdm-project/pdm/issues/1531
> docs: clarify the behavior of includes

- docs/docs/usage/scripts.md
- news/1507.feature.md
- src/pdm/cli/commands/run.py
- tests/cli/test_run.py
Allows specifying the insertion position of user provided arguments in scripts with the `{args[:default]}` placeholder.
The placeholder can be used in two forms:
- `{args}` which will be replaced by user provided extra arguments if any
- `{args:default values}` which will be replaced by user provided extra arguments if any or else by the defaults values
As soon as a placeholder is detected,  the extra user arguments are not automaticcaly appended anymore. This is especially important for composite scripts: a single placeholder deactivate the automatic append on all subscripts giving you control on which subscripts receive the arguments or not.
**Edit**: `call` scripts was initialy added to this PR but has been removed given they have access to `sys.argv` directly to handle such cases. …
> Allows specifying the insertion position of user provided arguments in scripts

- pdm.lock
- pyproject.toml
PDM uses the method `unwrap` from `tomlkit` which was added only in `tomlkit-0.11.0`. When I upgraded PDM from an old version and ran it, I got an error because of this.
I think these tasks are unnecessary for such a small change:
> Fix minimum version requirement for tomlkit

- news/1552.bugfix.md
- src/pdm/models/requirements.py
- src/pdm/utils.py
- tests/fixtures/projects/demo-#-with-hash/demo.py
- tests/fixtures/projects/demo-#-with-hash/setup.py
- tests/models/test_candidates.py
The command `pdm add -e ./demo --dev` result on a line added to pyproject.toml
```
dev = [
"-e file:///${PROJECT_ROOT}/demo#egg=demo",
]
```
Any following `pdm add` will result on an error
```
Adding packages to dev dev-dependencies: -e file:///${PROJECT_ROOT}/demo#egg=demo
[RequirementError]: Editable requirement is only supported for VCS link or local directory.
```
> fix: egg segment for local dependency

- news/1560.bugfix.md
- src/pdm/installers/core.py
- src/pdm/models/repositories.py
- src/pdm/models/requirements.py
>  fix: support relative paths in build requires

- news/1562.bugfix.md
- src/pdm/cli/utils.py
- src/pdm/models/requirements.py
- src/pdm/utils.py
- tests/cli/test_add.py
- tests/resolver/test_resolve.py
> fix: Strip the local part when building a specifier for comparison

- news/1560.bugfix.md
- news/1568.dep.md
- pdm.lock
- pyproject.toml
It resolves the following issues, while still allows future packaging versions to be installed
- #1556
- #1558
> fix: Exclude `packaging 22.0` to avoid breakage

- news/1567bugfix.md
- pdm.lock
- pyproject.toml
- src/pdm/__version__.py
- src/pdm/cli/actions.py
- src/pdm/cli/commands/run.py
- src/pdm/cli/commands/self_cmd.py
- src/pdm/cli/utils.py
- src/pdm/core.py
- src/pdm/models/in_process/__init__.py
- src/pdm/models/specifiers.py
- src/pdm/utils.py
- tests/cli/test_run.py
Use `importlib.resources` to read script or data inside the package, to replace the usages of `__file__` variable. This will enable PDM to be used in a zipapp.
> feat: remove usages of __file__ to support pdm in a zipapp

- news/1580.bugfix.md
- src/pdm/installers/uninstallers.py
> fix: correctly mark a symlink as file to remove

- .pre-commit-config.yaml
- docs/docs/plugin/fixtures.md
- docs/docs/plugin/reference.md
- docs/docs/plugin/write.md
- docs/mkdocs.yml
- news/1594.feature.md
- pdm.lock
- pyproject.toml
- src/pdm/pytest.py
- tests/cli/test_install.py
- tests/cli/test_list.py
- tests/conftest.py
This PR follows the discussion https://github.com/pdm-project/pdm/discussions/1571 and extract most pytest fixtures into their own public module `pdm.pytest`.
This allows pdm plugin developpers to benefits from them by importing them as a plugin:
```python
pytest_plugins = [
"pdm.pytest",
]
```
When relying on local file fixtures or any other configurable part, this is done by a dependency fixture.
The PDM test suite rely on those fixtures and configure them with PDM test fixtures (and so the PDM test suite is an usage example of those fixtures)
Given those fixtures are now in `src`, type hinting has been completed to comply with MyPy.
Documentation has been added in a dedicated page to differentiate from the real PDM API. Obviously, given I didn't write those, there might be some issues …
> feat(pytest): expose pytest fixtures and helpers for pdm plugins

- src/pdm/cli/commands/update.py
> docs: Fix typo in help output of update command

- docs/docs/usage/configuration.md
fix `venv.in_project` small typo in configuration docs
> docs: fix configuration typo for `venv.in_project`

- src/pdm/cli/utils.py
- src/pdm/formats/poetry.py
Avoid duplicates in dependencies/authors when importing from requirements, Poetry (#1584)
As there is some logic in the `do_import` action, we may want to add testing for the CLI command `import` or move this logic in the converters.
> Fix: Deduplicate lists when running pdm import

- news/1626.feature.md
- src/pdm/cli/commands/run.py
- tests/cli/test_run.py
> feat: support implicit python script execution

- news/1652.bugfix.md
- src/pdm/cli/commands/run.py
- src/pdm/models/environment.py
If the environment is a virtualenv, `pdm run` will set the `VIRTUAL_ENV` environment variable, which lets tools know that a virtualenv is in use. This means that (for example) the `py` launcher on Windows correctly locates the environment's Python rather than using the system Python.
Fixes #1650
> Set VIRTUAL_ENV in pdm run

- .github/workflows/ci.yml
- news/1660.bugfix.md
- src/pdm/__version__.py
- src/pdm/cli/commands/completion.py
- src/pdm/cli/utils.py
- src/pdm/compat.py
- src/pdm/models/in_process/__init__.py
- src/pdm/models/specifiers.py
> fix: eliminate the importlib.resources warnings

- docs/docs/usage/project.md
- news/1667.feature.md
- src/pdm/_types.py
- src/pdm/cli/commands/config.py
- src/pdm/cli/commands/publish/__init__.py
- src/pdm/cli/commands/publish/repository.py
- src/pdm/formats/poetry.py
- src/pdm/formats/requirements.py
- src/pdm/models/auth.py
- src/pdm/models/environment.py
- src/pdm/models/repositories.py
- src/pdm/project/config.py
- src/pdm/project/core.py
- src/pdm/pytest.py
- src/pdm/utils.py
- tests/models/test_candidates.py
- tests/test_project.py
> feat(core) merge index parameters

- news/1635.bugfix.md
- src/pdm/cli/actions.py
- src/pdm/installers/synchronizers.py
> fix: Fix the log leakage in installation

- news/1708.feature.md
- src/pdm/cli/commands/init.py
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- src/pdm/termui.py
> feat: add option --lib to init command to create a library project

- news/1709.bugfix.md
- src/pdm/models/environment.py
PDM would previously crash (assertion error) when trying to update the shebang in a script that is a binary file.
This change prevents that.
Fixes #1709.
> fix: Don't crash when trying to update the shebang in a binary script

- docs/docs/usage/advanced.md
- docs/docs/usage/pep582.md
- news/1721.doc.md
- [N/A] Test cases added for changed code.
MS's python lang server (as well as lsp-python-ms) are archived in favor of pyright. Additionally, eglot will be packaged with Emacs once Emacs 29 is released.
> Add pyright/eglot config for emacs

- docs/docs/usage/dependency.md
- news/1704.feature.md
- src/pdm/cli/actions.py
- src/pdm/cli/commands/add.py
- src/pdm/cli/commands/export.py
- src/pdm/cli/commands/install.py
- src/pdm/cli/commands/lock.py
- src/pdm/cli/commands/remove.py
- src/pdm/cli/commands/sync.py
- src/pdm/cli/commands/update.py
- src/pdm/cli/filters.py
- src/pdm/cli/options.py
- src/pdm/cli/utils.py
- src/pdm/project/lockfile.py
- src/pdm/project/project_file.py
- src/pdm/pytest.py
- tests/cli/test_add.py
- tests/cli/test_install.py
- tests/cli/test_list.py
- tests/cli/test_lock.py
- tests/cli/test_others.py
- tests/cli/test_remove.py
- tests/cli/test_update.py
- tests/conftest.py
- tests/test_formats.py
- tests/test_signals.py
- tests/test_utils.py
> feat: encode selected groups into lockfile

- news/1735.doc.md
- src/pdm/utils.py
~~- [ ] Test cases added for changed code.~~ (current tests do not cover `venv activate` without `env`)
For in project venv created by `conda`, using `pdm venv activate` without specifying `env_name` would be a failure:
```bash
(base) programripper:~/conda-test$ echo $CONDA_PREFIX  # Actually it is quite common for conda that isn't installed normally (e.g. via pyenv) that not to have CONDA_PREFIX properly set, which will make pdm fail faster.
/home/programripper/.pyenv/shims/conda
(base) programripper:~/conda-test$ pdm venv list
Virtualenvs created with this project:
*  in-project: /home/programripper/conda-test/.venv
(base) programripper:~/conda-test$ cat .pdm.toml
[venv]
backend = "conda"
[python]
path = "/home/programripper/conda-test/.venv/bin/python"
(base) …
```
> fix: in project conda venv activate without argument

- news/1752.bugfix.md
- news/1757.bugfix.md
- src/pdm/resolver/providers.py
> Fix the resolution order to prefer the packages causing the conflict

- news/1765.bugfix.md
- src/pdm/models/requirements.py
- tests/models/test_candidates.py
- tests/models/test_requirements.py
> fix: improve the error message when encountering an invalid requirement

- src/pdm/cli/actions.py
Unlike other shells which use the `:` as the delimiter, fish will not add a zero-length element to the end of the list if the variable in the command was not set. Thus, it will not cause the issue described in #410.
> fix: no need to check `PYTHONPATH` before setting it in fish

- news/1784.dep.md
- pdm.lock
- pyproject.toml
- src/pdm/installers/installers.py
> dep: Update installer to 0.7.0 to enable RECORD validation

- news/1749.feature.md
- src/pdm/cli/actions.py
- tests/cli/test_init.py
> feat: write .pdm-python to .gitignore when running pdm init

- news/1796.bugfix.md
- src/pdm/cli/actions.py
- src/pdm/cli/filters.py
> fix: do not validate against locked groups in lock command

- news/1800.bugfix.md
- src/pdm/cli/commands/fix/fixers.py
Avoid possible duplicate .pdm-python entries in .gitignore.
Fixes #1800
> fix: avoid duplicate .pdm-python in .gitignore.

- docs/docs/usage/venv.md
- news/1705.feature.md
- src/pdm/cli/actions.py
- src/pdm/cli/commands/add.py
- src/pdm/cli/commands/info.py
- src/pdm/cli/commands/install.py
- src/pdm/cli/commands/list.py
- src/pdm/cli/commands/remove.py
- src/pdm/cli/commands/run.py
- src/pdm/cli/commands/show.py
- src/pdm/cli/commands/sync.py
- src/pdm/cli/commands/update.py
- src/pdm/cli/commands/use.py
- src/pdm/cli/commands/venv/__init__.py
- src/pdm/cli/commands/venv/activate.py
- src/pdm/cli/commands/venv/remove.py
- src/pdm/cli/commands/venv/utils.py
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- src/pdm/cli/options.py
- src/pdm/cli/utils.py
- src/pdm/core.py
- src/pdm/project/core.py
- tests/cli/test_list.py
- tests/cli/test_others.py
- tests/cli/test_use.py
> feat: New option `--venv VENV` to run a command in the venv with the given name

- src/pdm/cli/commands/init.py
I have updated the prompt text for the init command to avoid confusion between asking about library creation and asking additional questions. 
Closes #1824
> chore: improve clarity of prompt in the init command

- news/1847.bugfix
- src/pdm/cli/completions/pdm.zsh
Fixed #1847 by replacing the brackets in the option descriptions with parentheses.
> fix: fixed zsh completions by replacing brackets in option descriptions

- news/1854.feature.md
- src/pdm/cli/commands/info.py
- src/pdm/cli/commands/run.py
- tests/cli/test_others.py
- tests/cli/test_run.py
This PR adds a `--json` option (exclusive with other options) to `info` and `run` commands in order to dump those data as JSON.
On my current `pdm` workspace, it give those results
```json
{
"complete": {
"name": "complete",
"kind": "call",
"help": "Create autocomplete files for bash and fish",
"args": "tasks.complete:main"
},
"doc": {
"name": "doc",
"kind": "shell",
"help": "Start the dev server for doc preview",
"args": "cd docs && mkdocs serve"
},
"lint": {
"name": "lint",
"kind": "cmd",
"help": "pre-commit run --all-files",
"args": "pre-commit run --all-files"
},
"pre_release": {
"name": "pre_release",
"kind": "cmd",
"help": "python tasks/max_versions.py",
"args": "python tasks/max_versions.py"
},
"release": {
"name": "release",
"kind": "cmd",
"help": "python tasks/release.py", …
```
> feat(commands): added a `--json` option to `info` and `run` command

- docs/docs/reference/cli.md
- src/pdm/cli/commands/base.py
- src/pdm/cli/commands/build.py
- src/pdm/cli/options.py
- src/pdm/cli/utils.py
- src/pdm/core.py
Improve cli reference display by:
- fixes dunders being rendered as bold markdown
- adds the missing spaces before `(default:` or `[env var`
- monospace some known reccuring references (`pyproject.toml`, `pdm.lock`, `.pdm-python`, `:all`, `:pre` and `:post`)
- apply the same casing to all help messages (Title)
- use the same format for all env vars
- use the same format (backticked) for parameters in help
> doc(cli): improve cli reference display

- docs/docs/usage/scripts.md
- news/1855.feature.md
- src/pdm/cli/commands/run.py
- tests/cli/test_run.py
This PR is considering the tasks with a name starting with an underscore as internal tasks (helpers for composite...) and hide them from the listing.
> feat(scripts): hide tasks starting with an underscore from listing

- src/pdm/cli/actions.py
- src/pdm/cli/commands/init.py
- src/pdm/project/core.py
- src/pdm/project/lockfile.py
- src/pdm/project/project_file.py
When running `pdm init -n`(non-interactive mode), a venv will be created by default. Previously, the selected Python will be used under PEP 582 mode.
> feat: create venv when running pdm init -n

- news/1866.bugfix.md
- pyproject.toml
- src/pdm/cli/actions.py
- src/pdm/cli/commands/init.py
- src/pdm/cli/commands/venv/__init__.py
- src/pdm/cli/commands/venv/activate.py
- src/pdm/cli/commands/venv/list.py
- src/pdm/cli/commands/venv/remove.py
- src/pdm/cli/commands/venv/utils.py
- src/pdm/cli/utils.py
- src/pdm/environments/python.py
- src/pdm/models/candidates.py
- src/pdm/models/python.py
- src/pdm/models/venv.py
- src/pdm/project/core.py
- src/pdm/utils.py
- tests/cli/test_init.py
- tests/test_project.py
> refactor: Extract the logic about virtualenv to its own module

- news/1890.feature.md
- src/pdm/models/repositories.py
- src/pdm/pytest.py
- tests/cli/test_lock.py
> feat: allow self-referencing groups in dev-dependencies

- news/1915.fix.md
- src/pdm/installers/installers.py
- src/pdm/installers/uninstallers.py
- src/pdm/termui.py
Running the test suite with warnings enabled generates a large number of warnings because of open file descriptors. This PR closes the two offending file handles and also a few others found in the same code files. ~~Two~~ Four warnings remain, one of which is outside this project's control.
> Fix a number of `ResourceWarning`s when running the test suite

- docs/docs/usage/dependency.md
Small edit to the docs explicitly indicating that you can install deps straight from a URL. Reading the section on VCS deps it wasn't obvious to me that any HTTP(s) url works fine with pdm.
> Document ability to install deps from a plain URL

- news/1935.bugfix.md
- src/pdm/formats/poetry.py
> fix: add pakcage without peotry config [tool.poetry.build] script would raise keyError

- news/1869.bugfix.md
- src/pdm/cli/commands/install.py
- src/pdm/installers/core.py
- src/pdm/installers/synchronizers.py
> fix: don't use install cache when installing build requirements to avoid race condition

- docs/docs/usage/advanced.md
- news/1947.doc.md
I changed the `Dockerfile` in the multi stages exemple to use `pdm sync` instead of `pdm install --no-lock`. Unless I am missing something both command do the same result but `pdm sync` seems to me to be the idomatic way, as described in [the doc](https://pdm.fming.dev/latest/usage/dependency/#install-the-packages-pinned-in-lock-file).
> fix(docs): use `pdm sync` instead of `pdm install --no-lock`

- news/1928.feature.md
- src/pdm/cli/commands/publish/__init__.py
- src/pdm/cli/commands/publish/repository.py
Closes #1928 
Add ability to skip SSL verification for publish repositories via `repository.custom.verify_ssl` config option.
> Add repository config verify ssl

- news/1971.feature.md
- pdm.lock
- pyproject.toml
- src/pdm/models/caches.py
- src/pdm/models/session.py
Supersedes #1498, rather than rebasing. This adds support for using a split-body. In the current single-body cache, each file in the HTTP cache contains two different fragments: the serialized HTTP response, followed by the HTTP body data. This means that when response headers change (including timestamps), the whole cache object is rewritten to disk.
With this change the body is not written again, reducing disk pressure. 
This change is compatible with existing caches, to the best of my ability to test it. However; it completely prevents running an older PDM against a new cache. In that case, the body in the file is "None" and the deserialization breaks. Not sure if there's a great workaround.
> add support for SplitBodyCache

- news/1970.bugfix.md
- src/pdm/formats/requirements.py
- src/pdm/models/repositories.py
- src/pdm/models/requirements.py
- tests/test_formats.py
> fix: guess name from the VCS url when importing requirements (#1970)

- docs/docs/reference/pep621.md
I added the suggestion from @mforbes in https://github.com/pdm-project/pdm/issues/1773#issuecomment-1475479530 (and added them as a co-author using the name and description on their GitHub profile).
> Add notes about Python version and license classifiers

- news/1995.bugfix.md
- src/pdm/models/in_process/__init__.py
- src/pdm/models/in_process/parse_setup.py
> fix: parsing setup.py error if it outputs to stdout

- news/1997.feature.md
- src/pdm/cli/commands/export.py
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- src/pdm/formats/requirements.py
- src/pdm/models/backends.py
- tests/test_formats.py
> feat: add option to expand vars when exporting

- .github/workflows/ci.yml
See https://docs.python.org/3/library/devmode.html. This helps to detect issues like #1988 earlier.
The title and commit message say it.
I‘m using this setting in CI pipelines everywhere and I have only good experiences with it.
(Please explain whether the two checklist items need completion in this case.)
> Use `PYTHONDEVMODE=1` for CI

- src/pdm/cli/commands/publish/package.py
- src/pdm/models/working_set.py
- tests/models/test_setup_parsing.py
Close file handles. Attempt to fix e.g., these warnings.
```console
$ pdm lock --production
python.use_venv is on, creating a virtualenv for this project...
/usr/lib/python3.11/subprocess.py:1127: ResourceWarning: subprocess 76 is still running
_warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.11/subprocess.py:1127: ResourceWarning: subprocess 75 is still running
_warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.11/subprocess.py:1127: ResourceWarning: subprocess 77 is still running
_warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback …
```
> Close IO objects

- news/2042.feature.md
- src/pdm/cli/commands/venv/__init__.py
- tests/cli/test_venv.py
Add `--project` option to `pdm venv` to support another path as the project root.
Closes #2042
> feat: add `--project` option to `pdm venv`

- news/2057.bugfix.md
- src/pdm/cli/commands/publish/package.py
> fix: do not normalize name when uploading

- news/2060.bugfix.md
- src/pdm/cli/commands/update.py
> fix: lock hooks emitted with dry_run=True when doing update

- news/2062.bugfix.md
- src/pdm/cli/commands/install.py
- src/pdm/cli/templates/__init__.py
- src/pdm/installers/core.py
- src/pdm/installers/synchronizers.py
- src/pdm/resolver/core.py
> fix: install --plugins cannot install self package

- news/2064.bugfix.md
- src/pdm/models/caches.py
> fix: The cache collision issue between named requirements and url requirements

- docs/docs/usage/advanced.md
See https://github.com/wntrblm/nox/issues/711
`session.run_always` works more similarly to `session.install`.
Changed `session.run` to `session.run_always` for installing dependencies on Nox example.
> docs: fix Nox install command

- docs/docs/usage/advanced.md
Improve documentation by adding instructions to copy executables in example Dockerfile in the advanced section.
> Add instructions to copy executables in example Dockerfile

- news/2081.feature.md
- src/pdm/core.py
- tests/cli/test_run.py
As issue #2081 described, pdm will display the help information with exit code 0 when running directly.
> feat: display the help information when running pdm directly

- news/2083.bugfix.md
- src/pdm/core.py
* Separate the use cases for CLI and API
* for CLI usage, pass `args or sys.argv[1:]` as `args` to Core
* for API usage, use `[]` instead of `sys.argv[1:]` as default value of `args`, if `args` is `None`
> fix: avoid mistakenly passing command-line arguments while testing

- news/2086.bugfix.md
- src/pdm/cli/commands/install.py
> fix: don't overwrite lockfile when locking in `pdm install`

- news/2102.bugfix.md
- src/pdm/core.py
- src/pdm/models/specifiers.py
- tests/models/test_candidates.py
- tests/models/test_requirements.py
- tests/models/test_specifiers.py
> fix: tolerate local version in specifiers

- src/pdm/cli/commands/cache.py
- src/pdm/cli/commands/self_cmd.py
- src/pdm/cli/commands/venv/__init__.py
- src/pdm/cli/utils.py
- src/pdm/core.py
- tests/cli/test_run.py
Improve help info format for subcommands. 
* Set `metavar` to empty for subparsers
* Remove extra line breaks and indent block when action_help is empty
* Remove extra continuous spaces in usage info
By the way, it also fixed the help info difference for older Python version.
> doc: improve help info format for subcommands

- pyproject.toml
Hello.
Thank you very much for PDM, incredible work, much appreciated here.
We are considering recommending PDM for the whole company, but we would *very much* need our contributors being able to install PDM "the right way" (meaning: with keyring included from the start) in one go, simply (and not having to run `pip install keyring` or `pipx inject pdm keyring` afterward), because we really value the password being stored in a safe way. And what comes with the `all` optional dependencies really looks irrelevant and cumbersome for our use case.
We think `keyring` is a very, very import dependency. For comparison, Poetry made it mandatory.
If you think it's worth an entry in the NEWS file, I will fill one.
Thank you very much.
> add optional keyring dependency target in pyproject.toml

- news/2120.bugfix.md
- src/pdm/models/repositories.py
- src/pdm/resolver/providers.py
- tests/fixtures/projects/demo-package/requirements.txt
- tests/fixtures/projects/demo-package/requirements_simple.txt
> fix: correct the comparison of candidate keys

- news/2163.feature.md
- pyproject.toml
- src/pdm/cli/commands/init.py
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- src/pdm/cli/templates/__init__.py
> feat: add an --overwrite option to pdm init

- news/2169.bugfix.md
- src/pdm/installers/synchronizers.py
> fix: pdm does not update a `@ file:///` dependency

- news/2175.bugfix.md
- src/pdm/resolver/providers.py
> fix: crash issue when dependencies are requested out of python range

- news/2182.bugfix.md
- src/pdm/utils.py
- tests/test_utils.py
This will complete the attribute editing procedure.
It makes `comarable_version("1.2.3+local1") == Version("1.2.3")` which is not achievable now.
> Fix comparable_version()

- news/2187.bugfix.md
- src/pdm/cli/commands/venv/activate.py
- tests/cli/test_venv.py
Now, if `pdm venv activate` fails to identify the shell (as it did with my zsh setup) it will use the default behavior instead of crashing.
Fixes #2187
> Fix shell detection failure

- src/pdm/models/caches.py
I'm writing tests for `caches.py`, and I find that using `str` directory path is more convenient.
> Fix cach file path's type to Path | str

- news/2195.feature.md
- pdm.lock
- pyproject.toml
> fix: Switch to Truststore by default

- README.md
Closes #2204.
~~- [ ] A news fragment is added in `news/` describing what is new.~~
~~- [ ] Test cases added for changed code.~~
Update to README.
> doc: Update comparison with hatch in README

- README.md
- docs/docs/usage/project.md
~~- [ ] A news fragment is added in `news/` describing what is new.~~
~~- [ ] Test cases added for changed code.~~
Corrected a typo in project.md.
Added change to commit #2210 requested by @pawamoy after review.
> doc: Correct a typo in project.md

- news/2217.feature.md
- src/pdm/cli/commands/run.py
- tests/cli/test_run.py
> feat: Allow using `pdm run` to run a command not on PATH

- news/2216.feature.md
- src/pdm/environments/python.py
- src/pdm/installers/synchronizers.py
- src/pdm/models/venv.py
- src/pdm/models/working_set.py
- src/pdm/pytest.py
> feat: Consider packages installed if the venv includes them from the system-site

- news/2222.feature.md
- src/pdm/cli/utils.py
- src/pdm/formats/setup_py.py
- src/pdm/models/in_process/parse_setup.py
> feat: support converting setup.cfg without existing setup.py

- docs/docs/usage/advanced.md
`isolated_build` is [the default since tox 4](https://tox.wiki/en/latest/upgrading.html#isolated-environment-on-by-default) Tox 4.0.0 was released on [2022-12-07](https://tox.wiki/en/latest/changelog.html#v4-0-0-2022-12-07).
> remove "isolated_build" tox option in docs

- news/2236.bugfix.md
- src/pdm/models/venv.py
If using (a `pip install`'ed) `pdm` with a Python from the [MSYS2 project](https://www.msys2.org/), sometimes it is possible for `pdm` to fail to find the `python` binary in a freshly-created `virtualenv`:
```
William@DESKTOP-3H1DSBV MINGW64 ~/Projects/FPGA/amaranth/template-fpga
$ pdm install -v
STATUS: Resolving packages from lockfile...
The saved Python interpreter doesn't match the project's requirement. Trying to find another one.
python.use_venv is on, creating a virtualenv for this project...
Cleaning existing target directory C:/msys64/home/William/Projects/FPGA/amaranth/template-fpga/.venv
Run command: ['C:/msys64/mingw64/bin/python.exe', '-m', 'virtualenv',
'C:/msys64/home/William/Projects/FPGA/amaranth/template-fpga/.venv', '-p', 'C:/msys64/mingw64/bin/python.EXE', …
```
> Accommodate virtual envs on Windows that use Unix path hierarchy.

- docs/docs/usage/advanced.md
- docs/docs/usage/project.md
Fix two typos in the documentation.
> doc: correct spelling

- news/2261.bugfix.md
- src/pdm/resolver/providers.py
- src/pdm/resolver/reporters.py
- tests/resolver/test_resolve.py
> fix: PDM crashes in case of invalid package metadata

- news/2230.bugfix.md
- src/pdm/cli/commands/install.py
- src/pdm/cli/commands/sync.py
- src/pdm/cli/commands/update.py
> fix: revert the change of install self

- docs/docs/index.md
> mention that all `pdm` commands need to be run with the `pw` wrapper when installing with the "inside project" method

- news/2282.venv-clean.md
- src/pdm/cli/commands/venv/backends.py
> fix: empty venv instead of remove it

- docs/docs/usage/advanced.md
Neither required - this is fixing a typo.
The monorepo docs under "advanced usage" have a typo in the example - `[projects]` should be `[project]`.
> [project] not [projects] for monorepo usage docs

- src/pdm/cli/commands/init.py
Seems like click of cookiecutter has changed to return None instead of 0
Seems like click of cookiecutter has changed to return None instead of 0
> Cookiecutter raising exception instead of returning errcode

- docs/docs/usage/config.md
Docs separate private pypi password and url with slash but should be a @ sign.
> Separate private pypi password with @ instead of slash

- docs/docs/usage/venv.md
Without specifying the `in-project` name:
> pdm use: error: argument --venv: expected one argument
> docs: fix `pdm use` example for in-project venv

- docs/docs/usage/venv.md
This is how current markup is rendered:
I think that this is not the intention. And the intention is to have a thrid tab with "Fish".
> Fix `venv.md` markup

- docs/docs/usage/config.md
- news/1645.feature.md
- src/pdm/_types.py
- src/pdm/models/repositories.py
- tests/test_project.py
> feat: per-package source configuration

- news/2328.feature.md
- src/pdm/installers/synchronizers.py
- src/pdm/models/candidates.py
- src/pdm/models/reporter.py
> feat: report progress when downloading packages

- src/pdm/cli/options.py
- src/pdm/project/lockfile.py
See commits for details. This PR introduces no functional change.
> Minor UI fixes for the new lock strategy arguments

- news/2330.bugfix.md
- src/pdm/project/config.py
> fix: Global repository setting results in TypeError

- news/2333.bugfix.md
- pdm.lock
- pyproject.toml
- src/pdm/models/auth.py
> fix: Credentials error when working with 2 indices on the same host

- news/2337.bugfix.md
- src/pdm/builders/base.py
> fix: check list for empty build error output

- news/2342.bugfix.md
- src/pdm/formats/requirements.py
- tests/test_formats.py
Fix issue with find-links being exported as `--extra-index-url`.
Closes #2342
> Export find-links correctly

- docs/docs/reference/pep621.md
Just link to the `pdm-backend` documentation, I guess most users are using the default backend.
Related issue: https://github.com/pdm-project/pdm/issues/2089
> doc: fix the invalid dynamic versioning link

- news/2292.bugfix.md
- src/pdm/cli/commands/run.py
- [ x] A news fragment is added in `news/` describing what is new.
- [ -] Test cases added for changed code.
Updated the signal used to interrupt a process (CTRL-C pressed) on windows.
Tested with the following python script as adding a test case is not practical.
Verification:
1. Run the script. "pdm run test.py"
2. Enter CTRL-C : Script is terminated
3. Run the script. "pdm run test.py"
4. Enter CTRL-C : Script is terminated
Without the pull request step 4 will not terminante the process.
```python
from time import sleep
print(1)
while True:
print(".", end="", flush=True)
sleep(1)
```
> fix: Subprocess signal forwarding on Windows

- .pre-commit-config.yaml
- install-pdm.py
- pyproject.toml
- src/pdm/compat.py
- src/pdm/formats/poetry.py
- src/pdm/models/candidates.py
- src/pdm/models/repositories.py
- tests/cli/test_install.py
- tests/cli/test_use.py
Ruff released its formatter, it is very close to the Black code style but is 30x faster.
https://astral.sh/blog/the-ruff-formatter
> feat: use ruff-format replace black

- news/2379.bugfix.md
- src/pdm/cli/templates/__init__.py
- tests/cli/test_template.py
When installing PDM through Nix (and other package managers with read-only file permissions) copying template permissions results in files which can't be used without chmod'ing them back to having write permissions.
It's best that we just create the files as the user copying them with default permissions.
Before:
```
$ pdm init
$ ls -la
total 16
drwx------  6 adisbladis users  200 Nov  8 12:47 .
drwxrwxrwt 56 root       root  1580 Nov  8 12:49 ..
-r--r--r--  1 adisbladis users 3102 Jan  1  1970 .gitignore
-rw-r--r--  1 adisbladis users   36 Nov  8 12:47 .pdm-python
drwxr-xr-x  2 adisbladis users   40 Nov  8 12:47 __pycache__
-rw-r--r--  1 adisbladis users  215 Nov  8 12:47 pyproject.toml
-r--r--r--  1 adisbladis users   18 Jan  1  1970 README.md
drwxr-xr-x  3 adisbladis users   60 Nov  8 …
```
> fix: Don't copy file permissions for templates

- news/2378.bugfix.md
- src/pdm/installers/installers.py
> fix: PDM does not detect namespace packages correctly

- news/2388.bugfix.md
- src/pdm/cli/actions.py
- src/pdm/cli/commands/import_cmd.py
> fix: Don't reset the build backend when asking for import

- news/2394.feature.md
- src/pdm/cli/actions.py
- src/pdm/cli/commands/add.py
- src/pdm/cli/commands/init.py
- src/pdm/cli/commands/show.py
- src/pdm/cli/utils.py
- src/pdm/models/repositories.py
- src/pdm/project/core.py
- src/pdm/resolver/core.py
- tests/cli/test_init.py
- tests/test_signals.py
> feat: add a new setting `package-type` to distinguish application and library

- news/2390.bugfix.md
- src/pdm/cli/commands/export.py
We now use a regular print to avoid any formatting of the export command output.
Closes #2390
> fix: Never wrap the output of the `export` command

- news/2360.bugfix.md
- src/pdm/cli/commands/init.py
- src/pdm/utils.py
Fix bugs mentioned in https://github.com/pdm-project/pdm/issues/2360, do some check before init a project, follow [PEP 426](https://peps.python.org/pep-0426/#name) and sanitize the default name by replacing the illegal characters
> Issues 2360 (#1)

- news/2409.bugfix.md
- src/pdm/project/core.py
> fix: forbid global project in conda base env

- news/2400.feature.md
- src/pdm/cli/commands/publish/__init__.py
Debugging the issue described in #2399 was hard, since PDM didn't provide the very helpful response body
`{"message":"Validation failed: Description is too long (maximum is 4000 characters)"}`. For some reason, capturing the traffic also didn't work out for me. And resorting to that would require much expertise from users.
This enhancement improves things in a straightforward, but simplistic manner. Ideal would be the ability to log all (structured) API endpoint response data to stdout throughout PDM. That would require more investment and architectural redesign.
> Provide response body upon HTTP fault with publish

- docs/docs/usage/scripts.md
- news/2408.feature.md
- src/pdm/cli/commands/run.py
- tests/cli/test_run.py
- Only found a single meaningful test-case -- I tried to do some more testing for the interpolation but it got far too complex with paths, dev versions etc.  
As discussed on Discord, this adds support for using a `{pdm}` placeholder in scripts to refer to the current interpreter. I'm not sure if this should affect calls in any way, but I don't think so since they'd (presumably) use the same python interpreter/venv.
> add support for `{pdm}` placeholder in scripts

- news/2418.feature.md
- pdm.lock
- pyproject.toml
- src/pdm/cli/actions.py
- src/pdm/cli/commands/export.py
- src/pdm/cli/commands/run.py
- src/pdm/cli/utils.py
- src/pdm/formats/pipfile.py
- src/pdm/formats/poetry.py
- src/pdm/formats/requirements.py
- src/pdm/models/candidates.py
- src/pdm/models/markers.py
- src/pdm/models/repositories.py
- src/pdm/models/requirements.py
- src/pdm/models/setup.py
- src/pdm/pytest.py
- src/pdm/resolver/core.py
- src/pdm/resolver/graph.py
- tests/fixtures/projects/demo-package-has-dep-with-extras/requirements.txt
- tests/models/test_candidates.py
- tests/models/test_marker.py
- tests/models/test_requirements.py
- tests/resolver/test_resolve.py
- tests/test_formats.py
> feat: export cross-platform requirements

- src/pdm/cli/actions.py
- src/pdm/cli/commands/lock.py
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- src/pdm/models/repositories.py
- tests/cli/test_lock.py
> feat: add `--update-reuse` to lock command

- news/2422.bugfix.md
- src/pdm/formats/requirements.py
When the requirements parser encountered a `-r` requirements path reference it would pass the line directly to `open`, whereas under pip (I was importing a requirements project when encountered this) the `-r` references are resolved relative to the file in which they are specified. 
This diff changes the behaviour to resolve the file relative to where it was specified, rather than the current working directory.
> fix: resolve requirements paths relative to the requirement file they are specified in

- news/1910.feature.md
- src/pdm/cli/commands/export.py
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- src/pdm/formats/requirements.py
- tests/cli/test_others.py
- tests/test_formats.py
> feat: allow to include self when exporting to requirements

- news/2423.bugfix.md
- src/pdm/installers/installers.py
- src/pdm/installers/manager.py
- src/pdm/installers/synchronizers.py
- src/pdm/installers/uninstallers.py
- src/pdm/pytest.py
> fix: inplace update

- news/2442.bugfix.md
- src/pdm/models/candidates.py
- src/pdm/models/repositories.py
- src/pdm/utils.py
> fix: Link collection ignores package-index-binding

- docs/docs/usage/project.md
> docs: Clarify effect of requires-python on resolution

- src/pdm/termui.py
`UI.echo` docstring default verobsity level was wrong. it was changed in [#2304](https://github.com/pdm-project/pdm/pull/2304/files#diff-731843a62f3036f02e987fb915be5c721aaad5010b252aa88383dd7184dafb11R180)
However, I am bit skeptical: shouldn't the default level be `NORMAL`?
> fix default verbosity level in UI.echo docstring

- news/2464.bugfix.md
- src/pdm/environments/base.py
- src/pdm/models/in_process/__init__.py
> fix: PDM installs wrong architecture of pywin32 wheel on Windows

- news/2466.bugfix.md
- src/pdm/installers/installers.py
I have the following, very specific setup:
```
foo-bar:
foo/
bar/
__init__.py
foo-baz:
foo/
baz.cpython-39-x86_64-linux-gnu.so
baz/
__init__.pyi
```
The `foo-bar` dependency provides a normal python module `foo.bar` inside a namespace package `foo`.
The `foo-baz` dependency provides an extension module `foo.baz` along with type stubs (`.pyi`), also inside namespace `foo`.
PDM currently mishandles those when installing with symlink support:
```
PDMWarning: Overwriting existing package: [...]
```
That's because the logic for installing namespace packages doesn't mark `foo/` in the `foo-baz` dependency as a namespace package since it not being a package at all:
https://github.com/pdm-project/pdm/blob/82a45743f0025322a155e8f5cb5af0aa6189c3a7/src/pdm/installers/installers.py#L97-L101 …
> fix: Fix installing PEP 561 stub-only packages

- docs/docs/usage/advanced.md
Simply updated the docs to remove any references to an export to `setup.py`, since this is not supported.
I did not make a news fragment because it did not seem worthy to do that, and no test cases are needed.
> Update docs to remove export to `setup.py` information since that is not supported

- news/2480.feature.md
- src/pdm/cli/utils.py
- tests/cli/test_utils.py
When passing unrecognized arguments to a pdm subcommand, pdm displays its own help info instead of the subcommand's one. It would be more helpful for users if pdm could display the help info of the subcommand.
This issue is caused by a known design of Python's argparse module, and the argparse module is not planning to improve it. (Refs: https://github.com/python/cpython/issues/83287 )
I found a modification on Stackoverflow, which I tried and found to be effective. (Refs: https://stackoverflow.com/a/61724607 )
> feat: Show subcommand's help info when passing unrecognized arguments

- docs/docs/reference/configuration.md
- news/2485.feature.md
- src/pdm/project/config.py
I made `cache_dir`configurable through an environment variable. Some CI impose some restriction on the location of what can be cached. For example, Gitlab CI mandates that the cache directory be a children of the build directory. And `pdm config cache_dir` is hardly usable when you have a big CI configuration where many blocs override each others.
I saw the `$HOME` tricks recommended by the env var but I think it would break our code base.
> add a `PDM_CACHE_DIR` environment variable

- docs/docs/usage/dependency.md
- news/0.doc.md
Simply fixed a typo in an example of `pdm list`.
The `license` field doesn't exist, it should be `licenses`.
> docs: Fix typo in usage example

- news/0.doc.md
- news/2495.bugfix.md
- src/pdm/resolver/providers.py
> fix: pdm update --update-eager can hit InconsistentCandidate error when dependency is included both through default dependencies and extra

- news/2502.bugfix.md
- src/pdm/installers/installers.py
This PR ensure that `pdm` does not raise warning on `install`/`update` for symlinks it created himself when cache is enabled.
Fixes #2502
> fix(installers): don't warn when overwriting its own symlink on `install` with cache enabled (fixes #2502)

- docs/docs/index.md
- docs/docs/usage/project.md
Drop references to Python 3.7 in docs/ files. I was reading the index page on `pdm-project.org/latest` when I noticed that some vestigial references to Python 3.7 were still hanging around after the `2.11.0` release.
There's also #2494, but it looks like that PR doesn't touch these files, only `ci.yml`.
> Update references to Python 3.7 in `docs/`

- src/pdm/models/repositories.py
Closes #2522.
- ~~[ ] A news fragment is added in `news/` describing what is new.~~ N/A
- ~~[ ] Test cases added for changed code.~~ N/A (?)
As discussed in #2522, the warning message is a bit misleading because the installation proceeds correctly, so this PR modifies the message to reflect that.
> chore(lib): enhance warning message

- news/2538.bugfix.md
- src/pdm/cli/commands/list.py
- tests/cli/test_list.py
The full license string can sometimes be contained inside the package metadata license field, for example:
`license = { file="LICENSE" }` in pyproject.toml
This has been fixed by checking for the presence of newlines in the `license` variable, or if it is larger than 50 chars (slightly more than the longest OSI license field).
The tests have been updated.
Note that when exporting the markdown file that contains all the licenses (and full text) the full text license is still not exported.  This is because it will always look inside: `locations = ("**/LICENSE*", "**/LICENCE*", "**/COPYING*", "**/NOTICE*")`
Closes https://github.com/pdm-project/pdm/issues/2538
```
╭────────────────────────────┬────────────────────────────────┬─────────────────────────────────────────────────────────────────── …
```
> Fixed pdm list output containing full license text in some cases

- docs/docs/usage/config.md
- docs/docs/usage/dependency.md
- news/1316.bugfix.md
- news/1316.feature.md
- src/pdm/environments/__init__.py
- src/pdm/environments/base.py
- src/pdm/exceptions.py
- src/pdm/installers/core.py
- src/pdm/models/environment.py
- src/pdm/project/core.py
- src/pdm/project/project_file.py
- src/pdm/resolver/providers.py
- tests/resolver/test_resolve.py
> feat: Allow exclusion of dependencies

- docs/docs/usage/config.md
- docs/docs/usage/dependency.md
- news/2552.feature.1.md
- news/2552.feature.2.md
- news/2552.feature.3.md
- src/pdm/cli/commands/add.py
- src/pdm/cli/commands/update.py
- src/pdm/cli/options.py
- src/pdm/formats/pipfile.py
- src/pdm/models/requirements.py
- src/pdm/project/core.py
- src/pdm/project/project_file.py
- src/pdm/resolver/providers.py
- tests/cli/test_update.py
- tests/resolver/test_resolve.py
- tests/test_formats.py
> feat: allow prereleases if a prerelease version is pinned for a specific package

- news/2560.bugfix.md
- src/pdm/environments/base.py
Set `index_urls` and `find_links` when init finder. Fix #2560
> fix: don't use pypi.org when pypi.url is set

- docs/docs/usage/publish.md
I have updated docs s.t. the github actions workflow example in the `Build and Publish` page would work for private repositories.
The reason it would previously not work is because settings of 
```yaml
permissions:
id-token: write
```
would overwrite the default which is 
```yaml
permissions:
contents: read
```
which results in a checkout fail.
See: actions/checkout#254 (not the issue itself, but the explanation here https://github.com/actions/checkout/issues/254#issuecomment-1603109591)
> fix: updates instructions for private repositories in pdm publish.

- src/pdm/cli/commands/fix/fixers.py
- src/pdm/environments/base.py
- src/pdm/environments/local.py
- src/pdm/environments/python.py
- src/pdm/installers/installers.py
> fix: install headers into package namespace

- src/pdm/project/core.py
> perf: Warnings that the correct version cannot be matched before the environment is finally created.

- news/2586.bugfix.md
- src/pdm/resolver/providers.py
- tests/resolver/test_resolve.py
> fix: unable to force install specific version with pdm

- pdm.lock
- pyproject.toml
Updated unearth dependency to version 0.14.0 to prevent pdm from hanging indefinitely when pypi.org is resolved but all other packets (i.e. non-DNS packets) are dropped.  
After investigation of issue #2183, we found that the problem was caused by the unearth package. However, it was solved in v. 0.14.0, specifically in commit [1d9a2dc](https://github.com/frostming/unearth/commit/1d9a2dc5279df60a9d3abda81af9a83590a80096). Therefore, this PR simply updates the unearth dependency to version 0.14.0. 
Closes #2183
> Fix #2183 no timeout for PyPI calls

- news/2398.feature.md
- pyproject.toml
- src/pdm/builders/base.py
- src/pdm/core.py
- src/pdm/installers/synchronizers.py
- src/pdm/models/caches.py
- src/pdm/models/candidates.py
- src/pdm/project/config.py
- src/pdm/pytest.py
- src/pdm/termui.py
- tests/models/test_candidates.py
- tests/test_project.py
> feat: Allow configuring log file directory

- docs/docs/usage/scripts.md
- src/pdm/cli/commands/run.py
- tests/cli/test_run.py
New option introduced that changes the behavior of composite script to executes all the scripts despite to present errors. Exit code is sum of all the codes.  The name of the option 'keep_going' is inspired/reused from 'GNU make' with similar/same purpose.
> An option to run full composite despite to errors

- docs/docs/usage/scripts.md
- news/2620.feature.md
- src/pdm/cli/commands/run.py
- src/pdm/termui.py
- tests/cli/test_run.py
> fix: Add an option for PDM's scripts to set the current working directory

- news/2697.feature.md
- src/pdm/cli/commands/publish/repository.py
- src/pdm/environments/base.py
- tests/models/test_candidates.py
- tests/test_project.py
> feat: reuse request sesison within the environment

- news/2702.feature.md
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- src/pdm/cli/options.py
- src/pdm/core.py
- src/pdm/project/core.py
- tests/cli/test_add.py
> feat: allow disabling caches with `--no-cache` option or `PDM_NO_CACHE`

- pdm.lock
- pyproject.toml
- src/pdm/cli/commands/publish/__init__.py
- src/pdm/cli/commands/publish/repository.py
- src/pdm/environments/base.py
- src/pdm/models/caches.py
- src/pdm/models/candidates.py
- src/pdm/models/finder.py
- src/pdm/models/repositories.py
- src/pdm/models/session.py
- src/pdm/pytest.py
- tasks/max_versions.py
- tests/cli/conftest.py
- tests/cli/test_cache.py
- tests/cli/test_publish.py
- tests/conftest.py
- tests/test_project.py
> refactor: switch to httpx client

- news/2628.feature.md
- src/pdm/cli/commands/update.py
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- tests/cli/test_update.py
*copied from commit message*:
Add the `--allow-transitive` argument handler to the class `Command` and its `do_update` method in `update.py`.
Add logic for updating transitive dependencies in `update.py`. If the specified package is not in `pyproject.toml`, and the '--allow-transitive' flag is used, then try to match the package name with packages in the lock file instead. Ensures transitive dependencies are not written to `pyproject.toml`.
Add three tests for `--allow-transitive` flag.
Add shell completions for bash, fish, powershell and zshell.
Resolves #2628
> feat: allow updating specific sub-deps with `--allow-transitive` flag

- README.md
- README_zh.md
- docs/docs/index.md
- docs/docs/usage/project.md
- news/2721.feature.md
- pdm.lock
- pyproject.toml
- src/pdm/cli/commands/python.py
- src/pdm/cli/commands/use.py
- src/pdm/cli/commands/venv/backends.py
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- src/pdm/cli/options.py
- src/pdm/models/python.py
- src/pdm/project/config.py
- src/pdm/project/core.py
- src/pdm/pytest.py
- src/pdm/termui.py
- tests/cli/test_python.py
> feat: install python using pbs-installer

- docs/docs/usage/dependency.md
- docs/docs/usage/lockfile.md
- docs/mkdocs.yml
- news/2725.doc.md
- src/pdm/cli/utils.py
> doc: extract lockfile doc from "manage dependencies" doc

- news/2726.bugfix.md
- src/pdm/project/core.py
> fix: couldn't find interpreter for global project

- .pre-commit-config.yaml
Currently, codespell in pre-commit will fail as following even though corresponding ignorance is configured in `pyporject.toml`.  According to the documentation [1], to have the configuration in `pyproject.toml` take effect, we need to add `tomli` as `additional_dependencies`.
```shell
codespell................................................................Failed                                                                                                                       - hook id: codespell                                                                                                                                                                                  - exit code: 65
pyproject.toml:218: overriden ==> overridden
pyproject.toml:218: te ==> the, be, we, to …
```
> chore: config codespell with pyproject.toml

- news/2730.bugfix.md
- src/pdm/installers/synchronizers.py
- src/pdm/models/cached_package.py
- src/pdm/models/caches.py
- src/pdm/models/candidates.py
> fix: make the cache package path shorter to solve the windows path problem

- news/2665.bugfix.md
- src/pdm/formats/base.py
- src/pdm/formats/poetry.py
- tests/fixtures/pyproject.toml
- tests/test_formats.py
* Fix errors when parsing poetry format that contains special characters in author name (fixes #2665)
* Poetry-specific `parse_name_email` and `NAME_EMAIL_RE` moved from `pdm.formats.base` to `pdm.formats.poetry`.
> ensure poetry authors are parsed properly (fixes #2665)

- news/2747.bugfix.md
- src/pdm/installers/manager.py
- src/pdm/models/cached_package.py
- src/pdm/models/caches.py
- src/pdm/models/candidates.py
- tests/models/test_candidates.py
> fix: feat: add back `candidate.build()` for backward-compatibility

- news/2757.bugfix.md
- src/pdm/cli/commands/cache.py
> fix(cli): remove all caches like removing individual caches

- news/2779.bugfix.md
- src/pdm/project/core.py
- tests/test_project.py
PDM was unable to find Python interpreters as soon as `PDM_IGNORE_ACTIVE_VENV` was set.
This PR fixes it
Fixes #2779
> fix(venv): ensures that `PDM_IGNORE_ACTIVE_VENV` does not prevent finding an interpreter (fix #2779)

- news/2776.bugfix.md
- src/pdm/cli/commands/use.py
> fix(use): fix inconsistent logging when `pdm use` a different python interpreter

- news/2784.bugfix.md
- src/pdm/models/session.py
Fix #2784.
- Move the logic to update `session._trusted_host_ports` before checking the `pypi` source so the pypi source can also be trusted if necessary
- Check that `verify_ssl is False` before adding to the trusted host ports which seems in line with how things worked before pdm 2.13.3
I'm not familiar enough with this codebase to know how to properly add unit tests, but I did verify that `pdm sync` works with my custom pypi source after this change.
> fix: add all sources to trusted_hosts if verify_ssl is False

- news/2785.bugfix.md
- src/pdm/cli/commands/outdated.py
- src/pdm/utils.py
This should fix #2785
1. Wrap `normalize_name` for `project.name` before name checking.
2. Add `lru_cache` for `normalize_name` function. 
<del>but I am not sure whether this is the best solution.</del>
<del>The cached property `normalized_name` for `Project` is added as the `normalize_name()` need to be triggered for multiple times in the for-loop and there are several other existence of `normalize_name(project.name)` in the repo. If this is OK, a follow up would be change those `normalize_name(project.name)` to `project.normalized_name`.</del>
<del>Other possible options:</del>
<del>1. Use a local variable, e.g., `normalized_project_name`, before the for-loop and use it inside.</del>
<del>3. Add `@lru_cache` for `normalize_name()`. </del>
BTW, I wonder the reason to use the normalized …
> fix: name check for project itself in `pdm outdated`

- news/2788.bugfix.md
- src/pdm/models/session.py
> fix: proxy environment variables are not recognised by pdm anymore on windows

- news/2803.feature.md
- src/pdm/installers/installers.py
- src/pdm/installers/manager.py
- src/pdm/models/caches.py
- src/pdm/models/candidates.py
- src/pdm/pytest.py
- tests/cli/test_install.py
- tests/models/test_candidates.py
- tests/test_installer.py
> revert: don't cache the decompressed content of wheels unless being told so

- news/2799.bugfix.md
- src/pdm/cli/filters.py
- tests/cli/test_install.py
- tests/cli/test_lock.py
- tests/test_utils.py
Fix #2799
I am not sure this is by design, let me know if I misunderstood anything.
> fix: make `--without` respect groups in `dev-dependencies`

- news/2816.bugfix.md
- src/pdm/installers/manager.py
- tests/test_installer.py
This PR adds a test case for editable caching and ensure editable installations are not cached.
Fix #2816
> fix(installer): do not cache editable installs (fix #2816)

- docs/usage/lockfile.md
- news/2656.feature.md
- src/pdm/environments/base.py
- src/pdm/project/core.py
- tests/test_project.py
Allows defining package format preferences in project settings using:
- `tool.pdm.resolution.no-binary`
- `tool.pdm.resolution.only-binary`
- `tool.pdm.resolution.prefer-binary`
Accept both comma separated list or toml list.
Environment variable has precedence over project settings.
`Project` class gains 2 reusable helpers (for plugin writers):
- `env_or_settings()` to get a setting from env var or setting with env var precedence
- `env_or_settings_list()` doing the same for list (as comma separated or toml list)
Fixes #2656
> feat(lockfile): allows defining package format preferences in project settings (fix #2656)

- news/2829.bugfix.md
- src/pdm/cli/commands/run.py
- tests/cli/test_run.py
For correctly determining script recursion, rather than just multiple invocations of the same task/command e.g. when using different arguments, pass a copy of the `seen` set when recursively calling the next (nested) run task.
Otherwise, when a parent composite recursively runs a child composite, the original `seen` set will get mutated, which means any further invocations of the same child composite in the parent scope will be blocked by the (incorrect) recursion error.
Fixes issue #2829
> fix: do not trigger recursive script error on multiple invocations

- mkdocs.yml
- news/2841.doc.md
Build docs with Sphinx-style object inventory to support cross referencing from Sphinx documentation projects.
Addresses #2841.
- [Y ] A news fragment is added in `news/` describing what is new.
- [N/A] Test cases added for changed code.
Added a new flag `enable_inventory: true` in the MkDocs YML to allow the docs to be built with a Sphinx-style object inventory to support markup cross references from external Sphinx documentation projects.
> doc: build docs with Sphinx-style object inventory to support cross referencing from Sphinx documentation projects

- news/2839.bugfix.md
- src/pdm/installers/installers.py
- src/pdm/models/cached_package.py
- tests/test_installer.py
Since a few versions I was having a lot of `sync`/`install` failures due to some cache file collisions (especially the `.referrers` file).
This PR ensure installers (with or without cache) are tested against both `PythonEnvironement` (virtualenv) and `PythonLocalEnvironment` (PEP582) because installation and caching might differ between both. (Only the `PythonLocalEnvironment` was tested).
It also tests cached installations across multiple projects with those environments allowing to reproduce my `.referrers` case:
When installing with cache in a virtualenv env, the referrer files was not linked on first install (because created after installation) but it was on the 2nd one.
As a side-effect, when installing 2 already cached packages in the same virtualenv, the 2nd one was failing because …
> fix(cache): ensure installation and cache works with any environment

- news/2838.bugfix.md
- src/pdm/cli/completions/pdm.zsh
This PR is a simpler fix to #2840: only disable update checking in `zsh` completions.
Fixes #2838 
Supersedes and closes #2840
> fix(zsh): fix completion for `zsh` in when check update is enabled

- news/2849.bugfix.md
- src/pdm/cli/commands/run.py
- tests/cli/test_run.py
When running each script in a composite, instead of just forwarding `options` as defined on the current composite `Task`, merge them with input `opts` (from parent composite) using the already existing `exec_opts` helper function.
Fixes #2849
> fix: env inherited in nested composite

- docs/index.md
This docs-only change updates the windows install instruction from ``| py -``, which is not always available (depending on how exactly you installed python on your system), to ``| python -``, which is always available (unless you don't add python to your ``PATH`` at all, in which case, you probably know what's wrong). See: #2860
> Update windows install docs "py" -> "python" (fixes #2860)

- news/2852.bugfix.md
- src/pdm/cli/utils.py
- src/pdm/models/setup.py
> fix: pdm lock --update-reuse expands the $PROJECT_ROOT variable when extra dependencies are included

- news/2880.bugfix.md
- src/pdm/models/session.py
> fix: Proxy (HTTP_PROXY) settings are ignored for custom Repositories

- docs/usage/dependency.md
- docs/usage/scripts.md
* Fix the incorrect link for API doc
* Update the deprecated env var in the script example
> fix(docs): fix incorrect link and example

- docs/usage/scripts.md
- news/2924.feature.md
- src/pdm/cli/commands/run.py
- src/pdm/cli/commands/venv/backends.py
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- tests/cli/test_run.py
> feat: PEP 723: running scripts with inline metadata

- docs/usage/dependency.md
In my network environment, install package by git+ssh is much faster than git+https
As the document missing this topic, it cost me quick a while to get it work last time.
When searching `pdm add by git+ssh` at internet, it is not easy to get an example.
It will help people who prefer to use ssh, if example added to the document.
> doc: add example for install by git+ssh

- news/2944.feature.md
- src/pdm/builders/base.py
- src/pdm/builders/editable.py
- src/pdm/builders/sdist.py
- src/pdm/builders/wheel.py
- src/pdm/cli/options.py
- src/pdm/core.py
> feat: `pdm install --no-isolation` uses required build dependencies

- src/pdm/cli/commands/add.py
- src/pdm/cli/commands/info.py
- src/pdm/cli/commands/remove.py
- src/pdm/cli/commands/update.py
- src/pdm/cli/commands/use.py
This Pull Request introduces improved UI feedback for command-line operations that utilize the global flag (`-g`). The enhancements cover several key commands, ensuring users receive clear, immediate visual confirmation when they are working with global packages.
The following commands have been updated to provide explicit UI indications whenever the `-g` (global) flag is used:
- `pdm add -g`
- `pdm remove -g`
- `pdm update -g`
- `pdm use -g`
- `pdm info -g`
These changes aim to improve the user experience by making it transparent when actions are applied to global packages. This enhancement helps prevent confusion and ensures users are fully aware of the scope of their operations.
Thank you for considering this Pull Request. I look forward to your feedback and any further suggestions.
> feat: Enhance CLI UI Feedback for Global Flag Operations

- news/2956.feature.md
- src/pdm/project/lockfile.py
- src/pdm/project/project_file.py
> feat: calculate project file hash using the `tool.pdm.resolution` table

- news/2966.bugfix.md
- src/pdm/installers/synchronizers.py
> fix: don't install a local file if it doesn't change

- news/2974.bugfix.md
- src/pdm/cli/commands/list.py
- src/pdm/cli/commands/self_cmd.py
- src/pdm/installers/manager.py
- src/pdm/installers/uninstallers.py
- src/pdm/models/candidates.py
- src/pdm/models/project_info.py
- src/pdm/models/repositories.py
- src/pdm/models/requirements.py
- src/pdm/models/specifiers.py
- src/pdm/models/working_set.py
- src/pdm/utils.py
Fixes #2974
Still running the test suite locally to verify whether existing tests catch this.
> Fix incompatibility with importlib-metadata 8

- news/2943.bugfix.md
- pdm.lock
- pyproject.toml
- src/pdm/project/core.py
Fix for new pbs_installer interface regarding `build_dir` and best match auto-install strategy for `pdm-use`. Basically the same fix as for `pdm python install --list` recently.
> fix: pbs_installer interface (build_dir) for auto-install best match strategy

- .pre-commit-hooks.yaml
- news/2994.feature.md
Currently, pdm sync will not be triggered when "git rebase" which is supposed to be the "post-rewrite" stage. 
Let me know if you have any concern on this change.
Reference: https://[pre-commit](https://pre-commit.com/#post-rewrite).com/#post-rewrite
> feat: run pdm sync in post-rewrite stage of pre-commit

- docs/usage/dependency.md
- news/2896.feature.md
- src/pdm/cli/commands/add.py
- src/pdm/cli/commands/install.py
- src/pdm/cli/commands/lock.py
- src/pdm/cli/commands/remove.py
- src/pdm/cli/commands/update.py
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- src/pdm/cli/options.py
- src/pdm/core.py
- src/pdm/formats/requirements.py
- src/pdm/resolver/providers.py
- tests/cli/test_lock.py
- tests/fixtures/constraints.txt
> feat: Support for constraint files

- install-pdm.py
- install-pdm.py.sha256
Resolve all paths in `pdm-install` instead of only resolve user-specified path.
Fixes #2317.
It seems that there is a checksum (`.sha256`). Do I have to update it?
> fix: resolve to real path in install-pdm

- news/3016.feature.md
- src/pdm/cli/options.py
> feat: group options for update strategy and save strategy

- news/3031.zshcompletion.md
- src/pdm/cli/completions/pdm.zsh
zsh completions were broken. Fixed the syntax error
Tested against my oh-my-zsh setup.
1. Install system pdm 2.17.0
2. `pdm completion zsh > $ZSH_CUSTOM/plugins/pdm/_pdm`
3. Type `pdm sync --` then tab. Error is reproduced
```bash
$ pdm sync --zsh: command not found: *:: :->_subcmds
zsh: command not found: *:: :->_subcmds
zsh: command not found: *:: :->_subcmds
zsh: command not found: *:: :->_subcmds
zsh: command not found: *:: :->_subcmds
zsh: command not found: *:: :->_subcmds
```
4. From within pdm fork: `pdm sync && pdm run pdm completion zsh > $ZSH_CUSTOM/plugins/pdm/_pdm`
5. Type `pdm sync --` then tab. See expected completions.
Closes #3031
> fix: zsh completion syntax error

- news/3062.bugfix.md
- src/pdm/models/setup.py
> fix: No requires-python in project metadata crashes pdm

- news/3081.feature.md
- src/pdm/project/config.py
Adresses issue #3082 
This PR allows `pypi.verify_ssl` to be configured via `PDM_PYPI_VERIFY_SSL` environmental variable.
Test case not added (as I couldn't find any tests for `pypi.username` nor `pypi.password`), but I'll work on it if it's mandatory.
> feat: Allow pypi.verify_ssl to be configured via environmental variable

- docs/usage/scripts.md
- news/3087.bugfix.md
- src/pdm/cli/commands/run.py
- src/pdm/pytest.py
- tests/cli/test_run.py
> fix: make it able to expand project env vars in dotenv file

- news/3089.bugfix.md
- src/pdm/resolver/providers.py
> fix: a bug reusing the python markers from the existing lock when appending result

- news/3091.feature.md
- src/pdm/termui.py
> feat: clean logs older than a week

- docs/usage/config.md
- news/3076.feature.md
- src/pdm/models/session.py
> feat: respect ca certs in env vars

- news/3095.bugfix.md
- src/pdm/formats/requirements.py
- src/pdm/resolver/providers.py
> fix: pdm install from requirements.txt does not consider auto selected python version

- news/3107.bugfix.md
- src/pdm/models/candidates.py
- src/pdm/models/repositories/base.py
> fix: Struggling with installs from git -- `unearth.errors.UnpackError: fatal: couldn't find remote ref unknown`

- news/3123.bugfix.md
- src/pdm/cli/commands/export.py
> fix: pdm export -f requirements exports package twice

- news/3133.bugfix.md
- src/pdm/cli/commands/remove.py
- src/pdm/project/core.py
- tests/cli/test_remove.py
> fix: `add --dev --group test` ignores `dev` if empty group with that name already exists in optional-dependencies

- news/3137.bugfix.md
- src/pdm/cli/commands/venv/purge.py
The command `pdm venv remove in-project --yes` will remove the `.pdm-python` file if target of the python path is in the removed venv folder, but the `pdm venv purge` command does not.  This updates the `pdm venv purge` command to match the behavior of the former.
> fix: remove _saved_python when purging venv

- news/3152.bugfix.md
- pdm.lock
- pyproject.toml
- src/pdm/cli/commands/export.py
- tests/cli/test_others.py
> fix: allow no-marker option to work in pdm export command

- .gitignore
- news/3155.misc.md
- pyproject.toml
- src/pdm/__init__.py
- src/pdm/__version__.py
> chore: change project structure

- .github/workflows/ci.yml
- docs/usage/project.md
- news/3176.breaking.md
- news/3176.bugfix.md
- pdm.lock
- src/pdm/models/in_process/__init__.py
- src/pdm/models/in_process/env_spec.py
- tests/test_integration.py
- tox.ini
> fix: call funciton from dep-logic instead of implementing own

- news/3190.bugfix.md
- src/pdm/cli/actions.py
- tests/test_signals.py
Fixes #3190
I wasn't so sure about where it made the most sense to put the regression tests so let me know if there's a more sensible place for them, or if you have a better idea for how they should be written.
> fix: `pre_install`/`post_install` receiving a generator not a list

- news/3193.bugfix.md
- src/pdm/formats/uv.py
> fix: create backup file with random filename

- news/3202.bugfix.md
- src/pdm/resolver/providers.py
- tests/resolver/test_resolve.py
> fix: allow prereleases when the requirement is pinned even if disabled by project

- news/3215.feature.md
- pdm.lock
- src/pdm/cli/commands/python.py
- tests/cli/test_python.py
> feat: allow linking existing python interpreters to managed location

- news/3218.bugfix.md
- src/pdm/cli/commands/outdated.py
- tests/cli/test_outdated.py
> fix: list direct dependencies in pdm outdated by default

- news/3207.bugfix.md
- src/pdm/formats/uv.py
- src/pdm/installers/uv.py
> fix: infinite loop in uv mode

- docs/usage/advanced.md
- docs/usage/dependency.md
- docs/usage/lockfile.md
- news/3230.feature.md
- src/pdm/cli/commands/add.py
- src/pdm/cli/commands/remove.py
- src/pdm/cli/filters.py
- src/pdm/cli/options.py
- src/pdm/installers/core.py
- src/pdm/models/repositories/base.py
- src/pdm/models/repositories/lock.py
- src/pdm/models/repositories/pypi.py
- src/pdm/project/core.py
- src/pdm/project/project_file.py
- src/pdm/pytest.py
- src/pdm/resolver/base.py
- src/pdm/resolver/resolvelib.py
- src/pdm/resolver/uv.py
- tests/cli/test_add.py
- tests/cli/test_lock.py
- tests/cli/test_remove.py
- tests/fixtures/projects/test-package-type-fixer/pyproject.toml
- tests/resolver/test_uv_resolver.py
- tests/test_project.py
- tests/test_utils.py
> feat: support PEP 735 dependency groups

- src/pdm/cli/commands/run.py
FIPS errors with the following message:
```
File "/usr/lib/python3.11/site-packages/pdm/cli/commands/run.py", line 167, in _get_script_env
venv_name = hashlib.md5(os.path.realpath(script_file).encode("utf-8")).hexdigest()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_hashlib.UnsupportedDigestmodError: [digital envelope routines] unsupported
```
Since the hash isn't use for cryptographic use we indicate that md5 can be safely used
> Fix hashlib.md5 call for FIPS-enabled builds

- news/3235.misc.md
- pdm.lock
- src/pdm/resolver/providers.py
> chore(deps): update resolvelib to 1.1.0

- news/3232.bugfix.md
- src/pdm/project/core.py
> fix: inherit_metadata would be written in lock file if the file is not pdm.lock even strategy config is true

- news/3231.bug.md
- src/pdm/cli/commands/build.py
- tests/cli/test_build.py
> fix: build fails when use_uv is true

- install-pdm.py
- install-pdm.py.sha256
> Include post-release versions in default installation

- news/3247.bugfix.md
- src/pdm/cli/commands/add.py
- src/pdm/cli/filters.py
- src/pdm/project/core.py
- tests/cli/test_add.py
> fix: dependency group with non-normalized name does not work in pdm 2.20.0

- news/3254.bugfix.md
- src/pdm/models/session.py
- tests/models/test_session.py
Sort proxy_map after constructing URLPatterns. URLPattern has logic to make more specific patterns sort first. Current code instead sorts URLs as strings, which orders them lexicographically. This means that URLs from `no_proxy` usually sort *after* URLs from `all_proxy` and so `no_proxy` settings have no effect.
Fixes #3254
> Fix sorting of proxy_map in PDMPyPIClient

- src/pdm/cli/commands/fix/__init__.py
- src/pdm/cli/commands/fix/fixers.py
> feat: add a fixer for deprecating cross platform strategy

- news/3271.bugfix.md
- src/pdm/project/core.py
> fix: pdm 2.20.1 breaks when optional dependency groups contain underscores

- news/3270.feat.md
- pyproject.toml
- src/pdm/cli/utils.py
- src/pdm/core.py
- tests/cli/test_run.py
- tests/cli/test_utils.py
Signed-off-by: Manjusaka <me@manjusaka.me>
Support #3270
> feat: Output similar commands or script command when the input command is not correct

- news/3289.bugfix.md
- src/pdm/core.py
- src/pdm/models/in_process/sysconfig_get_paths.py
> fix: Fix the bug that pdm plugins are invalid on ubuntu system python(#3289)

- news/3313.feature.md
- src/pdm/cli/commands/run.py
- src/pdm/project/config.py
- tests/cli/test_run.py
This PR is a proposal implementation for #3313 introduces a `scripts.show_header` setting allowing to customize scripts display on run.
If set to `True`, running a script will display the help before running, fallback to the command args when no help has been set.
This setting do not have impact on verbose mode, which is still displaying script name and resolved args (and not help as help can be pretty but args are useful, and `verbose` mode is often meant for debug/diagnostic).
With the following `tool.pdm.scripts` section:
```toml
[tool.pdm.script]
hello = {cmd = "echo 'hello'", help = "Say hello"}
```
With the following `tool.pdm.scripts` section:
```toml
[tool.pdm.script]
hello = {cmd = "echo 'hello'", help = "Say hello"}
composite = { composite = ["hello", "hello"], help = "Do many …
```
> feat(run): allow customizing scripts display from settings (fix #3313)

- news/3328.feature.md
- src/pdm/cli/commands/search.py
- src/pdm/models/repositories/pypi.py
- src/pdm/models/search.py
- tests/cli/test_others.py
> fix: drop version from search result

- news/3332.bugfix.md
- src/pdm/resolver/uv.py
> fix(uv): Universal wheel can't be added as URL dependency as it's mismatched to current platform

- news/3359.feature.md
- src/pdm/installers/base.py
- src/pdm/installers/installers.py
- src/pdm/installers/manager.py
- src/pdm/models/candidates.py
- src/pdm/pytest.py
> fix: write installer metadata

- news/3362.bugfix.md
- src/pdm/models/backends.py
- src/pdm/models/candidates.py
- src/pdm/models/repositories/lock.py
- src/pdm/models/requirements.py
- src/pdm/project/core.py
- src/pdm/pytest.py
- src/pdm/utils.py
- tests/cli/test_add.py
- tests/cli/test_lock.py
- tests/cli/test_run.py
- tests/conftest.py
- tests/models/test_backends.py
- tests/models/test_candidates.py
- tests/models/test_requirements.py
- tests/test_utils.py
> fix: use stdlib url<->path conversion

- news/3366.bugfix.md
- src/pdm/cli/commands/venv/activate.py
- tests/cli/test_venv.py
`shellingham.detect_shell()` returns `('tcsh', '/bin/tcsh')` for tcsh on FreeBSD, so the current code tries to use the Bash venv activation script and fails due to syntax error. This change fixes the issue.
> Also use csh venv activation for tcsh

- news/3368.bugfix.md
- src/pdm/_types.py
- src/pdm/cli/commands/publish/__init__.py
- src/pdm/models/auth.py
- src/pdm/project/config.py
- src/pdm/project/core.py
- tests/cli/conftest.py
- tests/cli/test_config.py
> fix: cache the result of keyring queries

- news/3376.bugfix.md
- src/pdm/formats/poetry.py
- src/pdm/models/candidates.py
- src/pdm/models/requirements.py
- tests/models/test_candidates.py
- tests/models/test_requirements.py
> fix: don't validate requirements that are not used

- news/3382.bugfix.md
- src/pdm/cli/commands/run.py
- tests/test_integration.py
> fix: PDM fails running a script with  PEP723 metadata with `uv`

- news/3392.bugfix.md
- src/pdm/project/core.py
- tests/cli/test_add.py
Before this change, the `group` variable containing the group the user requested was being overridden with the last group processed from the `tool.pdm.dev-dependencies` table, making PDM add dev-dependencies to the wrong group.
~This is a draft PR since #3392 also mentions the duplication of groups between `tool.pdm.dev-dependencies` and `dependency-groups`. I'll be adding the news fragment and test cases in another commit once I finish setting up the dev environment.~ Finished!
Fixes #3392.
> fix: ensure dev-dependencies are added to the correct group

- news/3404.bugfix.md
- src/pdm/cli/commands/remove.py
- src/pdm/cli/filters.py
- tests/cli/test_remove.py
Fix #3404 
```bash
$ pytest -k "test_remove_exclude_non_existing_dev_group_in_lockfile"
================================================================================ test session starts ================================================================================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/huxuan/Code/pdm
configfile: pyproject.toml
testpaths: tests/
plugins: anyio-4.3.0, mock-3.14.0, rerunfailures-14.0, pytest_httpserver-1.1.0, cov-5.0.0, xdist-3.6.1
collected 987 items / 986 deselected / 1 selected                                                                                                                                   
tests/cli/test_remove.py F …
```
> fix: excluding non-existing groups for `pdm remove`

- news/3446.bugfix.md
- src/pdm/cli/actions.py
- src/pdm/cli/commands/add.py
- src/pdm/exceptions.py
- src/pdm/resolver/providers.py
> fix: PDM removes override URL and some groups from deps in `pdm.lock` upon adding a new dependency.

- news/3401.bug.md
- src/pdm/cli/actions.py
- src/pdm/cli/commands/sync.py
- fix https://github.com/pdm-project/pdm/issues/3401
> fix: pass the `--quiet` option to `pdm sync`

- news/3417.bugfix.md
- src/pdm/cli/commands/use.py
- src/pdm/cli/commands/venv/backends.py
- src/pdm/project/config.py
- src/pdm/project/core.py
- tests/test_integration.py
Local .python-version flies with multiple versions will be ignored, as they do not provide a single version to consider. Hence it should not be used and can safely be ignored.
Closes #3417
> fix: If a multiline .python-version is found, it is ignored

- CONTRIBUTING.md
- pyproject.toml
> fix: faster pytest local same as ci info to dev doc

- CHANGELOG.md
- news/3476.feature.md
- src/pdm/cli/commands/init.py
> fix: add name to pdm new

- src/pdm/cli/commands/init.py
- src/pdm/cli/completions/pdm.bash
- src/pdm/cli/completions/pdm.fish
- src/pdm/cli/completions/pdm.ps1
- src/pdm/cli/completions/pdm.zsh
- src/pdm/cli/templates/minimal/.gitignore
> feat: initialize git repository when running `pdm init`

- news/3487.bugfix.md
- tests/models/test_candidates.py
- tests/test_project.py
Mark two more fails with the `network` marker, as they fail without Internet access, as noted in #3487.
> fix: Mark two more tests as requiring network (#3487)

- src/pdm/cli/commands/venv/backends.py
Fixes #3495.
The command `uv venv` takes a `--seed` flag with no parameters.
> fix: make `pdm venv create --with-pip --with uv` pass correct args to `uv`

- src/pdm/pytest.py
Revert part of the changes to `project_no_init` fixture introduced as part of 224663a601548108daac947531442b4af56a9747 that replaced `sys.executable` with `find_python_in_path()` call.  The latter code works correctly only if a single Python version is installed in `sys.base_prefix`.  When more than one version is installed, `find_python_in_path()` can choose an arbitrary Python version, effectively causing a mismatch between the version used by the test suite and the fixture, effectively causing test failures due to mismatched expectations.
Fixes #3486
> fix: Use `sys.executable` in `project_no_init` pytest fixture

- news/3565.bugfix.md
- src/pdm/models/repositories/lock.py
> fix: editable local packages causes empty urls when pylock is used

- mkdocs.yml
Added a toggle to select the documentation color scheme based on system preference. Additionally, the icons for light and dark mode were adjusted to match the automatic toggle icon.
Related mkdocs documentation: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
> Docs: Select color scheme based on system preference

- news/3552.feature.md
- src/pdm/cli/commands/python.py
Fixes https://github.com/pdm-project/pdm/issues/3552
- `pdm python install -v` command now shows the download URL 
```
STATUS: Downloading cpython@3.13.5 https://github.com/astral-sh/python-build-standalone/releases/download/20250723/cpython-3.13.5%2B20250723-x86_64-pc-windows-msvc-install_only.tar.gz
```
> feat: show download URL in 'pdm python install -v'

- CONTRIBUTING.md
`prefligit` was renamed to `prek`, update the contribution guide to reflect that.
> docs: update `prefligit` to `prek`

- news/3602.dep.md
- pdm.lock
- pyproject.toml
> dep: Bump truststore to version 0.10.4

- news/3610.bugfix.md
- src/pdm/cli/actions.py
> fix: prevent hash clearing when appending to lockfile with env_spec

- news/3617.bugfix.md
- src/pdm/cli/commands/publish/__init__.py
As described here for twine (https://github.com/pypa/twine/pull/1221), Sonatype changed its error message if packages already exists with version 3.70.x. This PR modifies the recognition for the `--skip-existing` option to support also those versions.
> fix: `publish --skip-existing` for Nexus Repository OSS >= 3.70
